#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_public_return_request
import ../models/model_public_return_response
import ../models/model_public_return_status_response

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc getPublicReturnStatus*(httpClient: HttpClient, email: string, returnNumber: string, returnOrderId: string, orderNumber: string): (Option[PublicReturnStatusResponse], Response) =
  ## Customer checks the status of a return (public, no auth). The return is only revealed when its linked order's email matches.
  var query_params_list: seq[(string, string)] = @[]
  if $returnNumber != "":
    query_params_list.add(("returnNumber", $returnNumber))
  if $returnOrderId != "":
    query_params_list.add(("returnOrderId", $returnOrderId))
  query_params_list.add(("email", $email))
  if $orderNumber != "":
    query_params_list.add(("orderNumber", $orderNumber))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/public/returns/status" & "?" & url_encoded_query_params)
  constructResult[PublicReturnStatusResponse](response)


proc listPublicReturns*(httpClient: HttpClient, orderNumber: string, email: string): (Option[seq[PublicReturnStatusResponse]], Response) =
  ## List all returns for an order (public, no auth).
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("orderNumber", $orderNumber))
  query_params_list.add(("email", $email))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/public/returns/list" & "?" & url_encoded_query_params)
  constructResult[seq[PublicReturnStatusResponse]](response)


proc requestPublicReturn*(httpClient: HttpClient, publicReturnRequest: PublicReturnRequest): (Option[PublicReturnResponse], Response) =
  ## Customer requests a return for an order (public, no auth).
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/public/returns/request", $(%publicReturnRequest))
  constructResult[PublicReturnResponse](response)

