#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_create_connection_request
import ../models/model_marketplace_connection
import ../models/model_o_auth_authorize_request
import ../models/model_o_auth_authorize_response
import ../models/model_o_auth_callback_request
import ../models/model_platform_info
import ../models/model_sync_log
import ../models/model_sync_summary
import ../models/model_update_connection_request
import ../models/model_update_sync_direction_request

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createConnectionApi*(httpClient: HttpClient, createConnectionRequest: CreateConnectionRequest): (Option[MarketplaceConnection], Response) =
  ## Create a new connection (for API-key based platforms)
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/marketplace/connections", $(%createConnectionRequest))
  constructResult[MarketplaceConnection](response)


proc deleteConnectionApi*(httpClient: HttpClient, connectionId: string): Response =
  ## Soft-delete a connection
  httpClient.delete(basepath & fmt"/api/v1/marketplace/connections/{connection_id}")



proc getConnectionApi*(httpClient: HttpClient, connectionId: string): (Option[MarketplaceConnection], Response) =
  ## Get a single connection

  let response = httpClient.get(basepath & fmt"/api/v1/marketplace/connections/{connection_id}")
  constructResult[MarketplaceConnection](response)


proc getSyncDirectionApi*(httpClient: HttpClient, connectionId: string): Response =
  ## Get current sync direction configuration for a connection
  httpClient.get(basepath & fmt"/api/v1/marketplace/connections/{connection_id}/directions")



proc getSyncLogsApi*(httpClient: HttpClient, connectionId: string): (Option[seq[SyncLog]], Response) =
  ## Get sync logs for a connection

  let response = httpClient.get(basepath & fmt"/api/v1/marketplace/connections/{connection_id}/logs")
  constructResult[seq[SyncLog]](response)


proc listConnectionsApi*(httpClient: HttpClient): (Option[seq[MarketplaceConnection]], Response) =
  ## List connections for the current tenant

  let response = httpClient.get(basepath & "/api/v1/marketplace/connections")
  constructResult[seq[MarketplaceConnection]](response)


proc listPlatformsApi*(httpClient: HttpClient): (Option[seq[PlatformInfo]], Response) =
  ## List all supported platforms

  let response = httpClient.get(basepath & "/api/v1/marketplace/platforms")
  constructResult[seq[PlatformInfo]](response)


proc oauthAuthorizeApi*(httpClient: HttpClient, oAuthAuthorizeRequest: OAuthAuthorizeRequest): (Option[OAuthAuthorizeResponse], Response) =
  ## OAuth: initiate authorization flow
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/marketplace/oauth/authorize", $(%oAuthAuthorizeRequest))
  constructResult[OAuthAuthorizeResponse](response)


proc oauthCallbackApi*(httpClient: HttpClient, oAuthCallbackRequest: OAuthCallbackRequest): (Option[MarketplaceConnection], Response) =
  ## OAuth: handle callback after authorization
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/marketplace/oauth/callback", $(%oAuthCallbackRequest))
  constructResult[MarketplaceConnection](response)


proc triggerSyncApi*(httpClient: HttpClient, connectionId: string, syncType: string, direction: string): (Option[SyncSummary], Response) =
  ## Trigger sync for a connection
  var query_params_list: seq[(string, string)] = @[]
  if $syncType != "":
    query_params_list.add(("sync_type", $syncType))
  if $direction != "":
    query_params_list.add(("direction", $direction))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/marketplace/connections/{connection_id}/sync" & "?" & url_encoded_query_params)
  constructResult[SyncSummary](response)


proc updateConnectionApi*(httpClient: HttpClient, connectionId: string, updateConnectionRequest: UpdateConnectionRequest): (Option[MarketplaceConnection], Response) =
  ## Update a connection
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/marketplace/connections/{connection_id}", $(%updateConnectionRequest))
  constructResult[MarketplaceConnection](response)


proc updateSyncDirectionApi*(httpClient: HttpClient, connectionId: string, updateSyncDirectionRequest: UpdateSyncDirectionRequest): Response =
  ## Update per-entity sync direction configuration for a connection
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.put(basepath & fmt"/api/v1/marketplace/connections/{connection_id}/directions", $(%updateSyncDirectionRequest))



proc webhookReceiverApi*(httpClient: HttpClient, platform: string, connectionId: string): Response =
  ## Webhook receiver
  httpClient.post(basepath & fmt"/api/v1/marketplace/webhook/{platform}/{connection_id}")


