#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_generate_variants_request
import ../models/model_plugin_error
import ../models/model_product_variant

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createProductVariant*(httpClient: HttpClient, productVariant: ProductVariant): (Option[ProductVariant], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/product-variants", $(%productVariant))
  constructResult[ProductVariant](response)


proc deleteProductVariant*(httpClient: HttpClient, variantId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/product-variants/{variant_id}")



proc generateProductVariants*(httpClient: HttpClient, generateVariantsRequest: GenerateVariantsRequest): (Option[seq[ProductVariant]], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/product-variants/generate", $(%generateVariantsRequest))
  constructResult[seq[ProductVariant]](response)


proc getProductVariant*(httpClient: HttpClient, variantId: string): (Option[ProductVariant], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/product-variants/{variant_id}")
  constructResult[ProductVariant](response)


proc listProductVariants*(httpClient: HttpClient, page: int, pageSize: int, productId: stringstring, isActive: bool): (Option[seq[ProductVariant]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $productId != "":
    query_params_list.add(("product_id", $productId))
  if $isActive != "":
    query_params_list.add(("is_active", $isActive))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/product-variants/" & "?" & url_encoded_query_params)
  constructResult[seq[ProductVariant]](response)


proc updateProductVariant*(httpClient: HttpClient, variantId: string, body: JsonNode): (Option[ProductVariant], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/product-variants/{variant_id}", $(%body))
  constructResult[ProductVariant](response)

