#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_pos_register
import ../models/model_pos_register_create
import ../models/model_pos_table
import ../models/model_pos_table_create

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc posBilling*(httpClient: HttpClient): (Option[JsonNode], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/pos/billing")
  constructResult[JsonNode](response)


proc posCreateOrder*(httpClient: HttpClient, body: JsonNode): (Option[JsonNode], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/orders", $(%body))
  constructResult[JsonNode](response)


proc posCreateRegister*(httpClient: HttpClient, posRegisterCreate: PosRegisterCreate): (Option[PosRegister], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/registers", $(%posRegisterCreate))
  constructResult[PosRegister](response)


proc posCreateTable*(httpClient: HttpClient, posTableCreate: PosTableCreate): (Option[PosTable], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/tables", $(%posTableCreate))
  constructResult[PosTable](response)


proc posDisableRegister*(httpClient: HttpClient, id: stringstring): (Option[PosRegister], Response) =
  ## 

  let response = httpClient.post(basepath & fmt"/api/pos/registers/{id}/disable")
  constructResult[PosRegister](response)


proc posFreeTable*(httpClient: HttpClient, id: stringstring): (Option[PosTable], Response) =
  ## 

  let response = httpClient.post(basepath & fmt"/api/pos/tables/{id}/free")
  constructResult[PosTable](response)


proc posKasseClosing*(httpClient: HttpClient, body: JsonNode): (Option[JsonNode], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/kasse/closing", $(%body))
  constructResult[JsonNode](response)


proc posKasseEntries*(httpClient: HttpClient): (Option[JsonNode], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/pos/kasse/entries")
  constructResult[JsonNode](response)


proc posKasseExport*(httpClient: HttpClient): (Option[JsonNode], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/pos/kasse/export")
  constructResult[JsonNode](response)


proc posKassePayInOut*(httpClient: HttpClient, body: JsonNode): (Option[JsonNode], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/kasse/pay-in-out", $(%body))
  constructResult[JsonNode](response)


proc posListOrders*(httpClient: HttpClient, status: string): (Option[JsonNode], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $status != "":
    query_params_list.add(("status", $status))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/pos/orders" & "?" & url_encoded_query_params)
  constructResult[JsonNode](response)


proc posListProducts*(httpClient: HttpClient, q: string): (Option[JsonNode], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $q != "":
    query_params_list.add(("q", $q))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/pos/products" & "?" & url_encoded_query_params)
  constructResult[JsonNode](response)


proc posListRegisters*(httpClient: HttpClient): (Option[seq[PosRegister]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/pos/registers")
  constructResult[seq[PosRegister]](response)


proc posListTables*(httpClient: HttpClient): (Option[seq[PosTable]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/pos/tables")
  constructResult[seq[PosTable]](response)


proc posOrderPrint*(httpClient: HttpClient, orderNumber: string): (Option[JsonNode], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/pos/orders/{order_number}/print")
  constructResult[JsonNode](response)


proc posOrderReceipt*(httpClient: HttpClient, orderNumber: string): (Option[JsonNode], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/pos/orders/{order_number}/receipt")
  constructResult[JsonNode](response)


proc posPayOrder*(httpClient: HttpClient, orderNumber: string, body: JsonNode): (Option[JsonNode], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & fmt"/api/pos/orders/{order_number}/pay", $(%body))
  constructResult[JsonNode](response)


proc posSumupCheckout*(httpClient: HttpClient, body: JsonNode): (Option[JsonNode], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/pos/sumup/checkout", $(%body))
  constructResult[JsonNode](response)

