#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_convert_response
import ../models/model_plugin_error
import ../models/model_proforma_invoice

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc convertProformaToInvoice*(httpClient: HttpClient, proformaId: string): (Option[ConvertResponse], Response) =
  ## 

  let response = httpClient.post(basepath & fmt"/api/v1/proforma-invoices/{proforma_id}/convert")
  constructResult[ConvertResponse](response)


proc createProformaInvoice*(httpClient: HttpClient, proformaInvoice: ProformaInvoice): (Option[ProformaInvoice], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/proforma-invoices", $(%proformaInvoice))
  constructResult[ProformaInvoice](response)


proc deleteProformaInvoice*(httpClient: HttpClient, proformaId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/proforma-invoices/{proforma_id}")



proc getProformaInvoice*(httpClient: HttpClient, proformaId: string): (Option[ProformaInvoice], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/proforma-invoices/{proforma_id}")
  constructResult[ProformaInvoice](response)


proc listProformaInvoices*(httpClient: HttpClient, page: int, pageSize: int, status: string, customerId: string, orderNumber: string): (Option[seq[ProformaInvoice]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $status != "":
    query_params_list.add(("status", $status))
  if $customerId != "":
    query_params_list.add(("customer_id", $customerId))
  if $orderNumber != "":
    query_params_list.add(("order_number", $orderNumber))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/proforma-invoices/" & "?" & url_encoded_query_params)
  constructResult[seq[ProformaInvoice]](response)


proc updateProformaInvoice*(httpClient: HttpClient, proformaId: string, body: JsonNode): (Option[ProformaInvoice], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/proforma-invoices/{proforma_id}", $(%body))
  constructResult[ProformaInvoice](response)

