#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_api_response_subscription_overview
import ../models/model_api_response_vec_plan
import ../models/model_quota_override

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc getPlans*(httpClient: HttpClient): (Option[ApiResponse_Vec_Plan], Response) =
  ## All canonical plans (free/starter/business/enterprise) — the single source of truth lives in `crate::saasy::plans`, matching marketing.

  let response = httpClient.get(basepath & "/api/v1/plans")
  constructResult[ApiResponse_Vec_Plan](response)


proc getQuotaApi*(httpClient: HttpClient): Response =
  ## Effective limits + current usage for the calling tenant.
  httpClient.get(basepath & "/api/v1/quota")



proc getSubscriptionApi*(httpClient: HttpClient): (Option[ApiResponse_SubscriptionOverview], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/v1/subscription")
  constructResult[ApiResponse_SubscriptionOverview](response)


proc getUsageApi*(httpClient: HttpClient, meter: string): Response =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $meter != "":
    query_params_list.add(("meter", $meter))
  let url_encoded_query_params = encodeQuery(query_params_list)
  httpClient.get(basepath & "/api/v1/usage" & "?" & url_encoded_query_params)



proc paddleSubscriptionWebhook*(httpClient: HttpClient): Response =
  ## Paddle Billing subscription webhook. Verifies the `Paddle-Signature` header (HMAC-SHA256 over `\"{ts}:{raw_body}\"` with the webhook secret), then updates `billing_info` and `tenants.plan` for the tenant identified by the subscription `custom_data` (JSON `{\"tenant_id\": \"...\"}` or a bare tenant UUID).
  httpClient.post(basepath & "/api/webhooks/paddle/subscription")



proc putQuotaApi*(httpClient: HttpClient, quotaOverride: QuotaOverride): Response =
  ## Write the per-tenant quota override (`admin:settings`). An empty object clears the override.
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.put(basepath & "/api/v1/quota", $(%quotaOverride))


