#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_appointment_status_update
import ../models/model_delivery_appointment
import ../models/model_delivery_appointment_create
import ../models/model_plugin_error
import ../models/model_public_delivery_appointment_request
import ../models/model_public_delivery_appointment_response
import ../models/model_public_delivery_appointment_status_response

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createDeliveryAppointment*(httpClient: HttpClient, deliveryAppointmentCreate: DeliveryAppointmentCreate): (Option[DeliveryAppointment], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/delivery-appointments", $(%deliveryAppointmentCreate))
  constructResult[DeliveryAppointment](response)


proc deleteDeliveryAppointment*(httpClient: HttpClient, appointmentId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/delivery-appointments/{appointment_id}")



proc getDeliveryAppointment*(httpClient: HttpClient, appointmentId: string): (Option[DeliveryAppointment], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/delivery-appointments/{appointment_id}")
  constructResult[DeliveryAppointment](response)


proc getPublicDeliveryAppointmentStatus*(httpClient: HttpClient, appointmentId: string, email: string, token: string): (Option[PublicDeliveryAppointmentStatusResponse], Response) =
  ## Supplier/carrier checks appointment status (public, no auth). The appointment is only revealed when email AND token match.
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("appointmentId", $appointmentId))
  query_params_list.add(("email", $email))
  query_params_list.add(("token", $token))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/public/delivery-appointments/status" & "?" & url_encoded_query_params)
  constructResult[PublicDeliveryAppointmentStatusResponse](response)


proc listDeliveryAppointments*(httpClient: HttpClient, page: int, pageSize: int, status: string, warehouseId: string, `from`: string, to: string): (Option[seq[DeliveryAppointment]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $status != "":
    query_params_list.add(("status", $status))
  if $warehouseId != "":
    query_params_list.add(("warehouse_id", $warehouseId))
  if $`from` != "":
    query_params_list.add(("from", $`from`))
  if $to != "":
    query_params_list.add(("to", $to))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/delivery-appointments" & "?" & url_encoded_query_params)
  constructResult[seq[DeliveryAppointment]](response)


proc requestPublicDeliveryAppointment*(httpClient: HttpClient, publicDeliveryAppointmentRequest: PublicDeliveryAppointmentRequest): (Option[PublicDeliveryAppointmentResponse], Response) =
  ## Supplier/carrier requests an inbound delivery slot (public, no auth). The tenant is derived from the warehouse found by `code` — never from the request.
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/public/delivery-appointments/request", $(%publicDeliveryAppointmentRequest))
  constructResult[PublicDeliveryAppointmentResponse](response)


proc updateDeliveryAppointment*(httpClient: HttpClient, appointmentId: string, body: JsonNode): (Option[DeliveryAppointment], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/delivery-appointments/{appointment_id}", $(%body))
  constructResult[DeliveryAppointment](response)


proc updateDeliveryAppointmentStatus*(httpClient: HttpClient, appointmentId: string, appointmentStatusUpdate: AppointmentStatusUpdate): (Option[DeliveryAppointment], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/delivery-appointments/{appointment_id}/status", $(%appointmentStatusUpdate))
  constructResult[DeliveryAppointment](response)

