#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_datev_booking_preview
import ../models/model_datev_export_response

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc datevExportApi*(httpClient: HttpClient, accountSchema: string, dateFrom: string, dateTo: string, page: int, pageSize: int): (Option[DatevExportResponse], Response) =
  ## Export bookkeeping data as DATEV CSV
  var query_params_list: seq[(string, string)] = @[]
  if $accountSchema != "":
    query_params_list.add(("account_schema", $accountSchema))
  if $dateFrom != "":
    query_params_list.add(("date_from", $dateFrom))
  if $dateTo != "":
    query_params_list.add(("date_to", $dateTo))
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/datev/export" & "?" & url_encoded_query_params)
  constructResult[DatevExportResponse](response)


proc datevPreviewApi*(httpClient: HttpClient, accountSchema: string, dateFrom: string, dateTo: string, page: int, pageSize: int): (Option[seq[DatevBookingPreview]], Response) =
  ## Exported_datev_bookings: returns formed bookings for review
  var query_params_list: seq[(string, string)] = @[]
  if $accountSchema != "":
    query_params_list.add(("account_schema", $accountSchema))
  if $dateFrom != "":
    query_params_list.add(("date_from", $dateFrom))
  if $dateTo != "":
    query_params_list.add(("date_to", $dateTo))
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/datev/preview" & "?" & url_encoded_query_params)
  constructResult[seq[DatevBookingPreview]](response)

