#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_delivery_date
import ../models/model_delivery_date_create
import ../models/model_delivery_date_status_update
import ../models/model_plugin_error

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createDeliveryDate*(httpClient: HttpClient, deliveryDateCreate: DeliveryDateCreate): (Option[DeliveryDate], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/delivery-dates", $(%deliveryDateCreate))
  constructResult[DeliveryDate](response)


proc deleteDeliveryDate*(httpClient: HttpClient, deliveryDateId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/delivery-dates/{delivery_date_id}")



proc getDeliveryDate*(httpClient: HttpClient, deliveryDateId: string): (Option[DeliveryDate], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/delivery-dates/{delivery_date_id}")
  constructResult[DeliveryDate](response)


proc getDeliveryPerformance*(httpClient: HttpClient, page: int, pageSize: int, orderNumber: string, status: string, `from`: string, to: string): (Option[JsonNode], Response) =
  ## On-time performance summary: how many promised delivery dates were met within a period.
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("pageSize", $pageSize))
  if $orderNumber != "":
    query_params_list.add(("orderNumber", $orderNumber))
  if $status != "":
    query_params_list.add(("status", $status))
  if $`from` != "":
    query_params_list.add(("from", $`from`))
  if $to != "":
    query_params_list.add(("to", $to))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/delivery-dates/performance" & "?" & url_encoded_query_params)
  constructResult[JsonNode](response)


proc listDeliveryDates*(httpClient: HttpClient, page: int, pageSize: int, orderNumber: string, status: string, `from`: string, to: string): (Option[seq[DeliveryDate]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("pageSize", $pageSize))
  if $orderNumber != "":
    query_params_list.add(("orderNumber", $orderNumber))
  if $status != "":
    query_params_list.add(("status", $status))
  if $`from` != "":
    query_params_list.add(("from", $`from`))
  if $to != "":
    query_params_list.add(("to", $to))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/delivery-dates/" & "?" & url_encoded_query_params)
  constructResult[seq[DeliveryDate]](response)


proc updateDeliveryDate*(httpClient: HttpClient, deliveryDateId: string, body: JsonNode): (Option[DeliveryDate], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/delivery-dates/{delivery_date_id}", $(%body))
  constructResult[DeliveryDate](response)


proc updateDeliveryDateStatus*(httpClient: HttpClient, deliveryDateId: string, deliveryDateStatusUpdate: DeliveryDateStatusUpdate): (Option[DeliveryDate], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/delivery-dates/{delivery_date_id}/status", $(%deliveryDateStatusUpdate))
  constructResult[DeliveryDate](response)

