#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_stock_adjustment
import ../models/model_warehouse_stock

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createWarehouseStock*(httpClient: HttpClient, warehouseId: string, stockAdjustment: StockAdjustment): (Option[WarehouseStock], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & fmt"/api/v1/warehouses/{warehouse_id}/stock", $(%stockAdjustment))
  constructResult[WarehouseStock](response)


proc deleteWarehouseStock*(httpClient: HttpClient, warehouseId: string, productId: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/warehouses/{warehouse_id}/stock/{product_id}")



proc listWarehouseStock*(httpClient: HttpClient, warehouseId: string): (Option[seq[WarehouseStock]], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/warehouses/{warehouse_id}/stock")
  constructResult[seq[WarehouseStock]](response)


proc updateWarehouseStock*(httpClient: HttpClient, warehouseId: string, productId: stringstring, stockAdjustment: StockAdjustment): (Option[WarehouseStock], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/warehouses/{warehouse_id}/stock/{product_id}", $(%stockAdjustment))
  constructResult[WarehouseStock](response)

