#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_bom
import ../models/model_bom_create
import ../models/model_bom_update
import ../models/model_plugin_error

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createBom*(httpClient: HttpClient, bomCreate: BomCreate): (Option[Bom], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/boms", $(%bomCreate))
  constructResult[Bom](response)


proc deleteBom*(httpClient: HttpClient, bomId: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/boms/{bom_id}")



proc getBom*(httpClient: HttpClient, bomId: stringstring): (Option[Bom], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/boms/{bom_id}")
  constructResult[Bom](response)


proc listBoms*(httpClient: HttpClient, page: int, pageSize: int, search: string, productId: stringstring): (Option[seq[Bom]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("pageSize", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $productId != "":
    query_params_list.add(("productId", $productId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/boms/" & "?" & url_encoded_query_params)
  constructResult[seq[Bom]](response)


proc updateBom*(httpClient: HttpClient, bomId: stringstring, bomUpdate: BomUpdate): (Option[Bom], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/boms/{bom_id}", $(%bomUpdate))
  constructResult[Bom](response)

