#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_labor_cost_row
import ../models/model_plugin_error
import ../models/model_time_entry_clock_in
import ../models/model_time_entry_clock_out
import ../models/model_time_entry_dto

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc clockInTimeEntry*(httpClient: HttpClient, timeEntryClockIn: TimeEntryClockIn): (Option[TimeEntryDto], Response) =
  ## Clock in for the authenticated user (resolved via their employee profile).
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/time-entries", $(%timeEntryClockIn))
  constructResult[TimeEntryDto](response)


proc clockOutTimeEntry*(httpClient: HttpClient, id: stringstring, timeEntryClockOut: TimeEntryClockOut): (Option[TimeEntryDto], Response) =
  ## Clock out an entry: the entry's owner, or anyone with `time_entries:write`.
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.patch(basepath & fmt"/api/v1/time-entries/{id}", $(%timeEntryClockOut))
  constructResult[TimeEntryDto](response)


proc getLaborCosts*(httpClient: HttpClient, `from`: string, to: string, groupBy: string): (Option[seq[LaborCostRow]], Response) =
  ## Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee's hourly cost rate.
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("from", $`from`))
  query_params_list.add(("to", $to))
  query_params_list.add(("group_by", $groupBy))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/labor-costs" & "?" & url_encoded_query_params)
  constructResult[seq[LaborCostRow]](response)


proc listTimeEntries*(httpClient: HttpClient, `from`: string, to: string, active: bool, employeeId: stringstring): (Option[seq[TimeEntryDto]], Response) =
  ## List time entries with optional date-range / active / employee filters.
  var query_params_list: seq[(string, string)] = @[]
  if $`from` != "":
    query_params_list.add(("from", $`from`))
  if $to != "":
    query_params_list.add(("to", $to))
  if $active != "":
    query_params_list.add(("active", $active))
  if $employeeId != "":
    query_params_list.add(("employee_id", $employeeId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/time-entries" & "?" & url_encoded_query_params)
  constructResult[seq[TimeEntryDto]](response)

