#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_create_emission_entry
import ../models/model_create_emission_target
import ../models/model_emission_entry
import ../models/model_emission_factor_response
import ../models/model_emission_target
import ../models/model_emissions_export_response
import ../models/model_emissions_report
import ../models/model_plugin_error

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createEmissionEntryApi*(httpClient: HttpClient, createEmissionEntry: CreateEmissionEntry): (Option[EmissionEntry], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/bookkeeping/emissions/entries", $(%createEmissionEntry))
  constructResult[EmissionEntry](response)


proc createEmissionTargetApi*(httpClient: HttpClient, createEmissionTarget: CreateEmissionTarget): (Option[EmissionTarget], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/bookkeeping/emissions/targets", $(%createEmissionTarget))
  constructResult[EmissionTarget](response)


proc deleteEmissionEntryApi*(httpClient: HttpClient, id: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/bookkeeping/emissions/entries/{id}")



proc deleteEmissionTargetApi*(httpClient: HttpClient, id: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/bookkeeping/emissions/targets/{id}")



proc emissionsEntriesApi*(httpClient: HttpClient, year: int): (Option[seq[EmissionEntry]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("year", $year))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/emissions/entries" & "?" & url_encoded_query_params)
  constructResult[seq[EmissionEntry]](response)


proc emissionsExportApi*(httpClient: HttpClient, year: int): (Option[EmissionsExportResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("year", $year))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/emissions/export" & "?" & url_encoded_query_params)
  constructResult[EmissionsExportResponse](response)


proc emissionsFactorsApi*(httpClient: HttpClient): (Option[seq[EmissionFactorResponse]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/emissions/factors")
  constructResult[seq[EmissionFactorResponse]](response)


proc emissionsReportApi*(httpClient: HttpClient, year: int): (Option[EmissionsReport], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("year", $year))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/emissions/report" & "?" & url_encoded_query_params)
  constructResult[EmissionsReport](response)


proc emissionsTargetsApi*(httpClient: HttpClient): (Option[seq[EmissionTarget]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/emissions/targets")
  constructResult[seq[EmissionTarget]](response)

