#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_plugin_error
import ../models/model_warehouse

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createWarehouse*(httpClient: HttpClient, warehouse: Warehouse): (Option[Warehouse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/warehouses", $(%warehouse))
  constructResult[Warehouse](response)


proc deleteWarehouse*(httpClient: HttpClient, warehouseId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/warehouses/{warehouse_id}")



proc getWarehouse*(httpClient: HttpClient, warehouseId: string): (Option[Warehouse], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/warehouses/{warehouse_id}")
  constructResult[Warehouse](response)


proc listWarehouses*(httpClient: HttpClient, page: int, pageSize: int, search: string, isActive: bool): (Option[seq[Warehouse]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $isActive != "":
    query_params_list.add(("is_active", $isActive))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/warehouses/" & "?" & url_encoded_query_params)
  constructResult[seq[Warehouse]](response)


proc updateWarehouse*(httpClient: HttpClient, warehouseId: string, body: JsonNode): (Option[Warehouse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/warehouses/{warehouse_id}", $(%body))
  constructResult[Warehouse](response)

