#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_stock_movement

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc getStockMovement*(httpClient: HttpClient, movementId: string): (Option[StockMovement], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/stock-movements/{movement_id}")
  constructResult[StockMovement](response)


proc listStockMovements*(httpClient: HttpClient, page: int, pageSize: int, productId: stringstring, warehouseId: string, movementType: string, `from`: string, to: string): (Option[seq[StockMovement]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("pageSize", $pageSize))
  if $productId != "":
    query_params_list.add(("productId", $productId))
  if $warehouseId != "":
    query_params_list.add(("warehouseId", $warehouseId))
  if $movementType != "":
    query_params_list.add(("movementType", $movementType))
  if $`from` != "":
    query_params_list.add(("from", $`from`))
  if $to != "":
    query_params_list.add(("to", $to))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/stock-movements/" & "?" & url_encoded_query_params)
  constructResult[seq[StockMovement]](response)

