#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_plugin_error
import ../models/model_return_logistics_queue_item
import ../models/model_return_logistics_summary
import ../models/model_return_order
import ../models/model_return_order_status_update

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createReturnOrder*(httpClient: HttpClient, returnOrder: ReturnOrder): (Option[ReturnOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/returns", $(%returnOrder))
  constructResult[ReturnOrder](response)


proc deleteReturnOrder*(httpClient: HttpClient, returnOrderId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/returns/{return_order_id}")



proc getReturnOrder*(httpClient: HttpClient, returnOrderId: string): (Option[ReturnOrder], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/returns/{return_order_id}")
  constructResult[ReturnOrder](response)


proc listReturnOrders*(httpClient: HttpClient, page: int, pageSize: int, status: string, customerName: string, orderNumber: string): (Option[seq[ReturnOrder]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $status != "":
    query_params_list.add(("status", $status))
  if $customerName != "":
    query_params_list.add(("customer_name", $customerName))
  if $orderNumber != "":
    query_params_list.add(("order_number", $orderNumber))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/returns/" & "?" & url_encoded_query_params)
  constructResult[seq[ReturnOrder]](response)


proc returnLogisticsQueue*(httpClient: HttpClient): (Option[seq[ReturnLogisticsQueueItem]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/v1/returns/logistics-queue")
  constructResult[seq[ReturnLogisticsQueueItem]](response)


proc returnLogisticsSummary*(httpClient: HttpClient): (Option[ReturnLogisticsSummary], Response) =
  ## Returns-logistics aggregation for the dashboard: quantities received, restocked and scrapped per warehouse.

  let response = httpClient.get(basepath & "/api/v1/returns/logistics-summary")
  constructResult[ReturnLogisticsSummary](response)


proc updateReturnOrder*(httpClient: HttpClient, returnOrderId: string, body: JsonNode): (Option[ReturnOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/returns/{return_order_id}", $(%body))
  constructResult[ReturnOrder](response)


proc updateReturnOrderStatus*(httpClient: HttpClient, returnOrderId: string, returnOrderStatusUpdate: ReturnOrderStatusUpdate): (Option[ReturnOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/returns/{return_order_id}/status", $(%returnOrderStatusUpdate))
  constructResult[ReturnOrder](response)

