#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_production_order
import ../models/model_production_order_costing
import ../models/model_production_order_status_update

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createProductionOrder*(httpClient: HttpClient, productionOrder: ProductionOrder): (Option[ProductionOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/production-orders", $(%productionOrder))
  constructResult[ProductionOrder](response)


proc deleteProductionOrder*(httpClient: HttpClient, productionOrderId: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/production-orders/{production_order_id}")



proc getProductionOrder*(httpClient: HttpClient, productionOrderId: stringstring): (Option[ProductionOrder], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/production-orders/{production_order_id}")
  constructResult[ProductionOrder](response)


proc listProductionOrders*(httpClient: HttpClient, page: int, pageSize: int, search: string, status: string): (Option[seq[ProductionOrder]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("pageSize", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $status != "":
    query_params_list.add(("status", $status))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/production-orders/" & "?" & url_encoded_query_params)
  constructResult[seq[ProductionOrder]](response)


proc productionOrderCosting*(httpClient: HttpClient, productionOrderId: stringstring): (Option[ProductionOrderCosting], Response) =
  ## Actual-costing report (Nachkalkulation) — material costs from BOM components at their purchase price plus the resulting per-unit cost and margin against the finished product's sale price.

  let response = httpClient.get(basepath & fmt"/api/v1/production-orders/{production_order_id}/costing")
  constructResult[ProductionOrderCosting](response)


proc updateProductionOrder*(httpClient: HttpClient, productionOrderId: stringstring, productionOrder: ProductionOrder): (Option[ProductionOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/production-orders/{production_order_id}", $(%productionOrder))
  constructResult[ProductionOrder](response)


proc updateProductionOrderStatus*(httpClient: HttpClient, productionOrderId: stringstring, productionOrderStatusUpdate: ProductionOrderStatusUpdate): (Option[ProductionOrder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/production-orders/{production_order_id}/status", $(%productionOrderStatusUpdate))
  constructResult[ProductionOrder](response)

