#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_price_tier
import ../models/model_price_tier_create
import ../models/model_price_tier_update
import ../models/model_resolved_price_response

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createPriceTier*(httpClient: HttpClient, priceTierCreate: PriceTierCreate): (Option[PriceTier], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/price-tiers", $(%priceTierCreate))
  constructResult[PriceTier](response)


proc deletePriceTier*(httpClient: HttpClient, priceTierId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/price-tiers/{price_tier_id}")



proc getPriceTier*(httpClient: HttpClient, priceTierId: string): (Option[PriceTier], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/price-tiers/{price_tier_id}")
  constructResult[PriceTier](response)


proc getResolvedPrice*(httpClient: HttpClient, productId: stringstring, quantity: int64, contactId: string): (Option[ResolvedPriceResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("productId", $productId))
  if $quantity != "":
    query_params_list.add(("quantity", $quantity))
  if $contactId != "":
    query_params_list.add(("contactId", $contactId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/price-tiers/resolved" & "?" & url_encoded_query_params)
  constructResult[ResolvedPriceResponse](response)


proc listPriceTiers*(httpClient: HttpClient, page: int, pageSize: int, productId: stringstring, customerGroupId: string): (Option[seq[PriceTier]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $productId != "":
    query_params_list.add(("product_id", $productId))
  if $customerGroupId != "":
    query_params_list.add(("customer_group_id", $customerGroupId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/price-tiers/" & "?" & url_encoded_query_params)
  constructResult[seq[PriceTier]](response)


proc updatePriceTier*(httpClient: HttpClient, priceTierId: string, priceTierUpdate: PriceTierUpdate): (Option[PriceTier], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/price-tiers/{price_tier_id}", $(%priceTierUpdate))
  constructResult[PriceTier](response)

