#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_plugin_error
import ../models/model_recurring_template

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createRecurringTemplate*(httpClient: HttpClient, body: JsonNode): (Option[RecurringTemplate], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/recurring-templates", $(%body))
  constructResult[RecurringTemplate](response)


proc deleteRecurringTemplate*(httpClient: HttpClient, templateId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/recurring-templates/{template_id}")



proc getRecurringTemplate*(httpClient: HttpClient, templateId: string): (Option[RecurringTemplate], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/recurring-templates/{template_id}")
  constructResult[RecurringTemplate](response)


proc listRecurringTemplates*(httpClient: HttpClient): (Option[seq[RecurringTemplate]], Response) =
  ## 

  let response = httpClient.get(basepath & "/api/v1/recurring-templates/")
  constructResult[seq[RecurringTemplate]](response)

