#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_x_rechnung_response

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc generateXrechnungApi*(httpClient: HttpClient, id: string, supplierName: string, supplierStreet: string, supplierCity: string, supplierZip: string, supplierCountry: string, supplierVatId: string): (Option[XRechnungResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $supplierName != "":
    query_params_list.add(("supplier_name", $supplierName))
  if $supplierStreet != "":
    query_params_list.add(("supplier_street", $supplierStreet))
  if $supplierCity != "":
    query_params_list.add(("supplier_city", $supplierCity))
  if $supplierZip != "":
    query_params_list.add(("supplier_zip", $supplierZip))
  if $supplierCountry != "":
    query_params_list.add(("supplier_country", $supplierCountry))
  if $supplierVatId != "":
    query_params_list.add(("supplier_vat_id", $supplierVatId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/invoices/{id}/xrechnung" & "?" & url_encoded_query_params)
  constructResult[XRechnungResponse](response)

