#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_contact
import ../models/model_contact_timeline_response
import ../models/model_plugin_error
import ../models/model_sales_volume_report

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc contactSchema*(httpClient: HttpClient): (Option[JsonNode], Response) =
  ## Serve JSON Schema for client-side validation

  let response = httpClient.get(basepath & "/api/v1/contacts/schema")
  constructResult[JsonNode](response)


proc contactTimeline*(httpClient: HttpClient, contactId: string): (Option[ContactTimelineResponse], Response) =
  ## Get the full per-contact timeline (Xentral §4.6/4.7).

  let response = httpClient.get(basepath & fmt"/api/v1/contacts/{contact_id}/timeline")
  constructResult[ContactTimelineResponse](response)


proc createContact*(httpClient: HttpClient, body: JsonNode): (Option[Contact], Response) =
  ## Create contact
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/contacts", $(%body))
  constructResult[Contact](response)


proc deleteContact*(httpClient: HttpClient, contactId: string): Response =
  ## Soft-delete contact
  httpClient.delete(basepath & fmt"/api/v1/contacts/{contact_id}")



proc getContact*(httpClient: HttpClient, contactId: string): (Option[Contact], Response) =
  ## Get single contact

  let response = httpClient.get(basepath & fmt"/api/v1/contacts/{contact_id}")
  constructResult[Contact](response)


proc listContacts*(httpClient: HttpClient, page: int, pageSize: int, search: string, contactType: string, tag: string): (Option[seq[Contact]], Response) =
  ## List contacts with search, type filter, and pagination
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $contactType != "":
    query_params_list.add(("contact_type", $contactType))
  if $tag != "":
    query_params_list.add(("tag", $tag))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/contacts" & "?" & url_encoded_query_params)
  constructResult[seq[Contact]](response)


proc salesVolume*(httpClient: HttpClient, page: int, pageSize: int, search: string, contactType: string, tag: string): (Option[SalesVolumeReport], Response) =
  ## Sales volume per contact
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $contactType != "":
    query_params_list.add(("contact_type", $contactType))
  if $tag != "":
    query_params_list.add(("tag", $tag))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/contacts/sales-volume" & "?" & url_encoded_query_params)
  constructResult[SalesVolumeReport](response)


proc updateContact*(httpClient: HttpClient, contactId: string, body: JsonNode): (Option[Contact], Response) =
  ## Update contact
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/contacts/{contact_id}", $(%body))
  constructResult[Contact](response)

