#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_plugin_error
import ../models/model_shareholder
import ../models/model_shareholder_create
import ../models/model_shareholder_update

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createShareholder*(httpClient: HttpClient, shareholderCreate: ShareholderCreate): (Option[Shareholder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/shareholders", $(%shareholderCreate))
  constructResult[Shareholder](response)


proc deleteShareholder*(httpClient: HttpClient, id: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/shareholders/{id}")



proc getShareholder*(httpClient: HttpClient, id: stringstring): (Option[Shareholder], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/shareholders/{id}")
  constructResult[Shareholder](response)


proc getShareholders*(httpClient: HttpClient, page: int, pageSize: int, search: string, includeDeleted: bool): (Option[seq[Shareholder]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $includeDeleted != "":
    query_params_list.add(("include_deleted", $includeDeleted))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/shareholders/" & "?" & url_encoded_query_params)
  constructResult[seq[Shareholder]](response)


proc updateShareholder*(httpClient: HttpClient, id: stringstring, shareholderUpdate: ShareholderUpdate): (Option[Shareholder], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/shareholders/{id}", $(%shareholderUpdate))
  constructResult[Shareholder](response)

