#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_bank_lookup
import ../models/model_hebesatz_lookup

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc bankLookupApi*(httpClient: HttpClient, iban: string): (Option[BankLookup], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("iban", $iban))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/banking/lookup" & "?" & url_encoded_query_params)
  constructResult[BankLookup](response)


proc bankTransactionsApi*(httpClient: HttpClient): Response =
  ## 
  httpClient.get(basepath & "/api/v1/bookkeeping/banking/transactions")



proc hebesatzLookupApi*(httpClient: HttpClient, gemeindeschluessel: string, plz: string, name: string, stichtag: string, countryCode: string): (Option[seq[HebesatzLookup]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $gemeindeschluessel != "":
    query_params_list.add(("gemeindeschluessel", $gemeindeschluessel))
  if $plz != "":
    query_params_list.add(("plz", $plz))
  if $name != "":
    query_params_list.add(("name", $name))
  if $stichtag != "":
    query_params_list.add(("stichtag", $stichtag))
  if $countryCode != "":
    query_params_list.add(("country_code", $countryCode))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/bookkeeping/hebesatz" & "?" & url_encoded_query_params)
  constructResult[seq[HebesatzLookup]](response)

