#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_any_type
import ../models/model_order_confirmation
import ../models/model_plugin_error
import ../models/model_quotation
import ../models/model_quotation_create

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createQuotation*(httpClient: HttpClient, quotationCreate: QuotationCreate): (Option[Quotation], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/quotations", $(%quotationCreate))
  constructResult[Quotation](response)


proc deleteQuotation*(httpClient: HttpClient, quotationId: string): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/quotations/{quotation_id}")



proc downloadQuotationPdf*(httpClient: HttpClient, quotationId: string): Response =
  ## 
  httpClient.get(basepath & fmt"/api/v1/quotations/{quotation_id}/pdf")



proc getQuotation*(httpClient: HttpClient, quotationId: string): (Option[Quotation], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/quotations/{quotation_id}")
  constructResult[Quotation](response)


proc listQuotations*(httpClient: HttpClient, page: int, pageSize: int, search: string, includeDeleted: bool): (Option[seq[Quotation]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  if $search != "":
    query_params_list.add(("search", $search))
  if $includeDeleted != "":
    query_params_list.add(("include_deleted", $includeDeleted))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/quotations/" & "?" & url_encoded_query_params)
  constructResult[seq[Quotation]](response)


proc pursueQuotation*(httpClient: HttpClient, quotationId: string): (Option[OrderConfirmation], Response) =
  ## 

  let response = httpClient.post(basepath & fmt"/api/v1/quotations/{quotation_id}/pursue")
  constructResult[OrderConfirmation](response)


proc quotationRestore*(httpClient: HttpClient, quotationId: string): (Option[Quotation], Response) =
  ## 

  let response = httpClient.post(basepath & fmt"/api/v1/quotations/{quotation_id}/restore")
  constructResult[Quotation](response)


proc updateQuotation*(httpClient: HttpClient, quotationId: string, body: JsonNode): (Option[Quotation], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/quotations/{quotation_id}", $(%body))
  constructResult[Quotation](response)

