#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_accept_invite_request
import ../models/model_auth_response
import ../models/model_forgot_password_request
import ../models/model_login_request
import ../models/model_magic_link_request
import ../models/model_magic_link_verify_request
import ../models/model_register_request
import ../models/model_reset_password_request
import ../models/model_totp_enable_request
import ../models/model_totp_setup_response
import ../models/model_verify_email_request

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc acceptInvite*(httpClient: HttpClient, acceptInviteRequest: AcceptInviteRequest): Response =
  ## Accept an invite: create the account (or reuse an existing one) and join the inviting tenant. The invite token proves control of the mailbox.
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/accept-invite", $(%acceptInviteRequest))



proc forgotPassword*(httpClient: HttpClient, forgotPasswordRequest: ForgotPasswordRequest): Response =
  ## Send a password reset email to the user
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/forgot-password", $(%forgotPasswordRequest))



proc login*(httpClient: HttpClient, loginRequest: LoginRequest): (Option[AuthResponse], Response) =
  ## Authenticate a user with email + password (optional TOTP)
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/auth/login", $(%loginRequest))
  constructResult[AuthResponse](response)


proc logout*(httpClient: HttpClient): Response =
  ## Log out the current user (kills the assay session)
  httpClient.post(basepath & "/auth/logout")



proc magicLinkLogin*(httpClient: HttpClient, magicLinkRequest: MagicLinkRequest): Response =
  ## Request a magic link login (sends an email with a one-time link)
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/magic-link", $(%magicLinkRequest))



proc magicLinkVerify*(httpClient: HttpClient, magicLinkVerifyRequest: MagicLinkVerifyRequest): (Option[AuthResponse], Response) =
  ## Verify a magic link token and log the user in
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/auth/magic-link/verify", $(%magicLinkVerifyRequest))
  constructResult[AuthResponse](response)


proc register*(httpClient: HttpClient, registerRequest: RegisterRequest): (Option[AuthResponse], Response) =
  ## Register a new user account
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/auth/register", $(%registerRequest))
  constructResult[AuthResponse](response)


proc resetPassword*(httpClient: HttpClient, resetPasswordRequest: ResetPasswordRequest): Response =
  ## Reset the user's password using a reset token
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/reset-password", $(%resetPasswordRequest))



proc totpEnable*(httpClient: HttpClient, totpEnableRequest: TotpEnableRequest): Response =
  ## Enable TOTP two-factor authentication by verifying a code
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/totp/enable", $(%totpEnableRequest))



proc totpSetup*(httpClient: HttpClient): (Option[TotpSetupResponse], Response) =
  ## Set up TOTP two-factor authentication (generates secret + backup codes)

  let response = httpClient.get(basepath & "/auth/totp/setup")
  constructResult[TotpSetupResponse](response)


proc verifyEmail*(httpClient: HttpClient, verifyEmailRequest: VerifyEmailRequest): Response =
  ## Verify a user's email address using a verification token
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.post(basepath & "/auth/verify-email", $(%verifyEmailRequest))


