#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_create_ticket_request
import ../models/model_support_ticket
import ../models/model_support_ticket_update

const basepath = "https://demo.simplebilly.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createTicketApi*(httpClient: HttpClient, createTicketRequest: CreateTicketRequest): (Option[SupportTicket], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/api/v1/support/tickets", $(%createTicketRequest))
  constructResult[SupportTicket](response)


proc deleteTicketApi*(httpClient: HttpClient, ticketId: stringstring): Response =
  ## 
  httpClient.delete(basepath & fmt"/api/v1/support/tickets/{ticket_id}")



proc getTicketApi*(httpClient: HttpClient, ticketId: stringstring): (Option[SupportTicket], Response) =
  ## 

  let response = httpClient.get(basepath & fmt"/api/v1/support/tickets/{ticket_id}")
  constructResult[SupportTicket](response)


proc listTicketsApi*(httpClient: HttpClient, status: string, priority: string, assignedTo: stringstring, channelType: string, customerId: string, search: string, page: int, pageSize: int): (Option[seq[SupportTicket]], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  if $status != "":
    query_params_list.add(("status", $status))
  if $priority != "":
    query_params_list.add(("priority", $priority))
  if $assignedTo != "":
    query_params_list.add(("assigned_to", $assignedTo))
  if $channelType != "":
    query_params_list.add(("channel_type", $channelType))
  if $customerId != "":
    query_params_list.add(("customer_id", $customerId))
  if $search != "":
    query_params_list.add(("search", $search))
  if $page != "":
    query_params_list.add(("page", $page))
  if $pageSize != "":
    query_params_list.add(("page_size", $pageSize))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/support/tickets" & "?" & url_encoded_query_params)
  constructResult[seq[SupportTicket]](response)


proc updateTicketApi*(httpClient: HttpClient, ticketId: stringstring, supportTicketUpdate: SupportTicketUpdate): (Option[SupportTicket], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/api/v1/support/tickets/{ticket_id}", $(%supportTicketUpdate))
  constructResult[SupportTicket](response)

