#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_lead_status

type LeadUpdate* = object
  ## 
  company*: Option[string]
  convertedAt*: Option[string]
  createdAt*: Option[string]
  email*: Option[string]
  firstContactAt*: Option[string]
  name*: Option[string]
  notes*: Option[string]
  phone*: Option[string]
  score*: Option[int]
  source*: Option[string]
  status*: Option[LeadStatus]
  tags*: Option[JsonNode]
  tenantId*: Option[string]
  updatedAt*: Option[string]

