#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PayGapInfoResponse* = object
  ## 
  employeeId*: string
  firstName*: string
  gender*: Option[string]
  groupMedianHourly*: Option[float64]
  groupMedianMonthly*: Option[float64]
  groupSize*: int
  jobTitle*: string
  lastName*: string
  overallMedianHourly*: Option[float64]
  ownHourlyGross*: Option[float64]
  ownMonthlyGross*: Option[float64]


# Custom JSON deserialization for PayGapInfoResponse with custom field names
proc to*(node: JsonNode, T: typedesc[PayGapInfoResponse]): PayGapInfoResponse =
  result = PayGapInfoResponse()
  if node.kind == JObject:
    if node.hasKey("employee_id"):
      result.employeeId = to(node["employee_id"], string)
    if node.hasKey("first_name"):
      result.firstName = to(node["first_name"], string)
    if node.hasKey("gender") and node["gender"].kind != JNull:
      result.gender = some(to(node["gender"], typeof(result.gender.get())))
    if node.hasKey("group_median_hourly") and node["group_median_hourly"].kind != JNull:
      result.groupMedianHourly = some(to(node["group_median_hourly"], typeof(result.groupMedianHourly.get())))
    if node.hasKey("group_median_monthly") and node["group_median_monthly"].kind != JNull:
      result.groupMedianMonthly = some(to(node["group_median_monthly"], typeof(result.groupMedianMonthly.get())))
    if node.hasKey("group_size"):
      result.groupSize = to(node["group_size"], int)
    if node.hasKey("job_title"):
      result.jobTitle = to(node["job_title"], string)
    if node.hasKey("last_name"):
      result.lastName = to(node["last_name"], string)
    if node.hasKey("overall_median_hourly") and node["overall_median_hourly"].kind != JNull:
      result.overallMedianHourly = some(to(node["overall_median_hourly"], typeof(result.overallMedianHourly.get())))
    if node.hasKey("own_hourly_gross") and node["own_hourly_gross"].kind != JNull:
      result.ownHourlyGross = some(to(node["own_hourly_gross"], typeof(result.ownHourlyGross.get())))
    if node.hasKey("own_monthly_gross") and node["own_monthly_gross"].kind != JNull:
      result.ownMonthlyGross = some(to(node["own_monthly_gross"], typeof(result.ownMonthlyGross.get())))

# Custom JSON serialization for PayGapInfoResponse with custom field names
proc `%`*(obj: PayGapInfoResponse): JsonNode =
  result = newJObject()
  result["employee_id"] = %obj.employeeId
  result["first_name"] = %obj.firstName
  if obj.gender.isSome():
    result["gender"] = %obj.gender.get()
  if obj.groupMedianHourly.isSome():
    result["group_median_hourly"] = %obj.groupMedianHourly.get()
  if obj.groupMedianMonthly.isSome():
    result["group_median_monthly"] = %obj.groupMedianMonthly.get()
  result["group_size"] = %obj.groupSize
  result["job_title"] = %obj.jobTitle
  result["last_name"] = %obj.lastName
  if obj.overallMedianHourly.isSome():
    result["overall_median_hourly"] = %obj.overallMedianHourly.get()
  if obj.ownHourlyGross.isSome():
    result["own_hourly_gross"] = %obj.ownHourlyGross.get()
  if obj.ownMonthlyGross.isSome():
    result["own_monthly_gross"] = %obj.ownMonthlyGross.get()

