#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AllocatePaymentRequest* = object
  ## 
  amount*: float64
  invoiceId*: string
  paymentId*: string


# Custom JSON deserialization for AllocatePaymentRequest with custom field names
proc to*(node: JsonNode, T: typedesc[AllocatePaymentRequest]): AllocatePaymentRequest =
  result = AllocatePaymentRequest()
  if node.kind == JObject:
    if node.hasKey("amount"):
      result.amount = to(node["amount"], float64)
    if node.hasKey("invoice_id"):
      result.invoiceId = to(node["invoice_id"], string)
    if node.hasKey("payment_id"):
      result.paymentId = to(node["payment_id"], string)

# Custom JSON serialization for AllocatePaymentRequest with custom field names
proc `%`*(obj: AllocatePaymentRequest): JsonNode =
  result = newJObject()
  result["amount"] = %obj.amount
  result["invoice_id"] = %obj.invoiceId
  result["payment_id"] = %obj.paymentId

