#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_anlage_s_kfz_hinweis

type AnlageSErgebnis* = object
  ## 
  gewinnVerlust*: string
  jahr*: int
  kfzHinweise*: seq[AnlageSKfzHinweis]


# Custom JSON deserialization for AnlageSErgebnis with custom field names
proc to*(node: JsonNode, T: typedesc[AnlageSErgebnis]): AnlageSErgebnis =
  result = AnlageSErgebnis()
  if node.kind == JObject:
    if node.hasKey("gewinn_verlust"):
      result.gewinnVerlust = to(node["gewinn_verlust"], string)
    if node.hasKey("jahr"):
      result.jahr = to(node["jahr"], int)
    if node.hasKey("kfz_hinweise"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["kfz_hinweise"]
      if arrayNode.kind == JArray:
        result.kfzHinweise = @[]
        for item in arrayNode.items:
          result.kfzHinweise.add(to(item, AnlageSKfzHinweis))

# Custom JSON serialization for AnlageSErgebnis with custom field names
proc `%`*(obj: AnlageSErgebnis): JsonNode =
  result = newJObject()
  result["gewinn_verlust"] = %obj.gewinnVerlust
  result["jahr"] = %obj.jahr
  result["kfz_hinweise"] = %obj.kfzHinweise

