#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SalesVolumeItem* = object
  ## 
  contactId*: string
  contactType*: string
  lastPurchaseDate*: Option[string]
  name*: string
  totalInvoices*: int
  totalRevenue*: string


# Custom JSON deserialization for SalesVolumeItem with custom field names
proc to*(node: JsonNode, T: typedesc[SalesVolumeItem]): SalesVolumeItem =
  result = SalesVolumeItem()
  if node.kind == JObject:
    if node.hasKey("contact_id"):
      result.contactId = to(node["contact_id"], string)
    if node.hasKey("contact_type"):
      result.contactType = to(node["contact_type"], string)
    if node.hasKey("last_purchase_date") and node["last_purchase_date"].kind != JNull:
      result.lastPurchaseDate = some(to(node["last_purchase_date"], typeof(result.lastPurchaseDate.get())))
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("total_invoices"):
      result.totalInvoices = to(node["total_invoices"], int)
    if node.hasKey("total_revenue"):
      result.totalRevenue = to(node["total_revenue"], string)

# Custom JSON serialization for SalesVolumeItem with custom field names
proc `%`*(obj: SalesVolumeItem): JsonNode =
  result = newJObject()
  result["contact_id"] = %obj.contactId
  result["contact_type"] = %obj.contactType
  if obj.lastPurchaseDate.isSome():
    result["last_purchase_date"] = %obj.lastPurchaseDate.get()
  result["name"] = %obj.name
  result["total_invoices"] = %obj.totalInvoices
  result["total_revenue"] = %obj.totalRevenue

