#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type Gender* {.pure.} = enum
  Male
  Female
  Diverse

func `%`*(v: Gender): JsonNode =
  result = case v:
    of Gender.Male: %"male"
    of Gender.Female: %"female"
    of Gender.Diverse: %"diverse"

func `$`*(v: Gender): string =
  result = case v:
    of Gender.Male: $("male")
    of Gender.Female: $("female")
    of Gender.Diverse: $("diverse")

proc to*(node: JsonNode, T: typedesc[Gender]): Gender =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum Gender, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("male"):
    return Gender.Male
  of $("female"):
    return Gender.Female
  of $("diverse"):
    return Gender.Diverse
  else:
    raise newException(ValueError, "Invalid enum value for Gender: " & strVal)

