#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type OrderStatus* {.pure.} = enum
  Pending
  Ordered
  Confirmed
  Processing
  Paid
  Shipped
  Completed
  Closed
  Cancelled
  Refunded
  Failed

func `%`*(v: OrderStatus): JsonNode =
  result = case v:
    of OrderStatus.Pending: %"pending"
    of OrderStatus.Ordered: %"ordered"
    of OrderStatus.Confirmed: %"confirmed"
    of OrderStatus.Processing: %"processing"
    of OrderStatus.Paid: %"paid"
    of OrderStatus.Shipped: %"shipped"
    of OrderStatus.Completed: %"completed"
    of OrderStatus.Closed: %"closed"
    of OrderStatus.Cancelled: %"cancelled"
    of OrderStatus.Refunded: %"refunded"
    of OrderStatus.Failed: %"failed"

func `$`*(v: OrderStatus): string =
  result = case v:
    of OrderStatus.Pending: $("pending")
    of OrderStatus.Ordered: $("ordered")
    of OrderStatus.Confirmed: $("confirmed")
    of OrderStatus.Processing: $("processing")
    of OrderStatus.Paid: $("paid")
    of OrderStatus.Shipped: $("shipped")
    of OrderStatus.Completed: $("completed")
    of OrderStatus.Closed: $("closed")
    of OrderStatus.Cancelled: $("cancelled")
    of OrderStatus.Refunded: $("refunded")
    of OrderStatus.Failed: $("failed")

proc to*(node: JsonNode, T: typedesc[OrderStatus]): OrderStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum OrderStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("pending"):
    return OrderStatus.Pending
  of $("ordered"):
    return OrderStatus.Ordered
  of $("confirmed"):
    return OrderStatus.Confirmed
  of $("processing"):
    return OrderStatus.Processing
  of $("paid"):
    return OrderStatus.Paid
  of $("shipped"):
    return OrderStatus.Shipped
  of $("completed"):
    return OrderStatus.Completed
  of $("closed"):
    return OrderStatus.Closed
  of $("cancelled"):
    return OrderStatus.Cancelled
  of $("refunded"):
    return OrderStatus.Refunded
  of $("failed"):
    return OrderStatus.Failed
  else:
    raise newException(ValueError, "Invalid enum value for OrderStatus: " & strVal)

