#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type ProductVariant* = object
  ## 
  barcode*: Option[string]
  imageLink*: Option[string]
  isActive*: Option[bool]
  name*: Option[string] ## Human-readable variant label, e.g. \"Red / M\".
  optionValues*: Option[JsonNode] ## Option name → value map, e.g. `{\"Color\": \"Red\", \"Size\": \"M\"}`.
  price*: Option[string] ## Explicit override price for this variant (takes precedence over parent price + delta).
  priceDelta*: Option[string] ## Price adjustment relative to the parent product's `default_price`.
  productId*: string ## The parent product this variant belongs to. References the product entity.
  sku*: string ## Variant-specific SKU (must be unique per tenant).
  stockQuantity*: Option[int64] ## Variant-level stock (optional — may be tracked on the parent only).

