#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ProviderInfo* = object
  ## 
  displayName*: string
  name*: string
  requiresApiKey*: bool
  services*: seq[string]
  supportsLabelCreation*: bool
  supportsRateEstimation*: bool
  supportsTracking*: bool


# Custom JSON deserialization for ProviderInfo with custom field names
proc to*(node: JsonNode, T: typedesc[ProviderInfo]): ProviderInfo =
  result = ProviderInfo()
  if node.kind == JObject:
    if node.hasKey("display_name"):
      result.displayName = to(node["display_name"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("requires_api_key"):
      result.requiresApiKey = to(node["requires_api_key"], bool)
    if node.hasKey("services"):
      result.services = to(node["services"], seq[string])
    if node.hasKey("supports_label_creation"):
      result.supportsLabelCreation = to(node["supports_label_creation"], bool)
    if node.hasKey("supports_rate_estimation"):
      result.supportsRateEstimation = to(node["supports_rate_estimation"], bool)
    if node.hasKey("supports_tracking"):
      result.supportsTracking = to(node["supports_tracking"], bool)

# Custom JSON serialization for ProviderInfo with custom field names
proc `%`*(obj: ProviderInfo): JsonNode =
  result = newJObject()
  result["display_name"] = %obj.displayName
  result["name"] = %obj.name
  result["requires_api_key"] = %obj.requiresApiKey
  result["services"] = %obj.services
  result["supports_label_creation"] = %obj.supportsLabelCreation
  result["supports_rate_estimation"] = %obj.supportsRateEstimation
  result["supports_tracking"] = %obj.supportsTracking

