#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PaymentMethod* {.pure.} = enum
  BankTransfer
  SepaDirectDebit
  Cash
  CreditCard
  Paypal
  Sumup
  VivaWallet
  Reepay
  None

func `%`*(v: PaymentMethod): JsonNode =
  result = case v:
    of PaymentMethod.BankTransfer: %"bank_transfer"
    of PaymentMethod.SepaDirectDebit: %"sepa_direct_debit"
    of PaymentMethod.Cash: %"cash"
    of PaymentMethod.CreditCard: %"credit_card"
    of PaymentMethod.Paypal: %"paypal"
    of PaymentMethod.Sumup: %"sumup"
    of PaymentMethod.VivaWallet: %"viva_wallet"
    of PaymentMethod.Reepay: %"reepay"
    of PaymentMethod.None: %"none"

func `$`*(v: PaymentMethod): string =
  result = case v:
    of PaymentMethod.BankTransfer: $("bank_transfer")
    of PaymentMethod.SepaDirectDebit: $("sepa_direct_debit")
    of PaymentMethod.Cash: $("cash")
    of PaymentMethod.CreditCard: $("credit_card")
    of PaymentMethod.Paypal: $("paypal")
    of PaymentMethod.Sumup: $("sumup")
    of PaymentMethod.VivaWallet: $("viva_wallet")
    of PaymentMethod.Reepay: $("reepay")
    of PaymentMethod.None: $("none")

proc to*(node: JsonNode, T: typedesc[PaymentMethod]): PaymentMethod =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum PaymentMethod, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("bank_transfer"):
    return PaymentMethod.BankTransfer
  of $("sepa_direct_debit"):
    return PaymentMethod.SepaDirectDebit
  of $("cash"):
    return PaymentMethod.Cash
  of $("credit_card"):
    return PaymentMethod.CreditCard
  of $("paypal"):
    return PaymentMethod.Paypal
  of $("sumup"):
    return PaymentMethod.Sumup
  of $("viva_wallet"):
    return PaymentMethod.VivaWallet
  of $("reepay"):
    return PaymentMethod.Reepay
  of $("none"):
    return PaymentMethod.None
  else:
    raise newException(ValueError, "Invalid enum value for PaymentMethod: " & strVal)

