#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_tracked_shipment

type TrackOrderResponse* = object
  ## 
  orderNumber*: string
  orderStatus*: string
  shipments*: seq[TrackedShipment]


# Custom JSON deserialization for TrackOrderResponse with custom field names
proc to*(node: JsonNode, T: typedesc[TrackOrderResponse]): TrackOrderResponse =
  result = TrackOrderResponse()
  if node.kind == JObject:
    if node.hasKey("order_number"):
      result.orderNumber = to(node["order_number"], string)
    if node.hasKey("order_status"):
      result.orderStatus = to(node["order_status"], string)
    if node.hasKey("shipments"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["shipments"]
      if arrayNode.kind == JArray:
        result.shipments = @[]
        for item in arrayNode.items:
          result.shipments.add(to(item, TrackedShipment))

# Custom JSON serialization for TrackOrderResponse with custom field names
proc `%`*(obj: TrackOrderResponse): JsonNode =
  result = newJObject()
  result["order_number"] = %obj.orderNumber
  result["order_status"] = %obj.orderStatus
  result["shipments"] = %obj.shipments

