#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_movement_type
import model_reference_type

type StockMovement* = object
  ## 
  delta*: int64 ## Signed movement: positive = into stock, negative = out of stock.
  movementType*: MovementType ## One of the `MOVEMENT_*` constants.
  productId*: string ## References the product entity.
  quantity*: int64 ## Absolute quantity moved (always >= 0).
  reason*: Option[string]
  referenceId*: Option[string] ## Primary-key of the referencing entity.
  referenceType*: Option[ReferenceType] ## Entity that caused the movement, e.g. `goods_receipt`, `stock_transfer`.
  warehouseId*: string ## References the warehouse entity.

