#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_tracking_event

type TrackedShipment* = object
  ## 
  carrier*: string
  events*: seq[TrackingEvent]
  labelUrl*: Option[string]
  status*: string
  trackingNumber*: Option[string]
  trackingUrl*: Option[string]


# Custom JSON deserialization for TrackedShipment with custom field names
proc to*(node: JsonNode, T: typedesc[TrackedShipment]): TrackedShipment =
  result = TrackedShipment()
  if node.kind == JObject:
    if node.hasKey("carrier"):
      result.carrier = to(node["carrier"], string)
    if node.hasKey("events"):
      result.events = to(node["events"], seq[TrackingEvent])
    if node.hasKey("label_url") and node["label_url"].kind != JNull:
      result.labelUrl = some(to(node["label_url"], typeof(result.labelUrl.get())))
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("tracking_number") and node["tracking_number"].kind != JNull:
      result.trackingNumber = some(to(node["tracking_number"], typeof(result.trackingNumber.get())))
    if node.hasKey("tracking_url") and node["tracking_url"].kind != JNull:
      result.trackingUrl = some(to(node["tracking_url"], typeof(result.trackingUrl.get())))

# Custom JSON serialization for TrackedShipment with custom field names
proc `%`*(obj: TrackedShipment): JsonNode =
  result = newJObject()
  result["carrier"] = %obj.carrier
  result["events"] = %obj.events
  if obj.labelUrl.isSome():
    result["label_url"] = %obj.labelUrl.get()
  result["status"] = %obj.status
  if obj.trackingNumber.isSome():
    result["tracking_number"] = %obj.trackingNumber.get()
  if obj.trackingUrl.isSome():
    result["tracking_url"] = %obj.trackingUrl.get()

