#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_balance_item

type BalanceSheet* = object
  ## 
  assets*: seq[BalanceItem]
  balanced*: bool
  equityLiabilities*: seq[BalanceItem]
  totalAssets*: string
  totalEquityLiabilities*: string


# Custom JSON deserialization for BalanceSheet with custom field names
proc to*(node: JsonNode, T: typedesc[BalanceSheet]): BalanceSheet =
  result = BalanceSheet()
  if node.kind == JObject:
    if node.hasKey("assets"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["assets"]
      if arrayNode.kind == JArray:
        result.assets = @[]
        for item in arrayNode.items:
          result.assets.add(to(item, BalanceItem))
    if node.hasKey("balanced"):
      result.balanced = to(node["balanced"], bool)
    if node.hasKey("equity_liabilities"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["equity_liabilities"]
      if arrayNode.kind == JArray:
        result.equityLiabilities = @[]
        for item in arrayNode.items:
          result.equityLiabilities.add(to(item, BalanceItem))
    if node.hasKey("total_assets"):
      result.totalAssets = to(node["total_assets"], string)
    if node.hasKey("total_equity_liabilities"):
      result.totalEquityLiabilities = to(node["total_equity_liabilities"], string)

# Custom JSON serialization for BalanceSheet with custom field names
proc `%`*(obj: BalanceSheet): JsonNode =
  result = newJObject()
  result["assets"] = %obj.assets
  result["balanced"] = %obj.balanced
  result["equity_liabilities"] = %obj.equityLiabilities
  result["total_assets"] = %obj.totalAssets
  result["total_equity_liabilities"] = %obj.totalEquityLiabilities

