#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type UpdateSubscriptionRequest* = object
  ## 
  eventType*: Option[string]
  isActive*: Option[bool]
  name*: Option[string]
  secret*: Option[string]
  url*: Option[string]


# Custom JSON deserialization for UpdateSubscriptionRequest with custom field names
proc to*(node: JsonNode, T: typedesc[UpdateSubscriptionRequest]): UpdateSubscriptionRequest =
  result = UpdateSubscriptionRequest()
  if node.kind == JObject:
    if node.hasKey("event_type") and node["event_type"].kind != JNull:
      result.eventType = some(to(node["event_type"], typeof(result.eventType.get())))
    if node.hasKey("is_active") and node["is_active"].kind != JNull:
      result.isActive = some(to(node["is_active"], typeof(result.isActive.get())))
    if node.hasKey("name") and node["name"].kind != JNull:
      result.name = some(to(node["name"], typeof(result.name.get())))
    if node.hasKey("secret") and node["secret"].kind != JNull:
      result.secret = some(to(node["secret"], typeof(result.secret.get())))
    if node.hasKey("url") and node["url"].kind != JNull:
      result.url = some(to(node["url"], typeof(result.url.get())))

# Custom JSON serialization for UpdateSubscriptionRequest with custom field names
proc `%`*(obj: UpdateSubscriptionRequest): JsonNode =
  result = newJObject()
  if obj.eventType.isSome():
    result["event_type"] = %obj.eventType.get()
  if obj.isActive.isSome():
    result["is_active"] = %obj.isActive.get()
  if obj.name.isSome():
    result["name"] = %obj.name.get()
  if obj.secret.isSome():
    result["secret"] = %obj.secret.get()
  if obj.url.isSome():
    result["url"] = %obj.url.get()

