#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AcceptInviteRequest* = object
  ## 
  firstName*: string
  lastName*: string
  password*: string
  privacyAccepted*: bool ## GDPR consent — rejected unless true.
  token*: string


# Custom JSON deserialization for AcceptInviteRequest with custom field names
proc to*(node: JsonNode, T: typedesc[AcceptInviteRequest]): AcceptInviteRequest =
  result = AcceptInviteRequest()
  if node.kind == JObject:
    if node.hasKey("first_name"):
      result.firstName = to(node["first_name"], string)
    if node.hasKey("last_name"):
      result.lastName = to(node["last_name"], string)
    if node.hasKey("password"):
      result.password = to(node["password"], string)
    if node.hasKey("privacy_accepted"):
      result.privacyAccepted = to(node["privacy_accepted"], bool)
    if node.hasKey("token"):
      result.token = to(node["token"], string)

# Custom JSON serialization for AcceptInviteRequest with custom field names
proc `%`*(obj: AcceptInviteRequest): JsonNode =
  result = newJObject()
  result["first_name"] = %obj.firstName
  result["last_name"] = %obj.lastName
  result["password"] = %obj.password
  result["privacy_accepted"] = %obj.privacyAccepted
  result["token"] = %obj.token

