#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AiConfigDto* = object
  ## 
  autoReply*: Option[bool]
  maxToolCalls*: Option[int]
  model*: string
  name*: string
  provider*: string
  systemPrompt*: Option[string]
  triggerOn*: Option[seq[string]]


# Custom JSON deserialization for AiConfigDto with custom field names
proc to*(node: JsonNode, T: typedesc[AiConfigDto]): AiConfigDto =
  result = AiConfigDto()
  if node.kind == JObject:
    if node.hasKey("auto_reply") and node["auto_reply"].kind != JNull:
      result.autoReply = some(to(node["auto_reply"], typeof(result.autoReply.get())))
    if node.hasKey("max_tool_calls") and node["max_tool_calls"].kind != JNull:
      result.maxToolCalls = some(to(node["max_tool_calls"], typeof(result.maxToolCalls.get())))
    if node.hasKey("model"):
      result.model = to(node["model"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("provider"):
      result.provider = to(node["provider"], string)
    if node.hasKey("system_prompt") and node["system_prompt"].kind != JNull:
      result.systemPrompt = some(to(node["system_prompt"], typeof(result.systemPrompt.get())))
    if node.hasKey("trigger_on") and node["trigger_on"].kind != JNull:
      result.triggerOn = some(to(node["trigger_on"], typeof(result.triggerOn.get())))

# Custom JSON serialization for AiConfigDto with custom field names
proc `%`*(obj: AiConfigDto): JsonNode =
  result = newJObject()
  if obj.autoReply.isSome():
    result["auto_reply"] = %obj.autoReply.get()
  if obj.maxToolCalls.isSome():
    result["max_tool_calls"] = %obj.maxToolCalls.get()
  result["model"] = %obj.model
  result["name"] = %obj.name
  result["provider"] = %obj.provider
  if obj.systemPrompt.isSome():
    result["system_prompt"] = %obj.systemPrompt.get()
  if obj.triggerOn.isSome():
    result["trigger_on"] = %obj.triggerOn.get()

