#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type UpdateConnectionRequest* = object
  ## 
  apiKey*: Option[string]
  apiSecret*: Option[string]
  config*: Option[JsonNode]
  isActive*: Option[bool]
  label*: Option[string]
  shopDomain*: Option[string]


# Custom JSON deserialization for UpdateConnectionRequest with custom field names
proc to*(node: JsonNode, T: typedesc[UpdateConnectionRequest]): UpdateConnectionRequest =
  result = UpdateConnectionRequest()
  if node.kind == JObject:
    if node.hasKey("api_key") and node["api_key"].kind != JNull:
      result.apiKey = some(to(node["api_key"], typeof(result.apiKey.get())))
    if node.hasKey("api_secret") and node["api_secret"].kind != JNull:
      result.apiSecret = some(to(node["api_secret"], typeof(result.apiSecret.get())))
    if node.hasKey("config") and node["config"].kind != JNull:
      result.config = some(to(node["config"], typeof(result.config.get())))
    if node.hasKey("is_active") and node["is_active"].kind != JNull:
      result.isActive = some(to(node["is_active"], typeof(result.isActive.get())))
    if node.hasKey("label") and node["label"].kind != JNull:
      result.label = some(to(node["label"], typeof(result.label.get())))
    if node.hasKey("shop_domain") and node["shop_domain"].kind != JNull:
      result.shopDomain = some(to(node["shop_domain"], typeof(result.shopDomain.get())))

# Custom JSON serialization for UpdateConnectionRequest with custom field names
proc `%`*(obj: UpdateConnectionRequest): JsonNode =
  result = newJObject()
  if obj.apiKey.isSome():
    result["api_key"] = %obj.apiKey.get()
  if obj.apiSecret.isSome():
    result["api_secret"] = %obj.apiSecret.get()
  if obj.config.isSome():
    result["config"] = %obj.config.get()
  if obj.isActive.isSome():
    result["is_active"] = %obj.isActive.get()
  if obj.label.isSome():
    result["label"] = %obj.label.get()
  if obj.shopDomain.isSome():
    result["shop_domain"] = %obj.shopDomain.get()

