#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_euer_zeile_detail

type EuerDetailErgebnis* = object
  ## 
  jahr*: int
  zeilen*: seq[EuerZeileDetail]


# Custom JSON deserialization for EuerDetailErgebnis with custom field names
proc to*(node: JsonNode, T: typedesc[EuerDetailErgebnis]): EuerDetailErgebnis =
  result = EuerDetailErgebnis()
  if node.kind == JObject:
    if node.hasKey("jahr"):
      result.jahr = to(node["jahr"], int)
    if node.hasKey("zeilen"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["zeilen"]
      if arrayNode.kind == JArray:
        result.zeilen = @[]
        for item in arrayNode.items:
          result.zeilen.add(to(item, EuerZeileDetail))

# Custom JSON serialization for EuerDetailErgebnis with custom field names
proc `%`*(obj: EuerDetailErgebnis): JsonNode =
  result = newJObject()
  result["jahr"] = %obj.jahr
  result["zeilen"] = %obj.zeilen

