#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SepaDirectDebitResponse* = object
  ## 
  contentType*: string
  filename*: string
  xmlContent*: string


# Custom JSON deserialization for SepaDirectDebitResponse with custom field names
proc to*(node: JsonNode, T: typedesc[SepaDirectDebitResponse]): SepaDirectDebitResponse =
  result = SepaDirectDebitResponse()
  if node.kind == JObject:
    if node.hasKey("content_type"):
      result.contentType = to(node["content_type"], string)
    if node.hasKey("filename"):
      result.filename = to(node["filename"], string)
    if node.hasKey("xml_content"):
      result.xmlContent = to(node["xml_content"], string)

# Custom JSON serialization for SepaDirectDebitResponse with custom field names
proc `%`*(obj: SepaDirectDebitResponse): JsonNode =
  result = newJObject()
  result["content_type"] = %obj.contentType
  result["filename"] = %obj.filename
  result["xml_content"] = %obj.xmlContent

