#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CreateEmissionTarget* = object
  ## 
  baseValue*: string
  baseYear*: int
  description*: string
  scope*: string
  targetValue*: string
  targetYear*: int


# Custom JSON deserialization for CreateEmissionTarget with custom field names
proc to*(node: JsonNode, T: typedesc[CreateEmissionTarget]): CreateEmissionTarget =
  result = CreateEmissionTarget()
  if node.kind == JObject:
    if node.hasKey("base_value"):
      result.baseValue = to(node["base_value"], string)
    if node.hasKey("base_year"):
      result.baseYear = to(node["base_year"], int)
    if node.hasKey("description"):
      result.description = to(node["description"], string)
    if node.hasKey("scope"):
      result.scope = to(node["scope"], string)
    if node.hasKey("target_value"):
      result.targetValue = to(node["target_value"], string)
    if node.hasKey("target_year"):
      result.targetYear = to(node["target_year"], int)

# Custom JSON serialization for CreateEmissionTarget with custom field names
proc `%`*(obj: CreateEmissionTarget): JsonNode =
  result = newJObject()
  result["base_value"] = %obj.baseValue
  result["base_year"] = %obj.baseYear
  result["description"] = %obj.description
  result["scope"] = %obj.scope
  result["target_value"] = %obj.targetValue
  result["target_year"] = %obj.targetYear

