#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type FeatureSettings* = object
  ## Feature toggles for a tenant.
  onlineshop*: bool ## Online shop / storefront module (default: enabled).
  reportBilanz*: bool ## Bilanz (balance sheet) report.
  reportBwa*: bool ## BWA (betriebswirtschaftliche Auswertung).
  reportEuer*: bool ## EÜR (Einnahmen-Überschuss-Rechnung).
  reportGewerbesteuer*: bool ## Gewerbesteuer report.
  reportGuv*: bool ## GuV (profit & loss) report.
  reportKst*: bool ## KSt (Körperschaftsteuer) report.
  reportUstva*: bool ## UStVA (Umsatzsteuervoranmeldung).

