#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ReferenceType* {.pure.} = enum
  GoodsReceipt
  ProductionOrder
  TransferIn
  StockTransfer
  ReturnOrder
  InventoryCount

func `%`*(v: ReferenceType): JsonNode =
  result = case v:
    of ReferenceType.GoodsReceipt: %"goods_receipt"
    of ReferenceType.ProductionOrder: %"production_order"
    of ReferenceType.TransferIn: %"transfer_in"
    of ReferenceType.StockTransfer: %"stock_transfer"
    of ReferenceType.ReturnOrder: %"return_order"
    of ReferenceType.InventoryCount: %"inventory_count"

func `$`*(v: ReferenceType): string =
  result = case v:
    of ReferenceType.GoodsReceipt: $("goods_receipt")
    of ReferenceType.ProductionOrder: $("production_order")
    of ReferenceType.TransferIn: $("transfer_in")
    of ReferenceType.StockTransfer: $("stock_transfer")
    of ReferenceType.ReturnOrder: $("return_order")
    of ReferenceType.InventoryCount: $("inventory_count")

proc to*(node: JsonNode, T: typedesc[ReferenceType]): ReferenceType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ReferenceType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("goods_receipt"):
    return ReferenceType.GoodsReceipt
  of $("production_order"):
    return ReferenceType.ProductionOrder
  of $("transfer_in"):
    return ReferenceType.TransferIn
  of $("stock_transfer"):
    return ReferenceType.StockTransfer
  of $("return_order"):
    return ReferenceType.ReturnOrder
  of $("inventory_count"):
    return ReferenceType.InventoryCount
  else:
    raise newException(ValueError, "Invalid enum value for ReferenceType: " & strVal)

