#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_language_code
import model_order_status
import model_payment_method

type OrderUpdate* = object
  ## 
  auditLog*: Option[JsonNode]
  currency*: Option[string]
  customerId*: Option[string] ## References the customer entity.
  externalReference*: Option[string]
  invoiceAddress*: Option[JsonNode]
  items*: Option[JsonNode]
  language*: Option[LanguageCode]
  orderStatus*: Option[OrderStatus]
  paymentMethod*: Option[PaymentMethod]
  shippingAddress*: Option[JsonNode]
  shippingCost*: Option[string]
  shippingMethod*: Option[string]
  shippingWeight*: Option[string]
  tags*: Option[seq[string]]
  totalCost*: Option[string]

