#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ExtraPayment* = object
  ## 
  amount*: string
  employeeId*: string
  reason*: Option[string]


# Custom JSON deserialization for ExtraPayment with custom field names
proc to*(node: JsonNode, T: typedesc[ExtraPayment]): ExtraPayment =
  result = ExtraPayment()
  if node.kind == JObject:
    if node.hasKey("amount"):
      result.amount = to(node["amount"], string)
    if node.hasKey("employee_id"):
      result.employeeId = to(node["employee_id"], string)
    if node.hasKey("reason") and node["reason"].kind != JNull:
      result.reason = some(to(node["reason"], typeof(result.reason.get())))

# Custom JSON serialization for ExtraPayment with custom field names
proc `%`*(obj: ExtraPayment): JsonNode =
  result = newJObject()
  result["amount"] = %obj.amount
  result["employee_id"] = %obj.employeeId
  if obj.reason.isSome():
    result["reason"] = %obj.reason.get()

