#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_country_code

type ShippingRuleUpdate* = object
  ## 
  carrier*: Option[string] ## Provider that auto-filled this rule (e.g. \"ups\"), if any.
  country*: Option[CountryCode] ## None = applies to all countries.
  deliveryTime*: Option[string] ## Delivery time text, e.g. \"1-3\".
  isActive*: Option[bool]
  maxWeightKg*: Option[float64]
  minWeightKg*: Option[float64]
  name*: Option[string] ## Delivery-method label, e.g. \"Standardversand\".
  notes*: Option[string]
  price*: Option[string] ## Shipping cost in the shop's currency.
  priority*: Option[int] ## Lower wins when multiple rules match.

