#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type EmitEventRequest* = object
  ## 
  eventType*: string
  payload*: Option[JsonNode]


# Custom JSON deserialization for EmitEventRequest with custom field names
proc to*(node: JsonNode, T: typedesc[EmitEventRequest]): EmitEventRequest =
  result = EmitEventRequest()
  if node.kind == JObject:
    if node.hasKey("event_type"):
      result.eventType = to(node["event_type"], string)
    if node.hasKey("payload") and node["payload"].kind != JNull:
      result.payload = some(to(node["payload"], typeof(result.payload.get())))

# Custom JSON serialization for EmitEventRequest with custom field names
proc `%`*(obj: EmitEventRequest): JsonNode =
  result = newJObject()
  result["event_type"] = %obj.eventType
  if obj.payload.isSome():
    result["payload"] = %obj.payload.get()

