#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type BoxFit* = object
  ## 
  heightCm*: float64
  itemCount*: int
  lengthCm*: float64
  volumeCm3*: float64
  widthCm*: float64


# Custom JSON deserialization for BoxFit with custom field names
proc to*(node: JsonNode, T: typedesc[BoxFit]): BoxFit =
  result = BoxFit()
  if node.kind == JObject:
    if node.hasKey("height_cm"):
      result.heightCm = to(node["height_cm"], float64)
    if node.hasKey("item_count"):
      result.itemCount = to(node["item_count"], int)
    if node.hasKey("length_cm"):
      result.lengthCm = to(node["length_cm"], float64)
    if node.hasKey("volume_cm3"):
      result.volumeCm3 = to(node["volume_cm3"], float64)
    if node.hasKey("width_cm"):
      result.widthCm = to(node["width_cm"], float64)

# Custom JSON serialization for BoxFit with custom field names
proc `%`*(obj: BoxFit): JsonNode =
  result = newJObject()
  result["height_cm"] = %obj.heightCm
  result["item_count"] = %obj.itemCount
  result["length_cm"] = %obj.lengthCm
  result["volume_cm3"] = %obj.volumeCm3
  result["width_cm"] = %obj.widthCm

