#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ProductAttributeCreate* = object
  ## 
  isFilterable*: Option[bool] ## Whether this attribute participates in the shop's faceted filters.
  name*: string ## Attribute name, e.g. `Material`, `Farbe`, `Gewicht`.
  position*: Option[int] ## Ordering position within the product's attribute list.
  productId*: string ## The product this attribute belongs to. References the product entity.
  unit*: Option[string] ## Optional unit of measure for numeric attributes, e.g. `g`, `cm`.
  value*: string ## Attribute value, e.g. `Baumwolle`, `Rot`, `180g`.

