#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type KonzernThresholds* = object
  ## 
  bilanzsumme*: string
  mitarbeiter*: int64
  nettoUmsatz*: string


# Custom JSON deserialization for KonzernThresholds with custom field names
proc to*(node: JsonNode, T: typedesc[KonzernThresholds]): KonzernThresholds =
  result = KonzernThresholds()
  if node.kind == JObject:
    if node.hasKey("bilanzsumme"):
      result.bilanzsumme = to(node["bilanzsumme"], string)
    if node.hasKey("mitarbeiter"):
      result.mitarbeiter = to(node["mitarbeiter"], int64)
    if node.hasKey("netto_umsatz"):
      result.nettoUmsatz = to(node["netto_umsatz"], string)

# Custom JSON serialization for KonzernThresholds with custom field names
proc `%`*(obj: KonzernThresholds): JsonNode =
  result = newJObject()
  result["bilanzsumme"] = %obj.bilanzsumme
  result["mitarbeiter"] = %obj.mitarbeiter
  result["netto_umsatz"] = %obj.nettoUmsatz

