#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type EventSubscription* = object
  ## 
  callbackUrl*: string
  eventType*: string
  isActive*: bool
  subscriptionId*: string


# Custom JSON deserialization for EventSubscription with custom field names
proc to*(node: JsonNode, T: typedesc[EventSubscription]): EventSubscription =
  result = EventSubscription()
  if node.kind == JObject:
    if node.hasKey("callback_url"):
      result.callbackUrl = to(node["callback_url"], string)
    if node.hasKey("event_type"):
      result.eventType = to(node["event_type"], string)
    if node.hasKey("is_active"):
      result.isActive = to(node["is_active"], bool)
    if node.hasKey("subscription_id"):
      result.subscriptionId = to(node["subscription_id"], string)

# Custom JSON serialization for EventSubscription with custom field names
proc `%`*(obj: EventSubscription): JsonNode =
  result = newJObject()
  result["callback_url"] = %obj.callbackUrl
  result["event_type"] = %obj.eventType
  result["is_active"] = %obj.isActive
  result["subscription_id"] = %obj.subscriptionId

