#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AbsenceType* {.pure.} = enum
  Vacation
  Sick
  Sabbatical
  Parental
  Other

func `%`*(v: AbsenceType): JsonNode =
  result = case v:
    of AbsenceType.Vacation: %"vacation"
    of AbsenceType.Sick: %"sick"
    of AbsenceType.Sabbatical: %"sabbatical"
    of AbsenceType.Parental: %"parental"
    of AbsenceType.Other: %"other"

func `$`*(v: AbsenceType): string =
  result = case v:
    of AbsenceType.Vacation: $("vacation")
    of AbsenceType.Sick: $("sick")
    of AbsenceType.Sabbatical: $("sabbatical")
    of AbsenceType.Parental: $("parental")
    of AbsenceType.Other: $("other")

proc to*(node: JsonNode, T: typedesc[AbsenceType]): AbsenceType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum AbsenceType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("vacation"):
    return AbsenceType.Vacation
  of $("sick"):
    return AbsenceType.Sick
  of $("sabbatical"):
    return AbsenceType.Sabbatical
  of $("parental"):
    return AbsenceType.Parental
  of $("other"):
    return AbsenceType.Other
  else:
    raise newException(ValueError, "Invalid enum value for AbsenceType: " & strVal)

