#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type BudgetGoalRequest* = object
  ## 
  monthlyGoal*: string ## Monthly goal amount (gross). 0 means \"no goal\" (fallback to default).
  year*: int ## Budget year the goal applies to.


# Custom JSON deserialization for BudgetGoalRequest with custom field names
proc to*(node: JsonNode, T: typedesc[BudgetGoalRequest]): BudgetGoalRequest =
  result = BudgetGoalRequest()
  if node.kind == JObject:
    if node.hasKey("monthly_goal"):
      result.monthlyGoal = to(node["monthly_goal"], string)
    if node.hasKey("year"):
      result.year = to(node["year"], int)

# Custom JSON serialization for BudgetGoalRequest with custom field names
proc `%`*(obj: BudgetGoalRequest): JsonNode =
  result = newJObject()
  result["monthly_goal"] = %obj.monthlyGoal
  result["year"] = %obj.year

