#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ImportJobStatus* = object
  ## 
  error*: Option[string] ## Set only when the job failed.
  jobId*: string
  processed*: int64
  progress*: int ## 0–100
  provider*: Option[string] ## Which competitor the import came from (lexoffice | billbee); the frontend uses it to label the job. Absent for legacy jobs.
  stage*: string ## queued | fetching | downloading | importing | done
  status*: string ## pending | running | done | failed
  total*: int64


# Custom JSON deserialization for ImportJobStatus with custom field names
proc to*(node: JsonNode, T: typedesc[ImportJobStatus]): ImportJobStatus =
  result = ImportJobStatus()
  if node.kind == JObject:
    if node.hasKey("error") and node["error"].kind != JNull:
      result.error = some(to(node["error"], typeof(result.error.get())))
    if node.hasKey("job_id"):
      result.jobId = to(node["job_id"], string)
    if node.hasKey("processed"):
      result.processed = to(node["processed"], int64)
    if node.hasKey("progress"):
      result.progress = to(node["progress"], int)
    if node.hasKey("provider") and node["provider"].kind != JNull:
      result.provider = some(to(node["provider"], typeof(result.provider.get())))
    if node.hasKey("stage"):
      result.stage = to(node["stage"], string)
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("total"):
      result.total = to(node["total"], int64)

# Custom JSON serialization for ImportJobStatus with custom field names
proc `%`*(obj: ImportJobStatus): JsonNode =
  result = newJObject()
  if obj.error.isSome():
    result["error"] = %obj.error.get()
  result["job_id"] = %obj.jobId
  result["processed"] = %obj.processed
  result["progress"] = %obj.progress
  if obj.provider.isSome():
    result["provider"] = %obj.provider.get()
  result["stage"] = %obj.stage
  result["status"] = %obj.status
  result["total"] = %obj.total

