#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_plausibility_check
import model_plausibility_summary

type PlausibilityReport* = object
  ## 
  checks*: seq[PlausibilityCheck]
  generatedAt*: string
  summary*: PlausibilitySummary


# Custom JSON deserialization for PlausibilityReport with custom field names
proc to*(node: JsonNode, T: typedesc[PlausibilityReport]): PlausibilityReport =
  result = PlausibilityReport()
  if node.kind == JObject:
    if node.hasKey("checks"):
      result.checks = to(node["checks"], seq[PlausibilityCheck])
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("summary"):
      result.summary = to(node["summary"], PlausibilitySummary)

# Custom JSON serialization for PlausibilityReport with custom field names
proc `%`*(obj: PlausibilityReport): JsonNode =
  result = newJObject()
  result["checks"] = %obj.checks
  result["generated_at"] = %obj.generatedAt
  result["summary"] = %obj.summary

