#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ContactType* {.pure.} = enum
  Customer
  Supplier

func `%`*(v: ContactType): JsonNode =
  result = case v:
    of ContactType.Customer: %"customer"
    of ContactType.Supplier: %"supplier"

func `$`*(v: ContactType): string =
  result = case v:
    of ContactType.Customer: $("customer")
    of ContactType.Supplier: $("supplier")

proc to*(node: JsonNode, T: typedesc[ContactType]): ContactType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ContactType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("customer"):
    return ContactType.Customer
  of $("supplier"):
    return ContactType.Supplier
  else:
    raise newException(ValueError, "Invalid enum value for ContactType: " & strVal)

