#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PostingCategory* = object
  ## 
  accountNumber*: Option[string]
  accountNumberSkr03*: Option[string]
  accountNumberSkr04*: Option[string]
  accountNumberSkr49*: Option[string]
  categoryId*: string
  defaultVatRate*: int
  description*: Option[string]
  eksCategory*: Option[string]
  isActive*: bool
  isSystem*: bool
  name*: string
  skrVersion*: string
  `type`*: string


# Custom JSON deserialization for PostingCategory with custom field names
proc to*(node: JsonNode, T: typedesc[PostingCategory]): PostingCategory =
  result = PostingCategory()
  if node.kind == JObject:
    if node.hasKey("account_number") and node["account_number"].kind != JNull:
      result.accountNumber = some(to(node["account_number"], typeof(result.accountNumber.get())))
    if node.hasKey("account_number_skr03") and node["account_number_skr03"].kind != JNull:
      result.accountNumberSkr03 = some(to(node["account_number_skr03"], typeof(result.accountNumberSkr03.get())))
    if node.hasKey("account_number_skr04") and node["account_number_skr04"].kind != JNull:
      result.accountNumberSkr04 = some(to(node["account_number_skr04"], typeof(result.accountNumberSkr04.get())))
    if node.hasKey("account_number_skr49") and node["account_number_skr49"].kind != JNull:
      result.accountNumberSkr49 = some(to(node["account_number_skr49"], typeof(result.accountNumberSkr49.get())))
    if node.hasKey("category_id"):
      result.categoryId = to(node["category_id"], string)
    if node.hasKey("default_vat_rate"):
      result.defaultVatRate = to(node["default_vat_rate"], int)
    if node.hasKey("description") and node["description"].kind != JNull:
      result.description = some(to(node["description"], typeof(result.description.get())))
    if node.hasKey("eks_category") and node["eks_category"].kind != JNull:
      result.eksCategory = some(to(node["eks_category"], typeof(result.eksCategory.get())))
    if node.hasKey("is_active"):
      result.isActive = to(node["is_active"], bool)
    if node.hasKey("is_system"):
      result.isSystem = to(node["is_system"], bool)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("skr_version"):
      result.skrVersion = to(node["skr_version"], string)
    if node.hasKey("type"):
      result.`type` = to(node["type"], string)

# Custom JSON serialization for PostingCategory with custom field names
proc `%`*(obj: PostingCategory): JsonNode =
  result = newJObject()
  if obj.accountNumber.isSome():
    result["account_number"] = %obj.accountNumber.get()
  if obj.accountNumberSkr03.isSome():
    result["account_number_skr03"] = %obj.accountNumberSkr03.get()
  if obj.accountNumberSkr04.isSome():
    result["account_number_skr04"] = %obj.accountNumberSkr04.get()
  if obj.accountNumberSkr49.isSome():
    result["account_number_skr49"] = %obj.accountNumberSkr49.get()
  result["category_id"] = %obj.categoryId
  result["default_vat_rate"] = %obj.defaultVatRate
  if obj.description.isSome():
    result["description"] = %obj.description.get()
  if obj.eksCategory.isSome():
    result["eks_category"] = %obj.eksCategory.get()
  result["is_active"] = %obj.isActive
  result["is_system"] = %obj.isSystem
  result["name"] = %obj.name
  result["skr_version"] = %obj.skrVersion
  result["type"] = %obj.`type`

