#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type InventoryCountStatus* {.pure.} = enum
  Draft
  Counting
  Reviewed
  Posted

func `%`*(v: InventoryCountStatus): JsonNode =
  result = case v:
    of InventoryCountStatus.Draft: %"draft"
    of InventoryCountStatus.Counting: %"counting"
    of InventoryCountStatus.Reviewed: %"reviewed"
    of InventoryCountStatus.Posted: %"posted"

func `$`*(v: InventoryCountStatus): string =
  result = case v:
    of InventoryCountStatus.Draft: $("draft")
    of InventoryCountStatus.Counting: $("counting")
    of InventoryCountStatus.Reviewed: $("reviewed")
    of InventoryCountStatus.Posted: $("posted")

proc to*(node: JsonNode, T: typedesc[InventoryCountStatus]): InventoryCountStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum InventoryCountStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("draft"):
    return InventoryCountStatus.Draft
  of $("counting"):
    return InventoryCountStatus.Counting
  of $("reviewed"):
    return InventoryCountStatus.Reviewed
  of $("posted"):
    return InventoryCountStatus.Posted
  else:
    raise newException(ValueError, "Invalid enum value for InventoryCountStatus: " & strVal)

