#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ResetPasswordRequest* = object
  ## 
  newPassword*: string
  token*: string


# Custom JSON deserialization for ResetPasswordRequest with custom field names
proc to*(node: JsonNode, T: typedesc[ResetPasswordRequest]): ResetPasswordRequest =
  result = ResetPasswordRequest()
  if node.kind == JObject:
    if node.hasKey("new_password"):
      result.newPassword = to(node["new_password"], string)
    if node.hasKey("token"):
      result.token = to(node["token"], string)

# Custom JSON serialization for ResetPasswordRequest with custom field names
proc `%`*(obj: ResetPasswordRequest): JsonNode =
  result = newJObject()
  result["new_password"] = %obj.newPassword
  result["token"] = %obj.token

