#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_payment_status
import model_voucher_status
import model_voucher_type

type VoucherCreate* = object
  ## 
  categoryId*: Option[string]
  contactId*: Option[string] ## References the contact entity.
  contactName*: Option[string]
  currency*: string
  description*: Option[string]
  fileAttachments*: Option[JsonNode]
  lineItems*: Option[JsonNode]
  metadata*: Option[JsonNode]
  notes*: Option[string]
  openAmount*: Option[string]
  paidDate*: Option[string]
  paymentStatus*: Option[PaymentStatus]
  taxAmounts*: Option[JsonNode]
  taxCondition*: Option[string]
  totalGrossAmount*: Option[string]
  totalNetAmount*: Option[string]
  voucherDate*: string
  voucherNumber*: Option[string]
  voucherStatus*: VoucherStatus
  voucherType*: VoucherType

