#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_emission_target_scope

type EmissionTarget* = object
  ## 
  baseValue*: string
  baseYear*: int ## tCO2e in the base year (actuals).
  description*: string ## Transition-plan narrative (ESRS E1-1 light), may be empty.
  scope*: EmissionTargetScope ## \"total\" | \"1\" | \"2\" | \"3\".
  targetValue*: string
  targetYear*: int ## tCO2e target for the target year.
  updatedAt*: Option[string]

