#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type MessageDirection* {.pure.} = enum
  Inbound
  Outbound
  Internal

func `%`*(v: MessageDirection): JsonNode =
  result = case v:
    of MessageDirection.Inbound: %"inbound"
    of MessageDirection.Outbound: %"outbound"
    of MessageDirection.Internal: %"internal"

func `$`*(v: MessageDirection): string =
  result = case v:
    of MessageDirection.Inbound: $("inbound")
    of MessageDirection.Outbound: $("outbound")
    of MessageDirection.Internal: $("internal")

proc to*(node: JsonNode, T: typedesc[MessageDirection]): MessageDirection =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum MessageDirection, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("inbound"):
    return MessageDirection.Inbound
  of $("outbound"):
    return MessageDirection.Outbound
  of $("internal"):
    return MessageDirection.Internal
  else:
    raise newException(ValueError, "Invalid enum value for MessageDirection: " & strVal)

