#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_bilanz_item

type BilanzReport* = object
  ## 
  aktiva*: seq[BilanzItem]
  balanced*: bool
  generatedAt*: string
  passiva*: seq[BilanzItem]
  period*: string
  totalAktiva*: string
  totalPassiva*: string


# Custom JSON deserialization for BilanzReport with custom field names
proc to*(node: JsonNode, T: typedesc[BilanzReport]): BilanzReport =
  result = BilanzReport()
  if node.kind == JObject:
    if node.hasKey("aktiva"):
      result.aktiva = to(node["aktiva"], seq[BilanzItem])
    if node.hasKey("balanced"):
      result.balanced = to(node["balanced"], bool)
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("passiva"):
      result.passiva = to(node["passiva"], seq[BilanzItem])
    if node.hasKey("period"):
      result.period = to(node["period"], string)
    if node.hasKey("total_aktiva"):
      result.totalAktiva = to(node["total_aktiva"], string)
    if node.hasKey("total_passiva"):
      result.totalPassiva = to(node["total_passiva"], string)

# Custom JSON serialization for BilanzReport with custom field names
proc `%`*(obj: BilanzReport): JsonNode =
  result = newJObject()
  result["aktiva"] = %obj.aktiva
  result["balanced"] = %obj.balanced
  result["generated_at"] = %obj.generatedAt
  result["passiva"] = %obj.passiva
  result["period"] = %obj.period
  result["total_aktiva"] = %obj.totalAktiva
  result["total_passiva"] = %obj.totalPassiva

