#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type PackingQueueItem* = object
  ## 
  createdAt*: string
  customerId*: string
  deliveryNotePrinted*: bool
  items*: Option[JsonNode]
  itemsCount*: int
  labelPrinted*: bool
  orderNumber*: string
  orderStatus*: string
  shipmentId*: Option[string]
  shippingAddress*: Option[JsonNode]
  shippingMethod*: string
  trackingNumber*: Option[string]
  videoRecording*: Option[string]


# Custom JSON deserialization for PackingQueueItem with custom field names
proc to*(node: JsonNode, T: typedesc[PackingQueueItem]): PackingQueueItem =
  result = PackingQueueItem()
  if node.kind == JObject:
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("customer_id"):
      result.customerId = to(node["customer_id"], string)
    if node.hasKey("delivery_note_printed"):
      result.deliveryNotePrinted = to(node["delivery_note_printed"], bool)
    if node.hasKey("items") and node["items"].kind != JNull:
      result.items = some(to(node["items"], typeof(result.items.get())))
    if node.hasKey("items_count"):
      result.itemsCount = to(node["items_count"], int)
    if node.hasKey("label_printed"):
      result.labelPrinted = to(node["label_printed"], bool)
    if node.hasKey("order_number"):
      result.orderNumber = to(node["order_number"], string)
    if node.hasKey("order_status"):
      result.orderStatus = to(node["order_status"], string)
    if node.hasKey("shipment_id") and node["shipment_id"].kind != JNull:
      result.shipmentId = some(to(node["shipment_id"], typeof(result.shipmentId.get())))
    if node.hasKey("shipping_address") and node["shipping_address"].kind != JNull:
      result.shippingAddress = some(to(node["shipping_address"], typeof(result.shippingAddress.get())))
    if node.hasKey("shipping_method"):
      result.shippingMethod = to(node["shipping_method"], string)
    if node.hasKey("tracking_number") and node["tracking_number"].kind != JNull:
      result.trackingNumber = some(to(node["tracking_number"], typeof(result.trackingNumber.get())))
    if node.hasKey("video_recording") and node["video_recording"].kind != JNull:
      result.videoRecording = some(to(node["video_recording"], typeof(result.videoRecording.get())))

# Custom JSON serialization for PackingQueueItem with custom field names
proc `%`*(obj: PackingQueueItem): JsonNode =
  result = newJObject()
  result["created_at"] = %obj.createdAt
  result["customer_id"] = %obj.customerId
  result["delivery_note_printed"] = %obj.deliveryNotePrinted
  if obj.items.isSome():
    result["items"] = %obj.items.get()
  result["items_count"] = %obj.itemsCount
  result["label_printed"] = %obj.labelPrinted
  result["order_number"] = %obj.orderNumber
  result["order_status"] = %obj.orderStatus
  if obj.shipmentId.isSome():
    result["shipment_id"] = %obj.shipmentId.get()
  if obj.shippingAddress.isSome():
    result["shipping_address"] = %obj.shippingAddress.get()
  result["shipping_method"] = %obj.shippingMethod
  if obj.trackingNumber.isSome():
    result["tracking_number"] = %obj.trackingNumber.get()
  if obj.videoRecording.isSome():
    result["video_recording"] = %obj.videoRecording.get()

