#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type FristEintrag* = object
  ## 
  bezeichnung*: string
  faellig*: string
  faelligOriginal*: string
  hinweis*: Option[string]
  typ*: string
  zeitraum*: string


# Custom JSON deserialization for FristEintrag with custom field names
proc to*(node: JsonNode, T: typedesc[FristEintrag]): FristEintrag =
  result = FristEintrag()
  if node.kind == JObject:
    if node.hasKey("bezeichnung"):
      result.bezeichnung = to(node["bezeichnung"], string)
    if node.hasKey("faellig"):
      result.faellig = to(node["faellig"], string)
    if node.hasKey("faellig_original"):
      result.faelligOriginal = to(node["faellig_original"], string)
    if node.hasKey("hinweis") and node["hinweis"].kind != JNull:
      result.hinweis = some(to(node["hinweis"], typeof(result.hinweis.get())))
    if node.hasKey("typ"):
      result.typ = to(node["typ"], string)
    if node.hasKey("zeitraum"):
      result.zeitraum = to(node["zeitraum"], string)

# Custom JSON serialization for FristEintrag with custom field names
proc `%`*(obj: FristEintrag): JsonNode =
  result = newJObject()
  result["bezeichnung"] = %obj.bezeichnung
  result["faellig"] = %obj.faellig
  result["faellig_original"] = %obj.faelligOriginal
  if obj.hinweis.isSome():
    result["hinweis"] = %obj.hinweis.get()
  result["typ"] = %obj.typ
  result["zeitraum"] = %obj.zeitraum

