#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_stille_partner_zeile

type StilleReport* = object
  ## 
  jahresueberschuss*: string
  partners*: seq[StillePartnerZeile]
  year*: int


# Custom JSON deserialization for StilleReport with custom field names
proc to*(node: JsonNode, T: typedesc[StilleReport]): StilleReport =
  result = StilleReport()
  if node.kind == JObject:
    if node.hasKey("jahresueberschuss"):
      result.jahresueberschuss = to(node["jahresueberschuss"], string)
    if node.hasKey("partners"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["partners"]
      if arrayNode.kind == JArray:
        result.partners = @[]
        for item in arrayNode.items:
          result.partners.add(to(item, StillePartnerZeile))
    if node.hasKey("year"):
      result.year = to(node["year"], int)

# Custom JSON serialization for StilleReport with custom field names
proc `%`*(obj: StilleReport): JsonNode =
  result = newJObject()
  result["jahresueberschuss"] = %obj.jahresueberschuss
  result["partners"] = %obj.partners
  result["year"] = %obj.year

