#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ShippingRate* = object
  ## 
  breakdown*: Option[string]
  carrier*: string
  crossBorderSurcharge*: Option[string]
  destinationCountry*: string ## ISO-2 code of destination country.
  estimatedDays*: Option[int]
  fromApi*: bool ## True when the rate was obtained via an API call rather than calculation.
  insuredValue*: Option[string]
  islandSurcharge*: Option[string]
  originCountry*: string ## ISO-2 code of origin country.
  rate*: string
  service*: string
  volumeDiscount*: Option[string]
  weightKg*: float64


# Custom JSON deserialization for ShippingRate with custom field names
proc to*(node: JsonNode, T: typedesc[ShippingRate]): ShippingRate =
  result = ShippingRate()
  if node.kind == JObject:
    if node.hasKey("breakdown") and node["breakdown"].kind != JNull:
      result.breakdown = some(to(node["breakdown"], typeof(result.breakdown.get())))
    if node.hasKey("carrier"):
      result.carrier = to(node["carrier"], string)
    if node.hasKey("cross_border_surcharge") and node["cross_border_surcharge"].kind != JNull:
      result.crossBorderSurcharge = some(to(node["cross_border_surcharge"], typeof(result.crossBorderSurcharge.get())))
    if node.hasKey("destination_country"):
      result.destinationCountry = to(node["destination_country"], string)
    if node.hasKey("estimated_days") and node["estimated_days"].kind != JNull:
      result.estimatedDays = some(to(node["estimated_days"], typeof(result.estimatedDays.get())))
    if node.hasKey("from_api"):
      result.fromApi = to(node["from_api"], bool)
    if node.hasKey("insured_value") and node["insured_value"].kind != JNull:
      result.insuredValue = some(to(node["insured_value"], typeof(result.insuredValue.get())))
    if node.hasKey("island_surcharge") and node["island_surcharge"].kind != JNull:
      result.islandSurcharge = some(to(node["island_surcharge"], typeof(result.islandSurcharge.get())))
    if node.hasKey("origin_country"):
      result.originCountry = to(node["origin_country"], string)
    if node.hasKey("rate"):
      result.rate = to(node["rate"], string)
    if node.hasKey("service"):
      result.service = to(node["service"], string)
    if node.hasKey("volume_discount") and node["volume_discount"].kind != JNull:
      result.volumeDiscount = some(to(node["volume_discount"], typeof(result.volumeDiscount.get())))
    if node.hasKey("weight_kg"):
      result.weightKg = to(node["weight_kg"], float64)

# Custom JSON serialization for ShippingRate with custom field names
proc `%`*(obj: ShippingRate): JsonNode =
  result = newJObject()
  if obj.breakdown.isSome():
    result["breakdown"] = %obj.breakdown.get()
  result["carrier"] = %obj.carrier
  if obj.crossBorderSurcharge.isSome():
    result["cross_border_surcharge"] = %obj.crossBorderSurcharge.get()
  result["destination_country"] = %obj.destinationCountry
  if obj.estimatedDays.isSome():
    result["estimated_days"] = %obj.estimatedDays.get()
  result["from_api"] = %obj.fromApi
  if obj.insuredValue.isSome():
    result["insured_value"] = %obj.insuredValue.get()
  if obj.islandSurcharge.isSome():
    result["island_surcharge"] = %obj.islandSurcharge.get()
  result["origin_country"] = %obj.originCountry
  result["rate"] = %obj.rate
  result["service"] = %obj.service
  if obj.volumeDiscount.isSome():
    result["volume_discount"] = %obj.volumeDiscount.get()
  result["weight_kg"] = %obj.weightKg

