#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type KstErgebnis* = object
  ## 
  gesamt*: string
  gesamtbelastung*: string
  gewerbesteuer*: string
  gewinn*: string
  istKapitalgesellschaft*: bool
  jahr*: int
  koerperschaftsteuer*: string
  solidaritaetszuschlag*: string


# Custom JSON deserialization for KstErgebnis with custom field names
proc to*(node: JsonNode, T: typedesc[KstErgebnis]): KstErgebnis =
  result = KstErgebnis()
  if node.kind == JObject:
    if node.hasKey("gesamt"):
      result.gesamt = to(node["gesamt"], string)
    if node.hasKey("gesamtbelastung"):
      result.gesamtbelastung = to(node["gesamtbelastung"], string)
    if node.hasKey("gewerbesteuer"):
      result.gewerbesteuer = to(node["gewerbesteuer"], string)
    if node.hasKey("gewinn"):
      result.gewinn = to(node["gewinn"], string)
    if node.hasKey("ist_kapitalgesellschaft"):
      result.istKapitalgesellschaft = to(node["ist_kapitalgesellschaft"], bool)
    if node.hasKey("jahr"):
      result.jahr = to(node["jahr"], int)
    if node.hasKey("koerperschaftsteuer"):
      result.koerperschaftsteuer = to(node["koerperschaftsteuer"], string)
    if node.hasKey("solidaritaetszuschlag"):
      result.solidaritaetszuschlag = to(node["solidaritaetszuschlag"], string)

# Custom JSON serialization for KstErgebnis with custom field names
proc `%`*(obj: KstErgebnis): JsonNode =
  result = newJObject()
  result["gesamt"] = %obj.gesamt
  result["gesamtbelastung"] = %obj.gesamtbelastung
  result["gewerbesteuer"] = %obj.gewerbesteuer
  result["gewinn"] = %obj.gewinn
  result["ist_kapitalgesellschaft"] = %obj.istKapitalgesellschaft
  result["jahr"] = %obj.jahr
  result["koerperschaftsteuer"] = %obj.koerperschaftsteuer
  result["solidaritaetszuschlag"] = %obj.solidaritaetszuschlag

