#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CreateTicketRequest* = object
  ## Request body for creating a support ticket. Wraps the generated `SupportTicketCreateDto` fields plus `message_body` which is not a Model field (used to create the initial `ticket_message`).
  channelId*: Option[string]
  channelType*: Option[string]
  customerEmail*: Option[string]
  customerId*: Option[string]
  customerName*: Option[string]
  externalId*: Option[string]
  messageBody*: string
  orderRef*: Option[string]
  subject*: string


# Custom JSON deserialization for CreateTicketRequest with custom field names
proc to*(node: JsonNode, T: typedesc[CreateTicketRequest]): CreateTicketRequest =
  result = CreateTicketRequest()
  if node.kind == JObject:
    if node.hasKey("channel_id") and node["channel_id"].kind != JNull:
      result.channelId = some(to(node["channel_id"], typeof(result.channelId.get())))
    if node.hasKey("channel_type") and node["channel_type"].kind != JNull:
      result.channelType = some(to(node["channel_type"], typeof(result.channelType.get())))
    if node.hasKey("customer_email") and node["customer_email"].kind != JNull:
      result.customerEmail = some(to(node["customer_email"], typeof(result.customerEmail.get())))
    if node.hasKey("customer_id") and node["customer_id"].kind != JNull:
      result.customerId = some(to(node["customer_id"], typeof(result.customerId.get())))
    if node.hasKey("customer_name") and node["customer_name"].kind != JNull:
      result.customerName = some(to(node["customer_name"], typeof(result.customerName.get())))
    if node.hasKey("external_id") and node["external_id"].kind != JNull:
      result.externalId = some(to(node["external_id"], typeof(result.externalId.get())))
    if node.hasKey("message_body"):
      result.messageBody = to(node["message_body"], string)
    if node.hasKey("order_ref") and node["order_ref"].kind != JNull:
      result.orderRef = some(to(node["order_ref"], typeof(result.orderRef.get())))
    if node.hasKey("subject"):
      result.subject = to(node["subject"], string)

# Custom JSON serialization for CreateTicketRequest with custom field names
proc `%`*(obj: CreateTicketRequest): JsonNode =
  result = newJObject()
  if obj.channelId.isSome():
    result["channel_id"] = %obj.channelId.get()
  if obj.channelType.isSome():
    result["channel_type"] = %obj.channelType.get()
  if obj.customerEmail.isSome():
    result["customer_email"] = %obj.customerEmail.get()
  if obj.customerId.isSome():
    result["customer_id"] = %obj.customerId.get()
  if obj.customerName.isSome():
    result["customer_name"] = %obj.customerName.get()
  if obj.externalId.isSome():
    result["external_id"] = %obj.externalId.get()
  result["message_body"] = %obj.messageBody
  if obj.orderRef.isSome():
    result["order_ref"] = %obj.orderRef.get()
  result["subject"] = %obj.subject

