#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CheckStatus* {.pure.} = enum
  Ok
  Warning
  Error

func `%`*(v: CheckStatus): JsonNode =
  result = case v:
    of CheckStatus.Ok: %"Ok"
    of CheckStatus.Warning: %"Warning"
    of CheckStatus.Error: %"Error"

func `$`*(v: CheckStatus): string =
  result = case v:
    of CheckStatus.Ok: $("Ok")
    of CheckStatus.Warning: $("Warning")
    of CheckStatus.Error: $("Error")

proc to*(node: JsonNode, T: typedesc[CheckStatus]): CheckStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum CheckStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("Ok"):
    return CheckStatus.Ok
  of $("Warning"):
    return CheckStatus.Warning
  of $("Error"):
    return CheckStatus.Error
  else:
    raise newException(ValueError, "Invalid enum value for CheckStatus: " & strVal)

