#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type DataQuality* = object
  ## 
  activityLines*: int
  activitySharePct*: float64
  spendLines*: int


# Custom JSON deserialization for DataQuality with custom field names
proc to*(node: JsonNode, T: typedesc[DataQuality]): DataQuality =
  result = DataQuality()
  if node.kind == JObject:
    if node.hasKey("activity_lines"):
      result.activityLines = to(node["activity_lines"], int)
    if node.hasKey("activity_share_pct"):
      result.activitySharePct = to(node["activity_share_pct"], float64)
    if node.hasKey("spend_lines"):
      result.spendLines = to(node["spend_lines"], int)

# Custom JSON serialization for DataQuality with custom field names
proc `%`*(obj: DataQuality): JsonNode =
  result = newJObject()
  result["activity_lines"] = %obj.activityLines
  result["activity_share_pct"] = %obj.activitySharePct
  result["spend_lines"] = %obj.spendLines

