#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ShippingThreshold* = object
  ## 
  isActive*: Option[bool]
  maxSellable*: Option[int64] ## Optional ceiling for the deliverable quantity.
  name*: string
  notes*: Option[string]
  productId*: Option[string] ## None = applies to all products. References the product entity.
  reserveStock*: Option[int64] ## Buffer of stock that must not be sold.
  warehouseId*: Option[string] ## None = applies to all warehouses. References the warehouse entity.

