#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_instrument_type

type SilentPartnerCreate* = object
  ## 
  contractDate*: Option[string] ## Datum des Vertragsabschlusses.
  einlage*: Option[string] ## Einlage (§ 230 HGB).
  gewinnquotePct*: Option[string] ## Gewinnbeteiligungsquote in Prozent (§ 231 HGB).
  gewinnvortrag*: Option[string] ## Nicht erhobene Gewinne (§ 232 Abs. 3 HGB).
  instrumentType*: InstrumentType ## Instrument: \"typisch\" | \"atypisch\" | \"partiarisches_darlehen\" | \"genussrecht\".
  kestPflichtig*: Option[bool] ## 25 % Kapitalertragsteuer einbehalten (§ 43 Abs. 1 Nr. 3 EStG; typisch + partiarisches Darlehen).
  name*: Option[string] ## Name des stillen Gesellschafters.
  notes*: Option[string] ## Freitext-Notizen.
  verlustVerrechnungskonto*: Option[string] ## Kumulierte Verluste gegen die Einlage (§ 232 Abs. 2 HGB, ≤ Einlage).
  verlustbeteiligung*: Option[bool] ## Verlustbeteiligung (§ 231 Abs. 2 HGB; kann ausgeschlossen werden).

