#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type KontoItem* = object
  ## 
  anfangsbestand*: string
  habenUmsatz*: string
  konto*: string
  name*: string
  saldo*: string
  sollUmsatz*: string


# Custom JSON deserialization for KontoItem with custom field names
proc to*(node: JsonNode, T: typedesc[KontoItem]): KontoItem =
  result = KontoItem()
  if node.kind == JObject:
    if node.hasKey("anfangsbestand"):
      result.anfangsbestand = to(node["anfangsbestand"], string)
    if node.hasKey("haben_umsatz"):
      result.habenUmsatz = to(node["haben_umsatz"], string)
    if node.hasKey("konto"):
      result.konto = to(node["konto"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("saldo"):
      result.saldo = to(node["saldo"], string)
    if node.hasKey("soll_umsatz"):
      result.sollUmsatz = to(node["soll_umsatz"], string)

# Custom JSON serialization for KontoItem with custom field names
proc `%`*(obj: KontoItem): JsonNode =
  result = newJObject()
  result["anfangsbestand"] = %obj.anfangsbestand
  result["haben_umsatz"] = %obj.habenUmsatz
  result["konto"] = %obj.konto
  result["name"] = %obj.name
  result["saldo"] = %obj.saldo
  result["soll_umsatz"] = %obj.sollUmsatz

