#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type MovementType* {.pure.} = enum
  GoodsReceipt
  GoodsReceiptReversal
  TransferIn
  TransferOut
  ReturnRestock
  ProductionConsumption
  ProductionCompletion
  InventoryAdjustment
  Sale
  Other

func `%`*(v: MovementType): JsonNode =
  result = case v:
    of MovementType.GoodsReceipt: %"goods_receipt"
    of MovementType.GoodsReceiptReversal: %"goods_receipt_reversal"
    of MovementType.TransferIn: %"transfer_in"
    of MovementType.TransferOut: %"transfer_out"
    of MovementType.ReturnRestock: %"return_restock"
    of MovementType.ProductionConsumption: %"production_consumption"
    of MovementType.ProductionCompletion: %"production_completion"
    of MovementType.InventoryAdjustment: %"inventory_adjustment"
    of MovementType.Sale: %"sale"
    of MovementType.Other: %"other"

func `$`*(v: MovementType): string =
  result = case v:
    of MovementType.GoodsReceipt: $("goods_receipt")
    of MovementType.GoodsReceiptReversal: $("goods_receipt_reversal")
    of MovementType.TransferIn: $("transfer_in")
    of MovementType.TransferOut: $("transfer_out")
    of MovementType.ReturnRestock: $("return_restock")
    of MovementType.ProductionConsumption: $("production_consumption")
    of MovementType.ProductionCompletion: $("production_completion")
    of MovementType.InventoryAdjustment: $("inventory_adjustment")
    of MovementType.Sale: $("sale")
    of MovementType.Other: $("other")

proc to*(node: JsonNode, T: typedesc[MovementType]): MovementType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum MovementType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("goods_receipt"):
    return MovementType.GoodsReceipt
  of $("goods_receipt_reversal"):
    return MovementType.GoodsReceiptReversal
  of $("transfer_in"):
    return MovementType.TransferIn
  of $("transfer_out"):
    return MovementType.TransferOut
  of $("return_restock"):
    return MovementType.ReturnRestock
  of $("production_consumption"):
    return MovementType.ProductionConsumption
  of $("production_completion"):
    return MovementType.ProductionCompletion
  of $("inventory_adjustment"):
    return MovementType.InventoryAdjustment
  of $("sale"):
    return MovementType.Sale
  of $("other"):
    return MovementType.Other
  else:
    raise newException(ValueError, "Invalid enum value for MovementType: " & strVal)

