#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type DownPaymentInvoice* = object
  ## 
  contactId*: Option[string]
  contactName*: Option[string]
  createdAt*: string
  currency*: string
  id*: string
  notes*: Option[string]
  paidAmount*: string
  totalAmount*: string
  voucherDate*: string
  voucherNumber*: Option[string]
  voucherStatus*: string


# Custom JSON deserialization for DownPaymentInvoice with custom field names
proc to*(node: JsonNode, T: typedesc[DownPaymentInvoice]): DownPaymentInvoice =
  result = DownPaymentInvoice()
  if node.kind == JObject:
    if node.hasKey("contact_id") and node["contact_id"].kind != JNull:
      result.contactId = some(to(node["contact_id"], typeof(result.contactId.get())))
    if node.hasKey("contact_name") and node["contact_name"].kind != JNull:
      result.contactName = some(to(node["contact_name"], typeof(result.contactName.get())))
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("currency"):
      result.currency = to(node["currency"], string)
    if node.hasKey("id"):
      result.id = to(node["id"], string)
    if node.hasKey("notes") and node["notes"].kind != JNull:
      result.notes = some(to(node["notes"], typeof(result.notes.get())))
    if node.hasKey("paid_amount"):
      result.paidAmount = to(node["paid_amount"], string)
    if node.hasKey("total_amount"):
      result.totalAmount = to(node["total_amount"], string)
    if node.hasKey("voucher_date"):
      result.voucherDate = to(node["voucher_date"], string)
    if node.hasKey("voucher_number") and node["voucher_number"].kind != JNull:
      result.voucherNumber = some(to(node["voucher_number"], typeof(result.voucherNumber.get())))
    if node.hasKey("voucher_status"):
      result.voucherStatus = to(node["voucher_status"], string)

# Custom JSON serialization for DownPaymentInvoice with custom field names
proc `%`*(obj: DownPaymentInvoice): JsonNode =
  result = newJObject()
  if obj.contactId.isSome():
    result["contact_id"] = %obj.contactId.get()
  if obj.contactName.isSome():
    result["contact_name"] = %obj.contactName.get()
  result["created_at"] = %obj.createdAt
  result["currency"] = %obj.currency
  result["id"] = %obj.id
  if obj.notes.isSome():
    result["notes"] = %obj.notes.get()
  result["paid_amount"] = %obj.paidAmount
  result["total_amount"] = %obj.totalAmount
  result["voucher_date"] = %obj.voucherDate
  if obj.voucherNumber.isSome():
    result["voucher_number"] = %obj.voucherNumber.get()
  result["voucher_status"] = %obj.voucherStatus

