#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_konto_item

type KontoReport* = object
  ## 
  generatedAt*: string
  konten*: seq[KontoItem]
  period*: string


# Custom JSON deserialization for KontoReport with custom field names
proc to*(node: JsonNode, T: typedesc[KontoReport]): KontoReport =
  result = KontoReport()
  if node.kind == JObject:
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("konten"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["konten"]
      if arrayNode.kind == JArray:
        result.konten = @[]
        for item in arrayNode.items:
          result.konten.add(to(item, KontoItem))
    if node.hasKey("period"):
      result.period = to(node["period"], string)

# Custom JSON serialization for KontoReport with custom field names
proc `%`*(obj: KontoReport): JsonNode =
  result = newJObject()
  result["generated_at"] = %obj.generatedAt
  result["konten"] = %obj.konten
  result["period"] = %obj.period

