#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ServiceAssignmentStatus* {.pure.} = enum
  Planned
  Confirmed
  EnRoute
  InProgress
  Completed
  Cancelled

func `%`*(v: ServiceAssignmentStatus): JsonNode =
  result = case v:
    of ServiceAssignmentStatus.Planned: %"planned"
    of ServiceAssignmentStatus.Confirmed: %"confirmed"
    of ServiceAssignmentStatus.EnRoute: %"en_route"
    of ServiceAssignmentStatus.InProgress: %"in_progress"
    of ServiceAssignmentStatus.Completed: %"completed"
    of ServiceAssignmentStatus.Cancelled: %"cancelled"

func `$`*(v: ServiceAssignmentStatus): string =
  result = case v:
    of ServiceAssignmentStatus.Planned: $("planned")
    of ServiceAssignmentStatus.Confirmed: $("confirmed")
    of ServiceAssignmentStatus.EnRoute: $("en_route")
    of ServiceAssignmentStatus.InProgress: $("in_progress")
    of ServiceAssignmentStatus.Completed: $("completed")
    of ServiceAssignmentStatus.Cancelled: $("cancelled")

proc to*(node: JsonNode, T: typedesc[ServiceAssignmentStatus]): ServiceAssignmentStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ServiceAssignmentStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("planned"):
    return ServiceAssignmentStatus.Planned
  of $("confirmed"):
    return ServiceAssignmentStatus.Confirmed
  of $("en_route"):
    return ServiceAssignmentStatus.EnRoute
  of $("in_progress"):
    return ServiceAssignmentStatus.InProgress
  of $("completed"):
    return ServiceAssignmentStatus.Completed
  of $("cancelled"):
    return ServiceAssignmentStatus.Cancelled
  else:
    raise newException(ValueError, "Invalid enum value for ServiceAssignmentStatus: " & strVal)

