#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type LiquidityPosition* = object
  ## 
  accountsPayable*: float64
  accountsReceivable*: float64
  cashAndEquivalents*: float64
  currentRatio*: float64
  quickRatio*: float64
  workingCapital*: float64


# Custom JSON deserialization for LiquidityPosition with custom field names
proc to*(node: JsonNode, T: typedesc[LiquidityPosition]): LiquidityPosition =
  result = LiquidityPosition()
  if node.kind == JObject:
    if node.hasKey("accounts_payable"):
      result.accountsPayable = to(node["accounts_payable"], float64)
    if node.hasKey("accounts_receivable"):
      result.accountsReceivable = to(node["accounts_receivable"], float64)
    if node.hasKey("cash_and_equivalents"):
      result.cashAndEquivalents = to(node["cash_and_equivalents"], float64)
    if node.hasKey("current_ratio"):
      result.currentRatio = to(node["current_ratio"], float64)
    if node.hasKey("quick_ratio"):
      result.quickRatio = to(node["quick_ratio"], float64)
    if node.hasKey("working_capital"):
      result.workingCapital = to(node["working_capital"], float64)

# Custom JSON serialization for LiquidityPosition with custom field names
proc `%`*(obj: LiquidityPosition): JsonNode =
  result = newJObject()
  result["accounts_payable"] = %obj.accountsPayable
  result["accounts_receivable"] = %obj.accountsReceivable
  result["cash_and_equivalents"] = %obj.cashAndEquivalents
  result["current_ratio"] = %obj.currentRatio
  result["quick_ratio"] = %obj.quickRatio
  result["working_capital"] = %obj.workingCapital

