#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ShipmentStatusUpdate* = object
  ## 
  deliveredAt*: Option[string]
  signedBy*: Option[string]
  status*: string
  trackingNumber*: Option[string]


# Custom JSON deserialization for ShipmentStatusUpdate with custom field names
proc to*(node: JsonNode, T: typedesc[ShipmentStatusUpdate]): ShipmentStatusUpdate =
  result = ShipmentStatusUpdate()
  if node.kind == JObject:
    if node.hasKey("delivered_at") and node["delivered_at"].kind != JNull:
      result.deliveredAt = some(to(node["delivered_at"], typeof(result.deliveredAt.get())))
    if node.hasKey("signed_by") and node["signed_by"].kind != JNull:
      result.signedBy = some(to(node["signed_by"], typeof(result.signedBy.get())))
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("tracking_number") and node["tracking_number"].kind != JNull:
      result.trackingNumber = some(to(node["tracking_number"], typeof(result.trackingNumber.get())))

# Custom JSON serialization for ShipmentStatusUpdate with custom field names
proc `%`*(obj: ShipmentStatusUpdate): JsonNode =
  result = newJObject()
  if obj.deliveredAt.isSome():
    result["delivered_at"] = %obj.deliveredAt.get()
  if obj.signedBy.isSome():
    result["signed_by"] = %obj.signedBy.get()
  result["status"] = %obj.status
  if obj.trackingNumber.isSome():
    result["tracking_number"] = %obj.trackingNumber.get()

