#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type ProductCreate* = object
  ## 
  availability*: Option[string]
  barcode*: Option[string]
  brand*: Option[string]
  categoryId*: Option[string]
  condition*: Option[string]
  defaultLedgerAccount*: Option[string]
  defaultPrice*: Option[string]
  defaultPriceFormulaId*: Option[string] ## References the price formula entity.
  defaultTaxRate*: Option[string]
  description*: Option[string]
  gtin*: Option[string]
  height*: Option[string]
  imageLink*: Option[string]
  images*: Option[JsonNode]
  isTaxable*: Option[bool]
  length*: Option[string]
  link*: Option[string]
  maxStock*: Option[int64] ## Target stock level used by reorder proposals.
  minStock*: Option[int64] ## Reorder point — when stock falls below this, a reorder is suggested.
  mpn*: Option[string]
  name*: string
  packageHeight*: Option[string]
  packageLength*: Option[string]
  packageWeightUnit*: Option[string]
  packageWeightValue*: Option[string]
  packageWidth*: Option[string]
  productCode*: string
  productType*: Option[string]
  purchasePrice*: Option[string]
  reorderQuantity*: Option[int64] ## Suggested purchase quantity when a reorder proposal is created.
  salePrice*: Option[string]
  shippingPrice*: Option[string]
  shippingRequiresInsurance*: Option[bool]
  sku*: string
  stockQuantity*: Option[int64]
  tags*: Option[JsonNode]
  taxPrice*: Option[string]
  trackBatch*: Option[bool] ## Whether this product requires batch (Chargennummer) tracking.
  trackSerial*: Option[bool] ## Whether this product requires serial-number tracking.
  unit*: Option[JsonNode]
  weightUnit*: Option[string]
  weightValue*: Option[string]
  width*: Option[string]

