#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type Shipment* = object
  ## 
  deliveredAt*: Option[string]
  labelUrl*: Option[string]
  lineItemsShipment*: Option[JsonNode]
  orderId*: string ## References the order entity.
  recipientAddress*: Option[JsonNode]
  shipmentDate*: string
  shippingCarrier*: string
  shippingCost*: Option[string]
  shippingMethod*: Option[string]
  signedBy*: Option[string]
  status*: string
  trackingEvents*: Option[JsonNode] ## Latest carrier tracking events (from the live tracking API).
  trackingNumber*: Option[string]
  trackingUrl*: Option[string]
  weightKg*: Option[float64]

