#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_webhook_direction
import model_webhook_event_status

type WebhookEvent* = object
  ## 
  attempts*: Option[int]
  channel*: Option[string] ## source for inbound, target URL for outbound.
  direction*: WebhookDirection ## inbound | outbound
  eventType*: string
  lastError*: Option[string]
  payload*: Option[JsonNode]
  status*: Option[WebhookEventStatus] ## accepted | delivered | failed

