#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_euer_zeile

type EuerErgebnis* = object
  ## 
  anlageZugaenge*: string
  gewinnVerlust*: string
  jahr*: int
  summeAusgaben*: string
  summeEinnahmen*: string
  zeilen*: seq[EuerZeile]


# Custom JSON deserialization for EuerErgebnis with custom field names
proc to*(node: JsonNode, T: typedesc[EuerErgebnis]): EuerErgebnis =
  result = EuerErgebnis()
  if node.kind == JObject:
    if node.hasKey("anlage_zugaenge"):
      result.anlageZugaenge = to(node["anlage_zugaenge"], string)
    if node.hasKey("gewinn_verlust"):
      result.gewinnVerlust = to(node["gewinn_verlust"], string)
    if node.hasKey("jahr"):
      result.jahr = to(node["jahr"], int)
    if node.hasKey("summe_ausgaben"):
      result.summeAusgaben = to(node["summe_ausgaben"], string)
    if node.hasKey("summe_einnahmen"):
      result.summeEinnahmen = to(node["summe_einnahmen"], string)
    if node.hasKey("zeilen"):
      result.zeilen = to(node["zeilen"], seq[EuerZeile])

# Custom JSON serialization for EuerErgebnis with custom field names
proc `%`*(obj: EuerErgebnis): JsonNode =
  result = newJObject()
  result["anlage_zugaenge"] = %obj.anlageZugaenge
  result["gewinn_verlust"] = %obj.gewinnVerlust
  result["jahr"] = %obj.jahr
  result["summe_ausgaben"] = %obj.summeAusgaben
  result["summe_einnahmen"] = %obj.summeEinnahmen
  result["zeilen"] = %obj.zeilen

