#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type NotificationDto* = object
  ## Wire shape of a notification row (mirrors frontend Notification type).
  createdAt*: string
  id*: string
  isRead*: bool
  message*: Option[string]
  sentViaEmail*: bool
  tenantId*: string
  title*: string
  userId*: string


# Custom JSON deserialization for NotificationDto with custom field names
proc to*(node: JsonNode, T: typedesc[NotificationDto]): NotificationDto =
  result = NotificationDto()
  if node.kind == JObject:
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("id"):
      result.id = to(node["id"], string)
    if node.hasKey("is_read"):
      result.isRead = to(node["is_read"], bool)
    if node.hasKey("message") and node["message"].kind != JNull:
      result.message = some(to(node["message"], typeof(result.message.get())))
    if node.hasKey("sent_via_email"):
      result.sentViaEmail = to(node["sent_via_email"], bool)
    if node.hasKey("tenant_id"):
      result.tenantId = to(node["tenant_id"], string)
    if node.hasKey("title"):
      result.title = to(node["title"], string)
    if node.hasKey("user_id"):
      result.userId = to(node["user_id"], string)

# Custom JSON serialization for NotificationDto with custom field names
proc `%`*(obj: NotificationDto): JsonNode =
  result = newJObject()
  result["created_at"] = %obj.createdAt
  result["id"] = %obj.id
  result["is_read"] = %obj.isRead
  if obj.message.isSome():
    result["message"] = %obj.message.get()
  result["sent_via_email"] = %obj.sentViaEmail
  result["tenant_id"] = %obj.tenantId
  result["title"] = %obj.title
  result["user_id"] = %obj.userId

