#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AiSuggestionRequest* = object
  ## 
  instructions*: Option[string]
  messageBody*: Option[string]
  ticketId*: string


# Custom JSON deserialization for AiSuggestionRequest with custom field names
proc to*(node: JsonNode, T: typedesc[AiSuggestionRequest]): AiSuggestionRequest =
  result = AiSuggestionRequest()
  if node.kind == JObject:
    if node.hasKey("instructions") and node["instructions"].kind != JNull:
      result.instructions = some(to(node["instructions"], typeof(result.instructions.get())))
    if node.hasKey("message_body") and node["message_body"].kind != JNull:
      result.messageBody = some(to(node["message_body"], typeof(result.messageBody.get())))
    if node.hasKey("ticket_id"):
      result.ticketId = to(node["ticket_id"], string)

# Custom JSON serialization for AiSuggestionRequest with custom field names
proc `%`*(obj: AiSuggestionRequest): JsonNode =
  result = newJObject()
  if obj.instructions.isSome():
    result["instructions"] = %obj.instructions.get()
  if obj.messageBody.isSome():
    result["message_body"] = %obj.messageBody.get()
  result["ticket_id"] = %obj.ticketId

