#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ServiceJobStatus* {.pure.} = enum
  Pending
  Assigned
  EnRoute
  InProgress
  Completed
  Cancelled

func `%`*(v: ServiceJobStatus): JsonNode =
  result = case v:
    of ServiceJobStatus.Pending: %"pending"
    of ServiceJobStatus.Assigned: %"assigned"
    of ServiceJobStatus.EnRoute: %"en_route"
    of ServiceJobStatus.InProgress: %"in_progress"
    of ServiceJobStatus.Completed: %"completed"
    of ServiceJobStatus.Cancelled: %"cancelled"

func `$`*(v: ServiceJobStatus): string =
  result = case v:
    of ServiceJobStatus.Pending: $("pending")
    of ServiceJobStatus.Assigned: $("assigned")
    of ServiceJobStatus.EnRoute: $("en_route")
    of ServiceJobStatus.InProgress: $("in_progress")
    of ServiceJobStatus.Completed: $("completed")
    of ServiceJobStatus.Cancelled: $("cancelled")

proc to*(node: JsonNode, T: typedesc[ServiceJobStatus]): ServiceJobStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ServiceJobStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("pending"):
    return ServiceJobStatus.Pending
  of $("assigned"):
    return ServiceJobStatus.Assigned
  of $("en_route"):
    return ServiceJobStatus.EnRoute
  of $("in_progress"):
    return ServiceJobStatus.InProgress
  of $("completed"):
    return ServiceJobStatus.Completed
  of $("cancelled"):
    return ServiceJobStatus.Cancelled
  else:
    raise newException(ValueError, "Invalid enum value for ServiceJobStatus: " & strVal)

