#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_check_status

type PlausibilitySummary* = object
  ## 
  errors*: int
  overallStatus*: CheckStatus
  passed*: int
  totalChecks*: int
  warnings*: int


# Custom JSON deserialization for PlausibilitySummary with custom field names
proc to*(node: JsonNode, T: typedesc[PlausibilitySummary]): PlausibilitySummary =
  result = PlausibilitySummary()
  if node.kind == JObject:
    if node.hasKey("errors"):
      result.errors = to(node["errors"], int)
    if node.hasKey("overall_status"):
      result.overallStatus = to(node["overall_status"], CheckStatus)
    if node.hasKey("passed"):
      result.passed = to(node["passed"], int)
    if node.hasKey("total_checks"):
      result.totalChecks = to(node["total_checks"], int)
    if node.hasKey("warnings"):
      result.warnings = to(node["warnings"], int)

# Custom JSON serialization for PlausibilitySummary with custom field names
proc `%`*(obj: PlausibilitySummary): JsonNode =
  result = newJObject()
  result["errors"] = %obj.errors
  result["overall_status"] = %obj.overallStatus
  result["passed"] = %obj.passed
  result["total_checks"] = %obj.totalChecks
  result["warnings"] = %obj.warnings

