#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CreateShipmentRequest* = object
  ## 
  carrier*: string ## Carrier name as configured in shipping settings: `ups` or `dhl`.
  service*: Option[string]
  weightKg*: Option[float64]


# Custom JSON deserialization for CreateShipmentRequest with custom field names
proc to*(node: JsonNode, T: typedesc[CreateShipmentRequest]): CreateShipmentRequest =
  result = CreateShipmentRequest()
  if node.kind == JObject:
    if node.hasKey("carrier"):
      result.carrier = to(node["carrier"], string)
    if node.hasKey("service") and node["service"].kind != JNull:
      result.service = some(to(node["service"], typeof(result.service.get())))
    if node.hasKey("weight_kg") and node["weight_kg"].kind != JNull:
      result.weightKg = some(to(node["weight_kg"], typeof(result.weightKg.get())))

# Custom JSON serialization for CreateShipmentRequest with custom field names
proc `%`*(obj: CreateShipmentRequest): JsonNode =
  result = newJObject()
  result["carrier"] = %obj.carrier
  if obj.service.isSome():
    result["service"] = %obj.service.get()
  if obj.weightKg.isSome():
    result["weight_kg"] = %obj.weightKg.get()

