#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_job_title_gap
import model_quartile_band

type PayGapReport* = object
  ## 
  byJobTitle*: seq[JobTitleGap]
  diverseCount*: int
  employeeCount*: int
  femaleCount*: int
  maleCount*: int
  meanGapPct*: float64
  medianGapPct*: float64
  quartiles*: seq[QuartileBand]


# Custom JSON deserialization for PayGapReport with custom field names
proc to*(node: JsonNode, T: typedesc[PayGapReport]): PayGapReport =
  result = PayGapReport()
  if node.kind == JObject:
    if node.hasKey("by_job_title"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["by_job_title"]
      if arrayNode.kind == JArray:
        result.byJobTitle = @[]
        for item in arrayNode.items:
          result.byJobTitle.add(to(item, JobTitleGap))
    if node.hasKey("diverse_count"):
      result.diverseCount = to(node["diverse_count"], int)
    if node.hasKey("employee_count"):
      result.employeeCount = to(node["employee_count"], int)
    if node.hasKey("female_count"):
      result.femaleCount = to(node["female_count"], int)
    if node.hasKey("male_count"):
      result.maleCount = to(node["male_count"], int)
    if node.hasKey("mean_gap_pct"):
      result.meanGapPct = to(node["mean_gap_pct"], float64)
    if node.hasKey("median_gap_pct"):
      result.medianGapPct = to(node["median_gap_pct"], float64)
    if node.hasKey("quartiles"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["quartiles"]
      if arrayNode.kind == JArray:
        result.quartiles = @[]
        for item in arrayNode.items:
          result.quartiles.add(to(item, QuartileBand))

# Custom JSON serialization for PayGapReport with custom field names
proc `%`*(obj: PayGapReport): JsonNode =
  result = newJObject()
  result["by_job_title"] = %obj.byJobTitle
  result["diverse_count"] = %obj.diverseCount
  result["employee_count"] = %obj.employeeCount
  result["female_count"] = %obj.femaleCount
  result["male_count"] = %obj.maleCount
  result["mean_gap_pct"] = %obj.meanGapPct
  result["median_gap_pct"] = %obj.medianGapPct
  result["quartiles"] = %obj.quartiles

