#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type QuotaOverrideFeatures* = object
  ## 
  erp*: Option[bool]
  fancyReports*: Option[bool]
  taxAutomations*: Option[bool]


# Custom JSON deserialization for QuotaOverrideFeatures with custom field names
proc to*(node: JsonNode, T: typedesc[QuotaOverrideFeatures]): QuotaOverrideFeatures =
  result = QuotaOverrideFeatures()
  if node.kind == JObject:
    if node.hasKey("erp") and node["erp"].kind != JNull:
      result.erp = some(to(node["erp"], typeof(result.erp.get())))
    if node.hasKey("fancy_reports") and node["fancy_reports"].kind != JNull:
      result.fancyReports = some(to(node["fancy_reports"], typeof(result.fancyReports.get())))
    if node.hasKey("tax_automations") and node["tax_automations"].kind != JNull:
      result.taxAutomations = some(to(node["tax_automations"], typeof(result.taxAutomations.get())))

# Custom JSON serialization for QuotaOverrideFeatures with custom field names
proc `%`*(obj: QuotaOverrideFeatures): JsonNode =
  result = newJObject()
  if obj.erp.isSome():
    result["erp"] = %obj.erp.get()
  if obj.fancyReports.isSome():
    result["fancy_reports"] = %obj.fancyReports.get()
  if obj.taxAutomations.isSome():
    result["tax_automations"] = %obj.taxAutomations.get()

