#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_object
import model_plugin_error_one_of
import model_plugin_error_one_of1
import model_plugin_error_one_of2
import model_plugin_error_one_of3
import model_plugin_error_one_of4
import model_plugin_error_one_of5
import model_plugin_error_one_of6

# OneOf type
type PluginErrorKind* {.pure.} = enum
  PluginErrorOneOfVariant
  PluginErrorOneOf1Variant
  PluginErrorOneOf2Variant
  PluginErrorOneOf3Variant
  PluginErrorOneOf4Variant
  PluginErrorOneOf5Variant
  PluginErrorOneOf6Variant

type PluginError* = object
  ## 
  case kind*: PluginErrorKind
  of PluginErrorKind.PluginErrorOneOfVariant:
    PluginError_oneOfValue*: PluginErrorOneOf
  of PluginErrorKind.PluginErrorOneOf1Variant:
    PluginError_oneOf_1Value*: PluginErrorOneOf1
  of PluginErrorKind.PluginErrorOneOf2Variant:
    PluginError_oneOf_2Value*: PluginErrorOneOf2
  of PluginErrorKind.PluginErrorOneOf3Variant:
    PluginError_oneOf_3Value*: PluginErrorOneOf3
  of PluginErrorKind.PluginErrorOneOf4Variant:
    PluginError_oneOf_4Value*: PluginErrorOneOf4
  of PluginErrorKind.PluginErrorOneOf5Variant:
    PluginError_oneOf_5Value*: PluginErrorOneOf5
  of PluginErrorKind.PluginErrorOneOf6Variant:
    PluginError_oneOf_6Value*: PluginErrorOneOf6

proc to*(node: JsonNode, T: typedesc[PluginError]): PluginError =
  ## Custom deserializer for oneOf type - tries each variant
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOfVariant, PluginError_oneOfValue: to(node, PluginErrorOneOf))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf1Variant, PluginError_oneOf_1Value: to(node, PluginErrorOneOf1))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf1: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf2Variant, PluginError_oneOf_2Value: to(node, PluginErrorOneOf2))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf2: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf3Variant, PluginError_oneOf_3Value: to(node, PluginErrorOneOf3))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf3: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf4Variant, PluginError_oneOf_4Value: to(node, PluginErrorOneOf4))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf4: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf5Variant, PluginError_oneOf_5Value: to(node, PluginErrorOneOf5))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf5: ", e.msg
  try:
    return PluginError(kind: PluginErrorKind.PluginErrorOneOf6Variant, PluginError_oneOf_6Value: to(node, PluginErrorOneOf6))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginErrorOneOf6: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PluginError. JSON: " & $node)

