#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SyncSummary* = object
  ## Result of a sync/export run — what the app reports back to the admin UI.
  errorMessage*: Option[string]
  itemsFailed*: Option[int]
  itemsSynced*: Option[int]


# Custom JSON deserialization for SyncSummary with custom field names
proc to*(node: JsonNode, T: typedesc[SyncSummary]): SyncSummary =
  result = SyncSummary()
  if node.kind == JObject:
    if node.hasKey("error_message") and node["error_message"].kind != JNull:
      result.errorMessage = some(to(node["error_message"], typeof(result.errorMessage.get())))
    if node.hasKey("items_failed") and node["items_failed"].kind != JNull:
      result.itemsFailed = some(to(node["items_failed"], typeof(result.itemsFailed.get())))
    if node.hasKey("items_synced") and node["items_synced"].kind != JNull:
      result.itemsSynced = some(to(node["items_synced"], typeof(result.itemsSynced.get())))

# Custom JSON serialization for SyncSummary with custom field names
proc `%`*(obj: SyncSummary): JsonNode =
  result = newJObject()
  if obj.errorMessage.isSome():
    result["error_message"] = %obj.errorMessage.get()
  if obj.itemsFailed.isSome():
    result["items_failed"] = %obj.itemsFailed.get()
  if obj.itemsSynced.isSome():
    result["items_synced"] = %obj.itemsSynced.get()

