#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type EmissionMethod* {.pure.} = enum
  Activity
  Spend
  Supplier

func `%`*(v: EmissionMethod): JsonNode =
  result = case v:
    of EmissionMethod.Activity: %"activity"
    of EmissionMethod.Spend: %"spend"
    of EmissionMethod.Supplier: %"supplier"

func `$`*(v: EmissionMethod): string =
  result = case v:
    of EmissionMethod.Activity: $("activity")
    of EmissionMethod.Spend: $("spend")
    of EmissionMethod.Supplier: $("supplier")

proc to*(node: JsonNode, T: typedesc[EmissionMethod]): EmissionMethod =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum EmissionMethod, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("activity"):
    return EmissionMethod.Activity
  of $("spend"):
    return EmissionMethod.Spend
  of $("supplier"):
    return EmissionMethod.Supplier
  else:
    raise newException(ValueError, "Invalid enum value for EmissionMethod: " & strVal)

