#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_connector_type

type MarketplaceConnection* = object
  ## 
  config*: Option[JsonNode]
  connectionId*: string
  connectorType*: ConnectorType
  createdAt*: string
  isActive*: bool
  label*: string
  lastSyncAt*: Option[string]
  platform*: string
  platformUserId*: Option[string]
  scopes*: Option[string]
  shopDomain*: Option[string]
  shopName*: Option[string]
  syncStatus*: Option[string]
  tenantId*: string
  updatedAt*: Option[string]


# Custom JSON deserialization for MarketplaceConnection with custom field names
proc to*(node: JsonNode, T: typedesc[MarketplaceConnection]): MarketplaceConnection =
  result = MarketplaceConnection()
  if node.kind == JObject:
    if node.hasKey("config") and node["config"].kind != JNull:
      result.config = some(to(node["config"], typeof(result.config.get())))
    if node.hasKey("connection_id"):
      result.connectionId = to(node["connection_id"], string)
    if node.hasKey("connector_type"):
      result.connectorType = to(node["connector_type"], ConnectorType)
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("is_active"):
      result.isActive = to(node["is_active"], bool)
    if node.hasKey("label"):
      result.label = to(node["label"], string)
    if node.hasKey("last_sync_at") and node["last_sync_at"].kind != JNull:
      result.lastSyncAt = some(to(node["last_sync_at"], typeof(result.lastSyncAt.get())))
    if node.hasKey("platform"):
      result.platform = to(node["platform"], string)
    if node.hasKey("platform_user_id") and node["platform_user_id"].kind != JNull:
      result.platformUserId = some(to(node["platform_user_id"], typeof(result.platformUserId.get())))
    if node.hasKey("scopes") and node["scopes"].kind != JNull:
      result.scopes = some(to(node["scopes"], typeof(result.scopes.get())))
    if node.hasKey("shop_domain") and node["shop_domain"].kind != JNull:
      result.shopDomain = some(to(node["shop_domain"], typeof(result.shopDomain.get())))
    if node.hasKey("shop_name") and node["shop_name"].kind != JNull:
      result.shopName = some(to(node["shop_name"], typeof(result.shopName.get())))
    if node.hasKey("sync_status") and node["sync_status"].kind != JNull:
      result.syncStatus = some(to(node["sync_status"], typeof(result.syncStatus.get())))
    if node.hasKey("tenant_id"):
      result.tenantId = to(node["tenant_id"], string)
    if node.hasKey("updated_at") and node["updated_at"].kind != JNull:
      result.updatedAt = some(to(node["updated_at"], typeof(result.updatedAt.get())))

# Custom JSON serialization for MarketplaceConnection with custom field names
proc `%`*(obj: MarketplaceConnection): JsonNode =
  result = newJObject()
  if obj.config.isSome():
    result["config"] = %obj.config.get()
  result["connection_id"] = %obj.connectionId
  result["connector_type"] = %obj.connectorType
  result["created_at"] = %obj.createdAt
  result["is_active"] = %obj.isActive
  result["label"] = %obj.label
  if obj.lastSyncAt.isSome():
    result["last_sync_at"] = %obj.lastSyncAt.get()
  result["platform"] = %obj.platform
  if obj.platformUserId.isSome():
    result["platform_user_id"] = %obj.platformUserId.get()
  if obj.scopes.isSome():
    result["scopes"] = %obj.scopes.get()
  if obj.shopDomain.isSome():
    result["shop_domain"] = %obj.shopDomain.get()
  if obj.shopName.isSome():
    result["shop_name"] = %obj.shopName.get()
  if obj.syncStatus.isSome():
    result["sync_status"] = %obj.syncStatus.get()
  result["tenant_id"] = %obj.tenantId
  if obj.updatedAt.isSome():
    result["updated_at"] = %obj.updatedAt.get()

