#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CurrencyCode* {.pure.} = enum
  ADP
  AED
  AFA
  AFN
  ALL
  AMD
  ANG
  AOA
  AOK
  AOR
  ARS
  ATS
  AUD
  AWG
  AZM
  AZN
  BAD
  BAM
  BBD
  BDT
  BEC
  BEF
  BEL
  BGJ
  BGN
  BHD
  BIF
  BMD
  BND
  BOB
  BOV
  BRB
  BRL
  BRR
  BSD
  BTN
  BWP
  BYB
  BYN
  BYR
  BZD
  CAD
  CDF
  CHE
  CHF
  CHW
  CLF
  CLP
  CNY
  COP
  COU
  CRC
  CSD
  CSK
  CUC
  CUP
  CVE
  CYP
  CZK
  DDM
  DJF
  DKK
  DOP
  DZD
  ECS
  ECV
  EEK
  EGP
  ERN
  ESA
  ESB
  ESP
  ETB
  EUR
  FIM
  FJD
  FKP
  FRF
  GBP
  GEK
  GEL
  GHC
  GHP
  GHS
  GIP
  GMD
  GNF
  GQE
  GRD
  GTQ
  GWE
  GYD
  HKD
  HNL
  HRD
  HTG
  HUF
  IDR
  IEP
  ILS
  INR
  IQD
  IRR
  ISK
  ITL
  JMD
  JOD
  JPY
  KES
  KGS
  KHR
  KMF
  KPW
  KRW
  KWD
  KYD
  KZT
  LAK
  LBP
  LKR
  LRD
  LSL
  LTL
  LUC
  LUF
  LUL
  LVL
  LYD
  MAD
  MDL
  MGA
  MGF
  MKD
  MLF
  MMK
  MNT
  MOP
  MRO
  MRU
  MTL
  MUR
  MVR
  MWK
  MXN
  MXV
  MYR
  MZE
  MZN
  NAD
  NGN
  NIO
  NLG
  NOK
  NPR
  NZD
  OMR
  PAB
  PEN
  PGK
  PHP
  PKR
  PLN
  PLZ
  PTE
  PYG
  QAR
  RHD
  ROK
  RON
  RSD
  RUB
  RUR
  RWF
  SAR
  SBD
  SCR
  SDD
  SDG
  SEK
  SGD
  SHP
  SIT
  SKK
  SLE
  SLL
  SOS
  SRD
  SRG
  SSP
  STD
  STN
  SVC
  SYP
  SZL
  THB
  TJR
  TJS
  TMM
  TMT
  TND
  TOP
  TPE
  TRL
  TRY
  TTD
  TWD
  TZS
  UAH
  UAK
  UGX
  USD
  USN
  USS
  UYI
  UYU
  UYW
  UZS
  VEB
  VED
  VEF
  VES
  VND
  VUV
  WST
  XAD
  XAF
  XAG
  XAU
  XBA
  XBB
  XBC
  XBD
  XCD
  XDR
  XEU
  XOF
  XPD
  XPF
  XPT
  XSU
  XTS
  XUA
  XXX
  YDD
  YER
  YUD
  ZAL
  ZAR
  ZMK
  ZMW
  ZRN
  ZWG
  ZWL
  ZWN
  ZWR

func `%`*(v: CurrencyCode): JsonNode =
  result = case v:
    of CurrencyCode.ADP: %"ADP"
    of CurrencyCode.AED: %"AED"
    of CurrencyCode.AFA: %"AFA"
    of CurrencyCode.AFN: %"AFN"
    of CurrencyCode.ALL: %"ALL"
    of CurrencyCode.AMD: %"AMD"
    of CurrencyCode.ANG: %"ANG"
    of CurrencyCode.AOA: %"AOA"
    of CurrencyCode.AOK: %"AOK"
    of CurrencyCode.AOR: %"AOR"
    of CurrencyCode.ARS: %"ARS"
    of CurrencyCode.ATS: %"ATS"
    of CurrencyCode.AUD: %"AUD"
    of CurrencyCode.AWG: %"AWG"
    of CurrencyCode.AZM: %"AZM"
    of CurrencyCode.AZN: %"AZN"
    of CurrencyCode.BAD: %"BAD"
    of CurrencyCode.BAM: %"BAM"
    of CurrencyCode.BBD: %"BBD"
    of CurrencyCode.BDT: %"BDT"
    of CurrencyCode.BEC: %"BEC"
    of CurrencyCode.BEF: %"BEF"
    of CurrencyCode.BEL: %"BEL"
    of CurrencyCode.BGJ: %"BGJ"
    of CurrencyCode.BGN: %"BGN"
    of CurrencyCode.BHD: %"BHD"
    of CurrencyCode.BIF: %"BIF"
    of CurrencyCode.BMD: %"BMD"
    of CurrencyCode.BND: %"BND"
    of CurrencyCode.BOB: %"BOB"
    of CurrencyCode.BOV: %"BOV"
    of CurrencyCode.BRB: %"BRB"
    of CurrencyCode.BRL: %"BRL"
    of CurrencyCode.BRR: %"BRR"
    of CurrencyCode.BSD: %"BSD"
    of CurrencyCode.BTN: %"BTN"
    of CurrencyCode.BWP: %"BWP"
    of CurrencyCode.BYB: %"BYB"
    of CurrencyCode.BYN: %"BYN"
    of CurrencyCode.BYR: %"BYR"
    of CurrencyCode.BZD: %"BZD"
    of CurrencyCode.CAD: %"CAD"
    of CurrencyCode.CDF: %"CDF"
    of CurrencyCode.CHE: %"CHE"
    of CurrencyCode.CHF: %"CHF"
    of CurrencyCode.CHW: %"CHW"
    of CurrencyCode.CLF: %"CLF"
    of CurrencyCode.CLP: %"CLP"
    of CurrencyCode.CNY: %"CNY"
    of CurrencyCode.COP: %"COP"
    of CurrencyCode.COU: %"COU"
    of CurrencyCode.CRC: %"CRC"
    of CurrencyCode.CSD: %"CSD"
    of CurrencyCode.CSK: %"CSK"
    of CurrencyCode.CUC: %"CUC"
    of CurrencyCode.CUP: %"CUP"
    of CurrencyCode.CVE: %"CVE"
    of CurrencyCode.CYP: %"CYP"
    of CurrencyCode.CZK: %"CZK"
    of CurrencyCode.DDM: %"DDM"
    of CurrencyCode.DJF: %"DJF"
    of CurrencyCode.DKK: %"DKK"
    of CurrencyCode.DOP: %"DOP"
    of CurrencyCode.DZD: %"DZD"
    of CurrencyCode.ECS: %"ECS"
    of CurrencyCode.ECV: %"ECV"
    of CurrencyCode.EEK: %"EEK"
    of CurrencyCode.EGP: %"EGP"
    of CurrencyCode.ERN: %"ERN"
    of CurrencyCode.ESA: %"ESA"
    of CurrencyCode.ESB: %"ESB"
    of CurrencyCode.ESP: %"ESP"
    of CurrencyCode.ETB: %"ETB"
    of CurrencyCode.EUR: %"EUR"
    of CurrencyCode.FIM: %"FIM"
    of CurrencyCode.FJD: %"FJD"
    of CurrencyCode.FKP: %"FKP"
    of CurrencyCode.FRF: %"FRF"
    of CurrencyCode.GBP: %"GBP"
    of CurrencyCode.GEK: %"GEK"
    of CurrencyCode.GEL: %"GEL"
    of CurrencyCode.GHC: %"GHC"
    of CurrencyCode.GHP: %"GHP"
    of CurrencyCode.GHS: %"GHS"
    of CurrencyCode.GIP: %"GIP"
    of CurrencyCode.GMD: %"GMD"
    of CurrencyCode.GNF: %"GNF"
    of CurrencyCode.GQE: %"GQE"
    of CurrencyCode.GRD: %"GRD"
    of CurrencyCode.GTQ: %"GTQ"
    of CurrencyCode.GWE: %"GWE"
    of CurrencyCode.GYD: %"GYD"
    of CurrencyCode.HKD: %"HKD"
    of CurrencyCode.HNL: %"HNL"
    of CurrencyCode.HRD: %"HRD"
    of CurrencyCode.HTG: %"HTG"
    of CurrencyCode.HUF: %"HUF"
    of CurrencyCode.IDR: %"IDR"
    of CurrencyCode.IEP: %"IEP"
    of CurrencyCode.ILS: %"ILS"
    of CurrencyCode.INR: %"INR"
    of CurrencyCode.IQD: %"IQD"
    of CurrencyCode.IRR: %"IRR"
    of CurrencyCode.ISK: %"ISK"
    of CurrencyCode.ITL: %"ITL"
    of CurrencyCode.JMD: %"JMD"
    of CurrencyCode.JOD: %"JOD"
    of CurrencyCode.JPY: %"JPY"
    of CurrencyCode.KES: %"KES"
    of CurrencyCode.KGS: %"KGS"
    of CurrencyCode.KHR: %"KHR"
    of CurrencyCode.KMF: %"KMF"
    of CurrencyCode.KPW: %"KPW"
    of CurrencyCode.KRW: %"KRW"
    of CurrencyCode.KWD: %"KWD"
    of CurrencyCode.KYD: %"KYD"
    of CurrencyCode.KZT: %"KZT"
    of CurrencyCode.LAK: %"LAK"
    of CurrencyCode.LBP: %"LBP"
    of CurrencyCode.LKR: %"LKR"
    of CurrencyCode.LRD: %"LRD"
    of CurrencyCode.LSL: %"LSL"
    of CurrencyCode.LTL: %"LTL"
    of CurrencyCode.LUC: %"LUC"
    of CurrencyCode.LUF: %"LUF"
    of CurrencyCode.LUL: %"LUL"
    of CurrencyCode.LVL: %"LVL"
    of CurrencyCode.LYD: %"LYD"
    of CurrencyCode.MAD: %"MAD"
    of CurrencyCode.MDL: %"MDL"
    of CurrencyCode.MGA: %"MGA"
    of CurrencyCode.MGF: %"MGF"
    of CurrencyCode.MKD: %"MKD"
    of CurrencyCode.MLF: %"MLF"
    of CurrencyCode.MMK: %"MMK"
    of CurrencyCode.MNT: %"MNT"
    of CurrencyCode.MOP: %"MOP"
    of CurrencyCode.MRO: %"MRO"
    of CurrencyCode.MRU: %"MRU"
    of CurrencyCode.MTL: %"MTL"
    of CurrencyCode.MUR: %"MUR"
    of CurrencyCode.MVR: %"MVR"
    of CurrencyCode.MWK: %"MWK"
    of CurrencyCode.MXN: %"MXN"
    of CurrencyCode.MXV: %"MXV"
    of CurrencyCode.MYR: %"MYR"
    of CurrencyCode.MZE: %"MZE"
    of CurrencyCode.MZN: %"MZN"
    of CurrencyCode.NAD: %"NAD"
    of CurrencyCode.NGN: %"NGN"
    of CurrencyCode.NIO: %"NIO"
    of CurrencyCode.NLG: %"NLG"
    of CurrencyCode.NOK: %"NOK"
    of CurrencyCode.NPR: %"NPR"
    of CurrencyCode.NZD: %"NZD"
    of CurrencyCode.OMR: %"OMR"
    of CurrencyCode.PAB: %"PAB"
    of CurrencyCode.PEN: %"PEN"
    of CurrencyCode.PGK: %"PGK"
    of CurrencyCode.PHP: %"PHP"
    of CurrencyCode.PKR: %"PKR"
    of CurrencyCode.PLN: %"PLN"
    of CurrencyCode.PLZ: %"PLZ"
    of CurrencyCode.PTE: %"PTE"
    of CurrencyCode.PYG: %"PYG"
    of CurrencyCode.QAR: %"QAR"
    of CurrencyCode.RHD: %"RHD"
    of CurrencyCode.ROK: %"ROK"
    of CurrencyCode.RON: %"RON"
    of CurrencyCode.RSD: %"RSD"
    of CurrencyCode.RUB: %"RUB"
    of CurrencyCode.RUR: %"RUR"
    of CurrencyCode.RWF: %"RWF"
    of CurrencyCode.SAR: %"SAR"
    of CurrencyCode.SBD: %"SBD"
    of CurrencyCode.SCR: %"SCR"
    of CurrencyCode.SDD: %"SDD"
    of CurrencyCode.SDG: %"SDG"
    of CurrencyCode.SEK: %"SEK"
    of CurrencyCode.SGD: %"SGD"
    of CurrencyCode.SHP: %"SHP"
    of CurrencyCode.SIT: %"SIT"
    of CurrencyCode.SKK: %"SKK"
    of CurrencyCode.SLE: %"SLE"
    of CurrencyCode.SLL: %"SLL"
    of CurrencyCode.SOS: %"SOS"
    of CurrencyCode.SRD: %"SRD"
    of CurrencyCode.SRG: %"SRG"
    of CurrencyCode.SSP: %"SSP"
    of CurrencyCode.STD: %"STD"
    of CurrencyCode.STN: %"STN"
    of CurrencyCode.SVC: %"SVC"
    of CurrencyCode.SYP: %"SYP"
    of CurrencyCode.SZL: %"SZL"
    of CurrencyCode.THB: %"THB"
    of CurrencyCode.TJR: %"TJR"
    of CurrencyCode.TJS: %"TJS"
    of CurrencyCode.TMM: %"TMM"
    of CurrencyCode.TMT: %"TMT"
    of CurrencyCode.TND: %"TND"
    of CurrencyCode.TOP: %"TOP"
    of CurrencyCode.TPE: %"TPE"
    of CurrencyCode.TRL: %"TRL"
    of CurrencyCode.TRY: %"TRY"
    of CurrencyCode.TTD: %"TTD"
    of CurrencyCode.TWD: %"TWD"
    of CurrencyCode.TZS: %"TZS"
    of CurrencyCode.UAH: %"UAH"
    of CurrencyCode.UAK: %"UAK"
    of CurrencyCode.UGX: %"UGX"
    of CurrencyCode.USD: %"USD"
    of CurrencyCode.USN: %"USN"
    of CurrencyCode.USS: %"USS"
    of CurrencyCode.UYI: %"UYI"
    of CurrencyCode.UYU: %"UYU"
    of CurrencyCode.UYW: %"UYW"
    of CurrencyCode.UZS: %"UZS"
    of CurrencyCode.VEB: %"VEB"
    of CurrencyCode.VED: %"VED"
    of CurrencyCode.VEF: %"VEF"
    of CurrencyCode.VES: %"VES"
    of CurrencyCode.VND: %"VND"
    of CurrencyCode.VUV: %"VUV"
    of CurrencyCode.WST: %"WST"
    of CurrencyCode.XAD: %"XAD"
    of CurrencyCode.XAF: %"XAF"
    of CurrencyCode.XAG: %"XAG"
    of CurrencyCode.XAU: %"XAU"
    of CurrencyCode.XBA: %"XBA"
    of CurrencyCode.XBB: %"XBB"
    of CurrencyCode.XBC: %"XBC"
    of CurrencyCode.XBD: %"XBD"
    of CurrencyCode.XCD: %"XCD"
    of CurrencyCode.XDR: %"XDR"
    of CurrencyCode.XEU: %"XEU"
    of CurrencyCode.XOF: %"XOF"
    of CurrencyCode.XPD: %"XPD"
    of CurrencyCode.XPF: %"XPF"
    of CurrencyCode.XPT: %"XPT"
    of CurrencyCode.XSU: %"XSU"
    of CurrencyCode.XTS: %"XTS"
    of CurrencyCode.XUA: %"XUA"
    of CurrencyCode.XXX: %"XXX"
    of CurrencyCode.YDD: %"YDD"
    of CurrencyCode.YER: %"YER"
    of CurrencyCode.YUD: %"YUD"
    of CurrencyCode.ZAL: %"ZAL"
    of CurrencyCode.ZAR: %"ZAR"
    of CurrencyCode.ZMK: %"ZMK"
    of CurrencyCode.ZMW: %"ZMW"
    of CurrencyCode.ZRN: %"ZRN"
    of CurrencyCode.ZWG: %"ZWG"
    of CurrencyCode.ZWL: %"ZWL"
    of CurrencyCode.ZWN: %"ZWN"
    of CurrencyCode.ZWR: %"ZWR"

func `$`*(v: CurrencyCode): string =
  result = case v:
    of CurrencyCode.ADP: $("ADP")
    of CurrencyCode.AED: $("AED")
    of CurrencyCode.AFA: $("AFA")
    of CurrencyCode.AFN: $("AFN")
    of CurrencyCode.ALL: $("ALL")
    of CurrencyCode.AMD: $("AMD")
    of CurrencyCode.ANG: $("ANG")
    of CurrencyCode.AOA: $("AOA")
    of CurrencyCode.AOK: $("AOK")
    of CurrencyCode.AOR: $("AOR")
    of CurrencyCode.ARS: $("ARS")
    of CurrencyCode.ATS: $("ATS")
    of CurrencyCode.AUD: $("AUD")
    of CurrencyCode.AWG: $("AWG")
    of CurrencyCode.AZM: $("AZM")
    of CurrencyCode.AZN: $("AZN")
    of CurrencyCode.BAD: $("BAD")
    of CurrencyCode.BAM: $("BAM")
    of CurrencyCode.BBD: $("BBD")
    of CurrencyCode.BDT: $("BDT")
    of CurrencyCode.BEC: $("BEC")
    of CurrencyCode.BEF: $("BEF")
    of CurrencyCode.BEL: $("BEL")
    of CurrencyCode.BGJ: $("BGJ")
    of CurrencyCode.BGN: $("BGN")
    of CurrencyCode.BHD: $("BHD")
    of CurrencyCode.BIF: $("BIF")
    of CurrencyCode.BMD: $("BMD")
    of CurrencyCode.BND: $("BND")
    of CurrencyCode.BOB: $("BOB")
    of CurrencyCode.BOV: $("BOV")
    of CurrencyCode.BRB: $("BRB")
    of CurrencyCode.BRL: $("BRL")
    of CurrencyCode.BRR: $("BRR")
    of CurrencyCode.BSD: $("BSD")
    of CurrencyCode.BTN: $("BTN")
    of CurrencyCode.BWP: $("BWP")
    of CurrencyCode.BYB: $("BYB")
    of CurrencyCode.BYN: $("BYN")
    of CurrencyCode.BYR: $("BYR")
    of CurrencyCode.BZD: $("BZD")
    of CurrencyCode.CAD: $("CAD")
    of CurrencyCode.CDF: $("CDF")
    of CurrencyCode.CHE: $("CHE")
    of CurrencyCode.CHF: $("CHF")
    of CurrencyCode.CHW: $("CHW")
    of CurrencyCode.CLF: $("CLF")
    of CurrencyCode.CLP: $("CLP")
    of CurrencyCode.CNY: $("CNY")
    of CurrencyCode.COP: $("COP")
    of CurrencyCode.COU: $("COU")
    of CurrencyCode.CRC: $("CRC")
    of CurrencyCode.CSD: $("CSD")
    of CurrencyCode.CSK: $("CSK")
    of CurrencyCode.CUC: $("CUC")
    of CurrencyCode.CUP: $("CUP")
    of CurrencyCode.CVE: $("CVE")
    of CurrencyCode.CYP: $("CYP")
    of CurrencyCode.CZK: $("CZK")
    of CurrencyCode.DDM: $("DDM")
    of CurrencyCode.DJF: $("DJF")
    of CurrencyCode.DKK: $("DKK")
    of CurrencyCode.DOP: $("DOP")
    of CurrencyCode.DZD: $("DZD")
    of CurrencyCode.ECS: $("ECS")
    of CurrencyCode.ECV: $("ECV")
    of CurrencyCode.EEK: $("EEK")
    of CurrencyCode.EGP: $("EGP")
    of CurrencyCode.ERN: $("ERN")
    of CurrencyCode.ESA: $("ESA")
    of CurrencyCode.ESB: $("ESB")
    of CurrencyCode.ESP: $("ESP")
    of CurrencyCode.ETB: $("ETB")
    of CurrencyCode.EUR: $("EUR")
    of CurrencyCode.FIM: $("FIM")
    of CurrencyCode.FJD: $("FJD")
    of CurrencyCode.FKP: $("FKP")
    of CurrencyCode.FRF: $("FRF")
    of CurrencyCode.GBP: $("GBP")
    of CurrencyCode.GEK: $("GEK")
    of CurrencyCode.GEL: $("GEL")
    of CurrencyCode.GHC: $("GHC")
    of CurrencyCode.GHP: $("GHP")
    of CurrencyCode.GHS: $("GHS")
    of CurrencyCode.GIP: $("GIP")
    of CurrencyCode.GMD: $("GMD")
    of CurrencyCode.GNF: $("GNF")
    of CurrencyCode.GQE: $("GQE")
    of CurrencyCode.GRD: $("GRD")
    of CurrencyCode.GTQ: $("GTQ")
    of CurrencyCode.GWE: $("GWE")
    of CurrencyCode.GYD: $("GYD")
    of CurrencyCode.HKD: $("HKD")
    of CurrencyCode.HNL: $("HNL")
    of CurrencyCode.HRD: $("HRD")
    of CurrencyCode.HTG: $("HTG")
    of CurrencyCode.HUF: $("HUF")
    of CurrencyCode.IDR: $("IDR")
    of CurrencyCode.IEP: $("IEP")
    of CurrencyCode.ILS: $("ILS")
    of CurrencyCode.INR: $("INR")
    of CurrencyCode.IQD: $("IQD")
    of CurrencyCode.IRR: $("IRR")
    of CurrencyCode.ISK: $("ISK")
    of CurrencyCode.ITL: $("ITL")
    of CurrencyCode.JMD: $("JMD")
    of CurrencyCode.JOD: $("JOD")
    of CurrencyCode.JPY: $("JPY")
    of CurrencyCode.KES: $("KES")
    of CurrencyCode.KGS: $("KGS")
    of CurrencyCode.KHR: $("KHR")
    of CurrencyCode.KMF: $("KMF")
    of CurrencyCode.KPW: $("KPW")
    of CurrencyCode.KRW: $("KRW")
    of CurrencyCode.KWD: $("KWD")
    of CurrencyCode.KYD: $("KYD")
    of CurrencyCode.KZT: $("KZT")
    of CurrencyCode.LAK: $("LAK")
    of CurrencyCode.LBP: $("LBP")
    of CurrencyCode.LKR: $("LKR")
    of CurrencyCode.LRD: $("LRD")
    of CurrencyCode.LSL: $("LSL")
    of CurrencyCode.LTL: $("LTL")
    of CurrencyCode.LUC: $("LUC")
    of CurrencyCode.LUF: $("LUF")
    of CurrencyCode.LUL: $("LUL")
    of CurrencyCode.LVL: $("LVL")
    of CurrencyCode.LYD: $("LYD")
    of CurrencyCode.MAD: $("MAD")
    of CurrencyCode.MDL: $("MDL")
    of CurrencyCode.MGA: $("MGA")
    of CurrencyCode.MGF: $("MGF")
    of CurrencyCode.MKD: $("MKD")
    of CurrencyCode.MLF: $("MLF")
    of CurrencyCode.MMK: $("MMK")
    of CurrencyCode.MNT: $("MNT")
    of CurrencyCode.MOP: $("MOP")
    of CurrencyCode.MRO: $("MRO")
    of CurrencyCode.MRU: $("MRU")
    of CurrencyCode.MTL: $("MTL")
    of CurrencyCode.MUR: $("MUR")
    of CurrencyCode.MVR: $("MVR")
    of CurrencyCode.MWK: $("MWK")
    of CurrencyCode.MXN: $("MXN")
    of CurrencyCode.MXV: $("MXV")
    of CurrencyCode.MYR: $("MYR")
    of CurrencyCode.MZE: $("MZE")
    of CurrencyCode.MZN: $("MZN")
    of CurrencyCode.NAD: $("NAD")
    of CurrencyCode.NGN: $("NGN")
    of CurrencyCode.NIO: $("NIO")
    of CurrencyCode.NLG: $("NLG")
    of CurrencyCode.NOK: $("NOK")
    of CurrencyCode.NPR: $("NPR")
    of CurrencyCode.NZD: $("NZD")
    of CurrencyCode.OMR: $("OMR")
    of CurrencyCode.PAB: $("PAB")
    of CurrencyCode.PEN: $("PEN")
    of CurrencyCode.PGK: $("PGK")
    of CurrencyCode.PHP: $("PHP")
    of CurrencyCode.PKR: $("PKR")
    of CurrencyCode.PLN: $("PLN")
    of CurrencyCode.PLZ: $("PLZ")
    of CurrencyCode.PTE: $("PTE")
    of CurrencyCode.PYG: $("PYG")
    of CurrencyCode.QAR: $("QAR")
    of CurrencyCode.RHD: $("RHD")
    of CurrencyCode.ROK: $("ROK")
    of CurrencyCode.RON: $("RON")
    of CurrencyCode.RSD: $("RSD")
    of CurrencyCode.RUB: $("RUB")
    of CurrencyCode.RUR: $("RUR")
    of CurrencyCode.RWF: $("RWF")
    of CurrencyCode.SAR: $("SAR")
    of CurrencyCode.SBD: $("SBD")
    of CurrencyCode.SCR: $("SCR")
    of CurrencyCode.SDD: $("SDD")
    of CurrencyCode.SDG: $("SDG")
    of CurrencyCode.SEK: $("SEK")
    of CurrencyCode.SGD: $("SGD")
    of CurrencyCode.SHP: $("SHP")
    of CurrencyCode.SIT: $("SIT")
    of CurrencyCode.SKK: $("SKK")
    of CurrencyCode.SLE: $("SLE")
    of CurrencyCode.SLL: $("SLL")
    of CurrencyCode.SOS: $("SOS")
    of CurrencyCode.SRD: $("SRD")
    of CurrencyCode.SRG: $("SRG")
    of CurrencyCode.SSP: $("SSP")
    of CurrencyCode.STD: $("STD")
    of CurrencyCode.STN: $("STN")
    of CurrencyCode.SVC: $("SVC")
    of CurrencyCode.SYP: $("SYP")
    of CurrencyCode.SZL: $("SZL")
    of CurrencyCode.THB: $("THB")
    of CurrencyCode.TJR: $("TJR")
    of CurrencyCode.TJS: $("TJS")
    of CurrencyCode.TMM: $("TMM")
    of CurrencyCode.TMT: $("TMT")
    of CurrencyCode.TND: $("TND")
    of CurrencyCode.TOP: $("TOP")
    of CurrencyCode.TPE: $("TPE")
    of CurrencyCode.TRL: $("TRL")
    of CurrencyCode.TRY: $("TRY")
    of CurrencyCode.TTD: $("TTD")
    of CurrencyCode.TWD: $("TWD")
    of CurrencyCode.TZS: $("TZS")
    of CurrencyCode.UAH: $("UAH")
    of CurrencyCode.UAK: $("UAK")
    of CurrencyCode.UGX: $("UGX")
    of CurrencyCode.USD: $("USD")
    of CurrencyCode.USN: $("USN")
    of CurrencyCode.USS: $("USS")
    of CurrencyCode.UYI: $("UYI")
    of CurrencyCode.UYU: $("UYU")
    of CurrencyCode.UYW: $("UYW")
    of CurrencyCode.UZS: $("UZS")
    of CurrencyCode.VEB: $("VEB")
    of CurrencyCode.VED: $("VED")
    of CurrencyCode.VEF: $("VEF")
    of CurrencyCode.VES: $("VES")
    of CurrencyCode.VND: $("VND")
    of CurrencyCode.VUV: $("VUV")
    of CurrencyCode.WST: $("WST")
    of CurrencyCode.XAD: $("XAD")
    of CurrencyCode.XAF: $("XAF")
    of CurrencyCode.XAG: $("XAG")
    of CurrencyCode.XAU: $("XAU")
    of CurrencyCode.XBA: $("XBA")
    of CurrencyCode.XBB: $("XBB")
    of CurrencyCode.XBC: $("XBC")
    of CurrencyCode.XBD: $("XBD")
    of CurrencyCode.XCD: $("XCD")
    of CurrencyCode.XDR: $("XDR")
    of CurrencyCode.XEU: $("XEU")
    of CurrencyCode.XOF: $("XOF")
    of CurrencyCode.XPD: $("XPD")
    of CurrencyCode.XPF: $("XPF")
    of CurrencyCode.XPT: $("XPT")
    of CurrencyCode.XSU: $("XSU")
    of CurrencyCode.XTS: $("XTS")
    of CurrencyCode.XUA: $("XUA")
    of CurrencyCode.XXX: $("XXX")
    of CurrencyCode.YDD: $("YDD")
    of CurrencyCode.YER: $("YER")
    of CurrencyCode.YUD: $("YUD")
    of CurrencyCode.ZAL: $("ZAL")
    of CurrencyCode.ZAR: $("ZAR")
    of CurrencyCode.ZMK: $("ZMK")
    of CurrencyCode.ZMW: $("ZMW")
    of CurrencyCode.ZRN: $("ZRN")
    of CurrencyCode.ZWG: $("ZWG")
    of CurrencyCode.ZWL: $("ZWL")
    of CurrencyCode.ZWN: $("ZWN")
    of CurrencyCode.ZWR: $("ZWR")

proc to*(node: JsonNode, T: typedesc[CurrencyCode]): CurrencyCode =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum CurrencyCode, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("ADP"):
    return CurrencyCode.ADP
  of $("AED"):
    return CurrencyCode.AED
  of $("AFA"):
    return CurrencyCode.AFA
  of $("AFN"):
    return CurrencyCode.AFN
  of $("ALL"):
    return CurrencyCode.ALL
  of $("AMD"):
    return CurrencyCode.AMD
  of $("ANG"):
    return CurrencyCode.ANG
  of $("AOA"):
    return CurrencyCode.AOA
  of $("AOK"):
    return CurrencyCode.AOK
  of $("AOR"):
    return CurrencyCode.AOR
  of $("ARS"):
    return CurrencyCode.ARS
  of $("ATS"):
    return CurrencyCode.ATS
  of $("AUD"):
    return CurrencyCode.AUD
  of $("AWG"):
    return CurrencyCode.AWG
  of $("AZM"):
    return CurrencyCode.AZM
  of $("AZN"):
    return CurrencyCode.AZN
  of $("BAD"):
    return CurrencyCode.BAD
  of $("BAM"):
    return CurrencyCode.BAM
  of $("BBD"):
    return CurrencyCode.BBD
  of $("BDT"):
    return CurrencyCode.BDT
  of $("BEC"):
    return CurrencyCode.BEC
  of $("BEF"):
    return CurrencyCode.BEF
  of $("BEL"):
    return CurrencyCode.BEL
  of $("BGJ"):
    return CurrencyCode.BGJ
  of $("BGN"):
    return CurrencyCode.BGN
  of $("BHD"):
    return CurrencyCode.BHD
  of $("BIF"):
    return CurrencyCode.BIF
  of $("BMD"):
    return CurrencyCode.BMD
  of $("BND"):
    return CurrencyCode.BND
  of $("BOB"):
    return CurrencyCode.BOB
  of $("BOV"):
    return CurrencyCode.BOV
  of $("BRB"):
    return CurrencyCode.BRB
  of $("BRL"):
    return CurrencyCode.BRL
  of $("BRR"):
    return CurrencyCode.BRR
  of $("BSD"):
    return CurrencyCode.BSD
  of $("BTN"):
    return CurrencyCode.BTN
  of $("BWP"):
    return CurrencyCode.BWP
  of $("BYB"):
    return CurrencyCode.BYB
  of $("BYN"):
    return CurrencyCode.BYN
  of $("BYR"):
    return CurrencyCode.BYR
  of $("BZD"):
    return CurrencyCode.BZD
  of $("CAD"):
    return CurrencyCode.CAD
  of $("CDF"):
    return CurrencyCode.CDF
  of $("CHE"):
    return CurrencyCode.CHE
  of $("CHF"):
    return CurrencyCode.CHF
  of $("CHW"):
    return CurrencyCode.CHW
  of $("CLF"):
    return CurrencyCode.CLF
  of $("CLP"):
    return CurrencyCode.CLP
  of $("CNY"):
    return CurrencyCode.CNY
  of $("COP"):
    return CurrencyCode.COP
  of $("COU"):
    return CurrencyCode.COU
  of $("CRC"):
    return CurrencyCode.CRC
  of $("CSD"):
    return CurrencyCode.CSD
  of $("CSK"):
    return CurrencyCode.CSK
  of $("CUC"):
    return CurrencyCode.CUC
  of $("CUP"):
    return CurrencyCode.CUP
  of $("CVE"):
    return CurrencyCode.CVE
  of $("CYP"):
    return CurrencyCode.CYP
  of $("CZK"):
    return CurrencyCode.CZK
  of $("DDM"):
    return CurrencyCode.DDM
  of $("DJF"):
    return CurrencyCode.DJF
  of $("DKK"):
    return CurrencyCode.DKK
  of $("DOP"):
    return CurrencyCode.DOP
  of $("DZD"):
    return CurrencyCode.DZD
  of $("ECS"):
    return CurrencyCode.ECS
  of $("ECV"):
    return CurrencyCode.ECV
  of $("EEK"):
    return CurrencyCode.EEK
  of $("EGP"):
    return CurrencyCode.EGP
  of $("ERN"):
    return CurrencyCode.ERN
  of $("ESA"):
    return CurrencyCode.ESA
  of $("ESB"):
    return CurrencyCode.ESB
  of $("ESP"):
    return CurrencyCode.ESP
  of $("ETB"):
    return CurrencyCode.ETB
  of $("EUR"):
    return CurrencyCode.EUR
  of $("FIM"):
    return CurrencyCode.FIM
  of $("FJD"):
    return CurrencyCode.FJD
  of $("FKP"):
    return CurrencyCode.FKP
  of $("FRF"):
    return CurrencyCode.FRF
  of $("GBP"):
    return CurrencyCode.GBP
  of $("GEK"):
    return CurrencyCode.GEK
  of $("GEL"):
    return CurrencyCode.GEL
  of $("GHC"):
    return CurrencyCode.GHC
  of $("GHP"):
    return CurrencyCode.GHP
  of $("GHS"):
    return CurrencyCode.GHS
  of $("GIP"):
    return CurrencyCode.GIP
  of $("GMD"):
    return CurrencyCode.GMD
  of $("GNF"):
    return CurrencyCode.GNF
  of $("GQE"):
    return CurrencyCode.GQE
  of $("GRD"):
    return CurrencyCode.GRD
  of $("GTQ"):
    return CurrencyCode.GTQ
  of $("GWE"):
    return CurrencyCode.GWE
  of $("GYD"):
    return CurrencyCode.GYD
  of $("HKD"):
    return CurrencyCode.HKD
  of $("HNL"):
    return CurrencyCode.HNL
  of $("HRD"):
    return CurrencyCode.HRD
  of $("HTG"):
    return CurrencyCode.HTG
  of $("HUF"):
    return CurrencyCode.HUF
  of $("IDR"):
    return CurrencyCode.IDR
  of $("IEP"):
    return CurrencyCode.IEP
  of $("ILS"):
    return CurrencyCode.ILS
  of $("INR"):
    return CurrencyCode.INR
  of $("IQD"):
    return CurrencyCode.IQD
  of $("IRR"):
    return CurrencyCode.IRR
  of $("ISK"):
    return CurrencyCode.ISK
  of $("ITL"):
    return CurrencyCode.ITL
  of $("JMD"):
    return CurrencyCode.JMD
  of $("JOD"):
    return CurrencyCode.JOD
  of $("JPY"):
    return CurrencyCode.JPY
  of $("KES"):
    return CurrencyCode.KES
  of $("KGS"):
    return CurrencyCode.KGS
  of $("KHR"):
    return CurrencyCode.KHR
  of $("KMF"):
    return CurrencyCode.KMF
  of $("KPW"):
    return CurrencyCode.KPW
  of $("KRW"):
    return CurrencyCode.KRW
  of $("KWD"):
    return CurrencyCode.KWD
  of $("KYD"):
    return CurrencyCode.KYD
  of $("KZT"):
    return CurrencyCode.KZT
  of $("LAK"):
    return CurrencyCode.LAK
  of $("LBP"):
    return CurrencyCode.LBP
  of $("LKR"):
    return CurrencyCode.LKR
  of $("LRD"):
    return CurrencyCode.LRD
  of $("LSL"):
    return CurrencyCode.LSL
  of $("LTL"):
    return CurrencyCode.LTL
  of $("LUC"):
    return CurrencyCode.LUC
  of $("LUF"):
    return CurrencyCode.LUF
  of $("LUL"):
    return CurrencyCode.LUL
  of $("LVL"):
    return CurrencyCode.LVL
  of $("LYD"):
    return CurrencyCode.LYD
  of $("MAD"):
    return CurrencyCode.MAD
  of $("MDL"):
    return CurrencyCode.MDL
  of $("MGA"):
    return CurrencyCode.MGA
  of $("MGF"):
    return CurrencyCode.MGF
  of $("MKD"):
    return CurrencyCode.MKD
  of $("MLF"):
    return CurrencyCode.MLF
  of $("MMK"):
    return CurrencyCode.MMK
  of $("MNT"):
    return CurrencyCode.MNT
  of $("MOP"):
    return CurrencyCode.MOP
  of $("MRO"):
    return CurrencyCode.MRO
  of $("MRU"):
    return CurrencyCode.MRU
  of $("MTL"):
    return CurrencyCode.MTL
  of $("MUR"):
    return CurrencyCode.MUR
  of $("MVR"):
    return CurrencyCode.MVR
  of $("MWK"):
    return CurrencyCode.MWK
  of $("MXN"):
    return CurrencyCode.MXN
  of $("MXV"):
    return CurrencyCode.MXV
  of $("MYR"):
    return CurrencyCode.MYR
  of $("MZE"):
    return CurrencyCode.MZE
  of $("MZN"):
    return CurrencyCode.MZN
  of $("NAD"):
    return CurrencyCode.NAD
  of $("NGN"):
    return CurrencyCode.NGN
  of $("NIO"):
    return CurrencyCode.NIO
  of $("NLG"):
    return CurrencyCode.NLG
  of $("NOK"):
    return CurrencyCode.NOK
  of $("NPR"):
    return CurrencyCode.NPR
  of $("NZD"):
    return CurrencyCode.NZD
  of $("OMR"):
    return CurrencyCode.OMR
  of $("PAB"):
    return CurrencyCode.PAB
  of $("PEN"):
    return CurrencyCode.PEN
  of $("PGK"):
    return CurrencyCode.PGK
  of $("PHP"):
    return CurrencyCode.PHP
  of $("PKR"):
    return CurrencyCode.PKR
  of $("PLN"):
    return CurrencyCode.PLN
  of $("PLZ"):
    return CurrencyCode.PLZ
  of $("PTE"):
    return CurrencyCode.PTE
  of $("PYG"):
    return CurrencyCode.PYG
  of $("QAR"):
    return CurrencyCode.QAR
  of $("RHD"):
    return CurrencyCode.RHD
  of $("ROK"):
    return CurrencyCode.ROK
  of $("RON"):
    return CurrencyCode.RON
  of $("RSD"):
    return CurrencyCode.RSD
  of $("RUB"):
    return CurrencyCode.RUB
  of $("RUR"):
    return CurrencyCode.RUR
  of $("RWF"):
    return CurrencyCode.RWF
  of $("SAR"):
    return CurrencyCode.SAR
  of $("SBD"):
    return CurrencyCode.SBD
  of $("SCR"):
    return CurrencyCode.SCR
  of $("SDD"):
    return CurrencyCode.SDD
  of $("SDG"):
    return CurrencyCode.SDG
  of $("SEK"):
    return CurrencyCode.SEK
  of $("SGD"):
    return CurrencyCode.SGD
  of $("SHP"):
    return CurrencyCode.SHP
  of $("SIT"):
    return CurrencyCode.SIT
  of $("SKK"):
    return CurrencyCode.SKK
  of $("SLE"):
    return CurrencyCode.SLE
  of $("SLL"):
    return CurrencyCode.SLL
  of $("SOS"):
    return CurrencyCode.SOS
  of $("SRD"):
    return CurrencyCode.SRD
  of $("SRG"):
    return CurrencyCode.SRG
  of $("SSP"):
    return CurrencyCode.SSP
  of $("STD"):
    return CurrencyCode.STD
  of $("STN"):
    return CurrencyCode.STN
  of $("SVC"):
    return CurrencyCode.SVC
  of $("SYP"):
    return CurrencyCode.SYP
  of $("SZL"):
    return CurrencyCode.SZL
  of $("THB"):
    return CurrencyCode.THB
  of $("TJR"):
    return CurrencyCode.TJR
  of $("TJS"):
    return CurrencyCode.TJS
  of $("TMM"):
    return CurrencyCode.TMM
  of $("TMT"):
    return CurrencyCode.TMT
  of $("TND"):
    return CurrencyCode.TND
  of $("TOP"):
    return CurrencyCode.TOP
  of $("TPE"):
    return CurrencyCode.TPE
  of $("TRL"):
    return CurrencyCode.TRL
  of $("TRY"):
    return CurrencyCode.TRY
  of $("TTD"):
    return CurrencyCode.TTD
  of $("TWD"):
    return CurrencyCode.TWD
  of $("TZS"):
    return CurrencyCode.TZS
  of $("UAH"):
    return CurrencyCode.UAH
  of $("UAK"):
    return CurrencyCode.UAK
  of $("UGX"):
    return CurrencyCode.UGX
  of $("USD"):
    return CurrencyCode.USD
  of $("USN"):
    return CurrencyCode.USN
  of $("USS"):
    return CurrencyCode.USS
  of $("UYI"):
    return CurrencyCode.UYI
  of $("UYU"):
    return CurrencyCode.UYU
  of $("UYW"):
    return CurrencyCode.UYW
  of $("UZS"):
    return CurrencyCode.UZS
  of $("VEB"):
    return CurrencyCode.VEB
  of $("VED"):
    return CurrencyCode.VED
  of $("VEF"):
    return CurrencyCode.VEF
  of $("VES"):
    return CurrencyCode.VES
  of $("VND"):
    return CurrencyCode.VND
  of $("VUV"):
    return CurrencyCode.VUV
  of $("WST"):
    return CurrencyCode.WST
  of $("XAD"):
    return CurrencyCode.XAD
  of $("XAF"):
    return CurrencyCode.XAF
  of $("XAG"):
    return CurrencyCode.XAG
  of $("XAU"):
    return CurrencyCode.XAU
  of $("XBA"):
    return CurrencyCode.XBA
  of $("XBB"):
    return CurrencyCode.XBB
  of $("XBC"):
    return CurrencyCode.XBC
  of $("XBD"):
    return CurrencyCode.XBD
  of $("XCD"):
    return CurrencyCode.XCD
  of $("XDR"):
    return CurrencyCode.XDR
  of $("XEU"):
    return CurrencyCode.XEU
  of $("XOF"):
    return CurrencyCode.XOF
  of $("XPD"):
    return CurrencyCode.XPD
  of $("XPF"):
    return CurrencyCode.XPF
  of $("XPT"):
    return CurrencyCode.XPT
  of $("XSU"):
    return CurrencyCode.XSU
  of $("XTS"):
    return CurrencyCode.XTS
  of $("XUA"):
    return CurrencyCode.XUA
  of $("XXX"):
    return CurrencyCode.XXX
  of $("YDD"):
    return CurrencyCode.YDD
  of $("YER"):
    return CurrencyCode.YER
  of $("YUD"):
    return CurrencyCode.YUD
  of $("ZAL"):
    return CurrencyCode.ZAL
  of $("ZAR"):
    return CurrencyCode.ZAR
  of $("ZMK"):
    return CurrencyCode.ZMK
  of $("ZMW"):
    return CurrencyCode.ZMW
  of $("ZRN"):
    return CurrencyCode.ZRN
  of $("ZWG"):
    return CurrencyCode.ZWG
  of $("ZWL"):
    return CurrencyCode.ZWL
  of $("ZWN"):
    return CurrencyCode.ZWN
  of $("ZWR"):
    return CurrencyCode.ZWR
  else:
    raise newException(ValueError, "Invalid enum value for CurrencyCode: " & strVal)

