#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_production_order_status

type ProductionOrder* = object
  ## 
  bomId*: Option[string] ## References the BOM entity.
  components*: Option[JsonNode] ## JSON snapshot of the BOM components at creation time.
  endDate*: Option[string]
  notes*: Option[string]
  orderNumber*: string
  productId*: string ## The finished product to manufacture. References the product entity.
  quantity*: int64 ## Quantity of finished product to produce.
  sourceWarehouseId*: Option[string] ## Warehouse components are consumed from. References the warehouse entity.
  startDate*: Option[string]
  status*: Option[ProductionOrderStatus] ## One of: planned | in_production | completed | cancelled
  targetWarehouseId*: Option[string] ## Warehouse the finished product is added to. References the warehouse entity.

