#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type BWASummary* = object
  ## 
  grossProfit*: string
  netProfit*: string
  openInvoicesCount*: int64
  openInvoicesTotal*: string
  overdueInvoicesCount*: int64
  overdueInvoicesTotal*: string
  profitMargin*: float64


# Custom JSON deserialization for BWASummary with custom field names
proc to*(node: JsonNode, T: typedesc[BWASummary]): BWASummary =
  result = BWASummary()
  if node.kind == JObject:
    if node.hasKey("gross_profit"):
      result.grossProfit = to(node["gross_profit"], string)
    if node.hasKey("net_profit"):
      result.netProfit = to(node["net_profit"], string)
    if node.hasKey("open_invoices_count"):
      result.openInvoicesCount = to(node["open_invoices_count"], int64)
    if node.hasKey("open_invoices_total"):
      result.openInvoicesTotal = to(node["open_invoices_total"], string)
    if node.hasKey("overdue_invoices_count"):
      result.overdueInvoicesCount = to(node["overdue_invoices_count"], int64)
    if node.hasKey("overdue_invoices_total"):
      result.overdueInvoicesTotal = to(node["overdue_invoices_total"], string)
    if node.hasKey("profit_margin"):
      result.profitMargin = to(node["profit_margin"], float64)

# Custom JSON serialization for BWASummary with custom field names
proc `%`*(obj: BWASummary): JsonNode =
  result = newJObject()
  result["gross_profit"] = %obj.grossProfit
  result["net_profit"] = %obj.netProfit
  result["open_invoices_count"] = %obj.openInvoicesCount
  result["open_invoices_total"] = %obj.openInvoicesTotal
  result["overdue_invoices_count"] = %obj.overdueInvoicesCount
  result["overdue_invoices_total"] = %obj.overdueInvoicesTotal
  result["profit_margin"] = %obj.profitMargin

