#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type InstituteType* {.pure.} = enum
  Kein
  Kreditinstitut
  Finanzdienstleistungsinstitut
  Finanzunternehmen
  Versicherung

func `%`*(v: InstituteType): JsonNode =
  result = case v:
    of InstituteType.Kein: %"kein"
    of InstituteType.Kreditinstitut: %"kreditinstitut"
    of InstituteType.Finanzdienstleistungsinstitut: %"finanzdienstleistungsinstitut"
    of InstituteType.Finanzunternehmen: %"finanzunternehmen"
    of InstituteType.Versicherung: %"versicherung"

func `$`*(v: InstituteType): string =
  result = case v:
    of InstituteType.Kein: $("kein")
    of InstituteType.Kreditinstitut: $("kreditinstitut")
    of InstituteType.Finanzdienstleistungsinstitut: $("finanzdienstleistungsinstitut")
    of InstituteType.Finanzunternehmen: $("finanzunternehmen")
    of InstituteType.Versicherung: $("versicherung")

proc to*(node: JsonNode, T: typedesc[InstituteType]): InstituteType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum InstituteType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("kein"):
    return InstituteType.Kein
  of $("kreditinstitut"):
    return InstituteType.Kreditinstitut
  of $("finanzdienstleistungsinstitut"):
    return InstituteType.Finanzdienstleistungsinstitut
  of $("finanzunternehmen"):
    return InstituteType.Finanzunternehmen
  of $("versicherung"):
    return InstituteType.Versicherung
  else:
    raise newException(ValueError, "Invalid enum value for InstituteType: " & strVal)

