#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ProposedAssignment* = object
  ## 
  amountPaid*: string
  confidence*: float64
  customerId*: Option[string]
  invoiceId*: string
  invoiceNumber*: string
  openAmount*: string
  paymentDate*: string
  paymentId*: string
  reason*: string
  reference*: Option[string]


# Custom JSON deserialization for ProposedAssignment with custom field names
proc to*(node: JsonNode, T: typedesc[ProposedAssignment]): ProposedAssignment =
  result = ProposedAssignment()
  if node.kind == JObject:
    if node.hasKey("amount_paid"):
      result.amountPaid = to(node["amount_paid"], string)
    if node.hasKey("confidence"):
      result.confidence = to(node["confidence"], float64)
    if node.hasKey("customer_id") and node["customer_id"].kind != JNull:
      result.customerId = some(to(node["customer_id"], typeof(result.customerId.get())))
    if node.hasKey("invoice_id"):
      result.invoiceId = to(node["invoice_id"], string)
    if node.hasKey("invoice_number"):
      result.invoiceNumber = to(node["invoice_number"], string)
    if node.hasKey("open_amount"):
      result.openAmount = to(node["open_amount"], string)
    if node.hasKey("payment_date"):
      result.paymentDate = to(node["payment_date"], string)
    if node.hasKey("payment_id"):
      result.paymentId = to(node["payment_id"], string)
    if node.hasKey("reason"):
      result.reason = to(node["reason"], string)
    if node.hasKey("reference") and node["reference"].kind != JNull:
      result.reference = some(to(node["reference"], typeof(result.reference.get())))

# Custom JSON serialization for ProposedAssignment with custom field names
proc `%`*(obj: ProposedAssignment): JsonNode =
  result = newJObject()
  result["amount_paid"] = %obj.amountPaid
  result["confidence"] = %obj.confidence
  if obj.customerId.isSome():
    result["customer_id"] = %obj.customerId.get()
  result["invoice_id"] = %obj.invoiceId
  result["invoice_number"] = %obj.invoiceNumber
  result["open_amount"] = %obj.openAmount
  result["payment_date"] = %obj.paymentDate
  result["payment_id"] = %obj.paymentId
  result["reason"] = %obj.reason
  if obj.reference.isSome():
    result["reference"] = %obj.reference.get()

