#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PrintLabelResponse* = object
  ## 
  labelUrl*: Option[string]
  message*: string
  sscc*: Option[string]
  success*: bool
  trackingNumber*: Option[string]


# Custom JSON deserialization for PrintLabelResponse with custom field names
proc to*(node: JsonNode, T: typedesc[PrintLabelResponse]): PrintLabelResponse =
  result = PrintLabelResponse()
  if node.kind == JObject:
    if node.hasKey("label_url") and node["label_url"].kind != JNull:
      result.labelUrl = some(to(node["label_url"], typeof(result.labelUrl.get())))
    if node.hasKey("message"):
      result.message = to(node["message"], string)
    if node.hasKey("sscc") and node["sscc"].kind != JNull:
      result.sscc = some(to(node["sscc"], typeof(result.sscc.get())))
    if node.hasKey("success"):
      result.success = to(node["success"], bool)
    if node.hasKey("tracking_number") and node["tracking_number"].kind != JNull:
      result.trackingNumber = some(to(node["tracking_number"], typeof(result.trackingNumber.get())))

# Custom JSON serialization for PrintLabelResponse with custom field names
proc `%`*(obj: PrintLabelResponse): JsonNode =
  result = newJObject()
  if obj.labelUrl.isSome():
    result["label_url"] = %obj.labelUrl.get()
  result["message"] = %obj.message
  if obj.sscc.isSome():
    result["sscc"] = %obj.sscc.get()
  result["success"] = %obj.success
  if obj.trackingNumber.isSome():
    result["tracking_number"] = %obj.trackingNumber.get()

