#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PnLItem* = object
  ## 
  account*: string
  accountName*: string
  amount*: string


# Custom JSON deserialization for PnLItem with custom field names
proc to*(node: JsonNode, T: typedesc[PnLItem]): PnLItem =
  result = PnLItem()
  if node.kind == JObject:
    if node.hasKey("account"):
      result.account = to(node["account"], string)
    if node.hasKey("account_name"):
      result.accountName = to(node["account_name"], string)
    if node.hasKey("amount"):
      result.amount = to(node["amount"], string)

# Custom JSON serialization for PnLItem with custom field names
proc `%`*(obj: PnLItem): JsonNode =
  result = newJObject()
  result["account"] = %obj.account
  result["account_name"] = %obj.accountName
  result["amount"] = %obj.amount

