#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_betriebsstaetten_detail

type GezReport* = object
  ## Berechnungsergebnis des Rundfunkbeitrags für ein Unternehmen.
  beitragsfreieKfz*: int64
  beitragspflichtigeKfz*: int64
  betriebsstaetten*: seq[BetriebsstaettenDetail]
  hinweis*: string
  hotelzimmerBeitrag*: string
  jaehrlicherBeitrag*: string
  jahr*: int
  kfzBeitrag*: string
  monatlicherBeitrag*: string
  vierteljaehrlicherBeitrag*: string


# Custom JSON deserialization for GezReport with custom field names
proc to*(node: JsonNode, T: typedesc[GezReport]): GezReport =
  result = GezReport()
  if node.kind == JObject:
    if node.hasKey("beitragsfreie_kfz"):
      result.beitragsfreieKfz = to(node["beitragsfreie_kfz"], int64)
    if node.hasKey("beitragspflichtige_kfz"):
      result.beitragspflichtigeKfz = to(node["beitragspflichtige_kfz"], int64)
    if node.hasKey("betriebsstaetten"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["betriebsstaetten"]
      if arrayNode.kind == JArray:
        result.betriebsstaetten = @[]
        for item in arrayNode.items:
          result.betriebsstaetten.add(to(item, BetriebsstaettenDetail))
    if node.hasKey("hinweis"):
      result.hinweis = to(node["hinweis"], string)
    if node.hasKey("hotelzimmer_beitrag"):
      result.hotelzimmerBeitrag = to(node["hotelzimmer_beitrag"], string)
    if node.hasKey("jaehrlicher_beitrag"):
      result.jaehrlicherBeitrag = to(node["jaehrlicher_beitrag"], string)
    if node.hasKey("jahr"):
      result.jahr = to(node["jahr"], int)
    if node.hasKey("kfz_beitrag"):
      result.kfzBeitrag = to(node["kfz_beitrag"], string)
    if node.hasKey("monatlicher_beitrag"):
      result.monatlicherBeitrag = to(node["monatlicher_beitrag"], string)
    if node.hasKey("vierteljaehrlicher_beitrag"):
      result.vierteljaehrlicherBeitrag = to(node["vierteljaehrlicher_beitrag"], string)

# Custom JSON serialization for GezReport with custom field names
proc `%`*(obj: GezReport): JsonNode =
  result = newJObject()
  result["beitragsfreie_kfz"] = %obj.beitragsfreieKfz
  result["beitragspflichtige_kfz"] = %obj.beitragspflichtigeKfz
  result["betriebsstaetten"] = %obj.betriebsstaetten
  result["hinweis"] = %obj.hinweis
  result["hotelzimmer_beitrag"] = %obj.hotelzimmerBeitrag
  result["jaehrlicher_beitrag"] = %obj.jaehrlicherBeitrag
  result["jahr"] = %obj.jahr
  result["kfz_beitrag"] = %obj.kfzBeitrag
  result["monatlicher_beitrag"] = %obj.monatlicherBeitrag
  result["vierteljaehrlicher_beitrag"] = %obj.vierteljaehrlicherBeitrag

