#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AssignmentStatus* {.pure.} = enum
  Required
  Completed
  Overdue
  Waived

func `%`*(v: AssignmentStatus): JsonNode =
  result = case v:
    of AssignmentStatus.Required: %"required"
    of AssignmentStatus.Completed: %"completed"
    of AssignmentStatus.Overdue: %"overdue"
    of AssignmentStatus.Waived: %"waived"

func `$`*(v: AssignmentStatus): string =
  result = case v:
    of AssignmentStatus.Required: $("required")
    of AssignmentStatus.Completed: $("completed")
    of AssignmentStatus.Overdue: $("overdue")
    of AssignmentStatus.Waived: $("waived")

proc to*(node: JsonNode, T: typedesc[AssignmentStatus]): AssignmentStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum AssignmentStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("required"):
    return AssignmentStatus.Required
  of $("completed"):
    return AssignmentStatus.Completed
  of $("overdue"):
    return AssignmentStatus.Overdue
  of $("waived"):
    return AssignmentStatus.Waived
  else:
    raise newException(ValueError, "Invalid enum value for AssignmentStatus: " & strVal)

