#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_gewinnverwendungs_zeile

type GewinnverwendungsReport* = object
  ## 
  bilanzgewinn*: string ## Bilanzgewinn nach Einstellung (§ 174 AktG, Beschluss der HV).
  gesetzlicheRuecklageBestand*: string
  gesetzlicheRuecklageCap*: string ## Deckel: 10 % des Grundkapitals (§ 150 Abs. 2 AktG).
  gesetzlicheRuecklageNach*: string ## Rücklage nach Einstellung.
  gesetzlicheRuecklageSoll*: string ## Vorgeschlagene Einstellung in die gesetzliche Rücklage (§ 150 Abs. 2 AktG).
  gezeichnetesKapital*: string
  jahresueberschuss*: string
  year*: int
  zeilen*: seq[GewinnverwendungsZeile]


# Custom JSON deserialization for GewinnverwendungsReport with custom field names
proc to*(node: JsonNode, T: typedesc[GewinnverwendungsReport]): GewinnverwendungsReport =
  result = GewinnverwendungsReport()
  if node.kind == JObject:
    if node.hasKey("bilanzgewinn"):
      result.bilanzgewinn = to(node["bilanzgewinn"], string)
    if node.hasKey("gesetzliche_ruecklage_bestand"):
      result.gesetzlicheRuecklageBestand = to(node["gesetzliche_ruecklage_bestand"], string)
    if node.hasKey("gesetzliche_ruecklage_cap"):
      result.gesetzlicheRuecklageCap = to(node["gesetzliche_ruecklage_cap"], string)
    if node.hasKey("gesetzliche_ruecklage_nach"):
      result.gesetzlicheRuecklageNach = to(node["gesetzliche_ruecklage_nach"], string)
    if node.hasKey("gesetzliche_ruecklage_soll"):
      result.gesetzlicheRuecklageSoll = to(node["gesetzliche_ruecklage_soll"], string)
    if node.hasKey("gezeichnetes_kapital"):
      result.gezeichnetesKapital = to(node["gezeichnetes_kapital"], string)
    if node.hasKey("jahresueberschuss"):
      result.jahresueberschuss = to(node["jahresueberschuss"], string)
    if node.hasKey("year"):
      result.year = to(node["year"], int)
    if node.hasKey("zeilen"):
      result.zeilen = to(node["zeilen"], seq[GewinnverwendungsZeile])

# Custom JSON serialization for GewinnverwendungsReport with custom field names
proc `%`*(obj: GewinnverwendungsReport): JsonNode =
  result = newJObject()
  result["bilanzgewinn"] = %obj.bilanzgewinn
  result["gesetzliche_ruecklage_bestand"] = %obj.gesetzlicheRuecklageBestand
  result["gesetzliche_ruecklage_cap"] = %obj.gesetzlicheRuecklageCap
  result["gesetzliche_ruecklage_nach"] = %obj.gesetzlicheRuecklageNach
  result["gesetzliche_ruecklage_soll"] = %obj.gesetzlicheRuecklageSoll
  result["gezeichnetes_kapital"] = %obj.gezeichnetesKapital
  result["jahresueberschuss"] = %obj.jahresueberschuss
  result["year"] = %obj.year
  result["zeilen"] = %obj.zeilen

