#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SupportTicketStatus* {.pure.} = enum
  Open
  AwaitingReply
  Resolved
  Closed

func `%`*(v: SupportTicketStatus): JsonNode =
  result = case v:
    of SupportTicketStatus.Open: %"open"
    of SupportTicketStatus.AwaitingReply: %"awaiting_reply"
    of SupportTicketStatus.Resolved: %"resolved"
    of SupportTicketStatus.Closed: %"closed"

func `$`*(v: SupportTicketStatus): string =
  result = case v:
    of SupportTicketStatus.Open: $("open")
    of SupportTicketStatus.AwaitingReply: $("awaiting_reply")
    of SupportTicketStatus.Resolved: $("resolved")
    of SupportTicketStatus.Closed: $("closed")

proc to*(node: JsonNode, T: typedesc[SupportTicketStatus]): SupportTicketStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SupportTicketStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("open"):
    return SupportTicketStatus.Open
  of $("awaiting_reply"):
    return SupportTicketStatus.AwaitingReply
  of $("resolved"):
    return SupportTicketStatus.Resolved
  of $("closed"):
    return SupportTicketStatus.Closed
  else:
    raise newException(ValueError, "Invalid enum value for SupportTicketStatus: " & strVal)

