#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_return_order_status

type ReturnOrder* = object
  ## 
  customerContactId*: Option[string] ## References the contact entity.
  customerName*: Option[string]
  lineItems*: Option[JsonNode] ## JSON array of `{product_id, name, quantity, condition, restock, batch_number?}`.
  notes*: Option[string]
  orderId*: Option[string] ## References the order entity.
  orderNumber*: Option[string]
  returnNumber*: string
  returnReason*: Option[string]
  status*: ReturnOrderStatus ## One of: requested | received | inspected | restocked | closed
  warehouseId*: Option[string] ## Warehouse into which restockable items are returned. References the warehouse entity.

