#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_inventory_value_point

type CurrentInventoryValue* = object
  ## 
  history*: seq[InventoryValuePoint]
  productCount*: int64
  totalPurchaseValue*: string
  totalSalesValue*: string


# Custom JSON deserialization for CurrentInventoryValue with custom field names
proc to*(node: JsonNode, T: typedesc[CurrentInventoryValue]): CurrentInventoryValue =
  result = CurrentInventoryValue()
  if node.kind == JObject:
    if node.hasKey("history"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["history"]
      if arrayNode.kind == JArray:
        result.history = @[]
        for item in arrayNode.items:
          result.history.add(to(item, InventoryValuePoint))
    if node.hasKey("product_count"):
      result.productCount = to(node["product_count"], int64)
    if node.hasKey("total_purchase_value"):
      result.totalPurchaseValue = to(node["total_purchase_value"], string)
    if node.hasKey("total_sales_value"):
      result.totalSalesValue = to(node["total_sales_value"], string)

# Custom JSON serialization for CurrentInventoryValue with custom field names
proc `%`*(obj: CurrentInventoryValue): JsonNode =
  result = newJObject()
  result["history"] = %obj.history
  result["product_count"] = %obj.productCount
  result["total_purchase_value"] = %obj.totalPurchaseValue
  result["total_sales_value"] = %obj.totalSalesValue

