#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type TenantUser* = object
  ## 
  email*: string
  emailVerified*: bool
  isActive*: bool
  joinedAt*: string
  lastLogin*: Option[string]
  name*: string
  permissions*: seq[string]
  role*: string
  userId*: string


# Custom JSON deserialization for TenantUser with custom field names
proc to*(node: JsonNode, T: typedesc[TenantUser]): TenantUser =
  result = TenantUser()
  if node.kind == JObject:
    if node.hasKey("email"):
      result.email = to(node["email"], string)
    if node.hasKey("email_verified"):
      result.emailVerified = to(node["email_verified"], bool)
    if node.hasKey("is_active"):
      result.isActive = to(node["is_active"], bool)
    if node.hasKey("joined_at"):
      result.joinedAt = to(node["joined_at"], string)
    if node.hasKey("last_login") and node["last_login"].kind != JNull:
      result.lastLogin = some(to(node["last_login"], typeof(result.lastLogin.get())))
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("permissions"):
      result.permissions = to(node["permissions"], seq[string])
    if node.hasKey("role"):
      result.role = to(node["role"], string)
    if node.hasKey("user_id"):
      result.userId = to(node["user_id"], string)

# Custom JSON serialization for TenantUser with custom field names
proc `%`*(obj: TenantUser): JsonNode =
  result = newJObject()
  result["email"] = %obj.email
  result["email_verified"] = %obj.emailVerified
  result["is_active"] = %obj.isActive
  result["joined_at"] = %obj.joinedAt
  if obj.lastLogin.isSome():
    result["last_login"] = %obj.lastLogin.get()
  result["name"] = %obj.name
  result["permissions"] = %obj.permissions
  result["role"] = %obj.role
  result["user_id"] = %obj.userId

