#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CartItemInput* = object
  ## 
  productId*: string
  quantity*: int


# Custom JSON deserialization for CartItemInput with custom field names
proc to*(node: JsonNode, T: typedesc[CartItemInput]): CartItemInput =
  result = CartItemInput()
  if node.kind == JObject:
    if node.hasKey("product_id"):
      result.productId = to(node["product_id"], string)
    if node.hasKey("quantity"):
      result.quantity = to(node["quantity"], int)

# Custom JSON serialization for CartItemInput with custom field names
proc `%`*(obj: CartItemInput): JsonNode =
  result = newJObject()
  result["product_id"] = %obj.productId
  result["quantity"] = %obj.quantity

