#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ParticipationUpdate* = object
  ## 
  acquiredAt*: Option[string] ## Datum des Erwerbs der Beteiligung.
  boardAppointment*: Option[bool] ## Bestellungsrecht für Geschäftsführung/Aufsichtsrat (§ 290 Abs. 2 Nr. 2 HGB).
  companyName*: Option[string] ## Name des Beteiligungsunternehmens (§ 271 HGB).
  controlAgreement*: Option[bool] ## Beherrschungsvertrag (§ 290 Abs. 2 Nr. 3 HGB).
  legalForm*: Option[string] ## Rechtsform, z. B. \"GmbH\".
  ownershipPct*: Option[string] ## Anteilsquote in Prozent (§ 271 HGB; > 20 % widerlegbare Vermutung).
  purposeVehicle*: Option[bool] ## Zweckgesellschaft (§ 290 Abs. 2 Nr. 4 HGB).
  votingMajority*: Option[bool] ## Stimmrechtsmehrheit (§ 290 Abs. 2 Nr. 1 HGB).

