#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CreateEmissionEntry* = object
  ## 
  activityValue*: string
  categoryId*: string
  description*: string
  `method`*: string
  scope*: string
  unit*: string
  year*: int


# Custom JSON deserialization for CreateEmissionEntry with custom field names
proc to*(node: JsonNode, T: typedesc[CreateEmissionEntry]): CreateEmissionEntry =
  result = CreateEmissionEntry()
  if node.kind == JObject:
    if node.hasKey("activity_value"):
      result.activityValue = to(node["activity_value"], string)
    if node.hasKey("category_id"):
      result.categoryId = to(node["category_id"], string)
    if node.hasKey("description"):
      result.description = to(node["description"], string)
    if node.hasKey("method"):
      result.`method` = to(node["method"], string)
    if node.hasKey("scope"):
      result.scope = to(node["scope"], string)
    if node.hasKey("unit"):
      result.unit = to(node["unit"], string)
    if node.hasKey("year"):
      result.year = to(node["year"], int)

# Custom JSON serialization for CreateEmissionEntry with custom field names
proc `%`*(obj: CreateEmissionEntry): JsonNode =
  result = newJObject()
  result["activity_value"] = %obj.activityValue
  result["category_id"] = %obj.categoryId
  result["description"] = %obj.description
  result["method"] = %obj.`method`
  result["scope"] = %obj.scope
  result["unit"] = %obj.unit
  result["year"] = %obj.year

