#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type InstrumentType* {.pure.} = enum
  Typisch
  Atypisch

func `%`*(v: InstrumentType): JsonNode =
  result = case v:
    of InstrumentType.Typisch: %"typisch"
    of InstrumentType.Atypisch: %"atypisch"

func `$`*(v: InstrumentType): string =
  result = case v:
    of InstrumentType.Typisch: $("typisch")
    of InstrumentType.Atypisch: $("atypisch")

proc to*(node: JsonNode, T: typedesc[InstrumentType]): InstrumentType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum InstrumentType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("typisch"):
    return InstrumentType.Typisch
  of $("atypisch"):
    return InstrumentType.Atypisch
  else:
    raise newException(ValueError, "Invalid enum value for InstrumentType: " & strVal)

