#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type BetriebsstaettenDetail* = object
  ## 
  beschaefigte*: int64
  monatlicherBeitrag*: string
  name*: string


# Custom JSON deserialization for BetriebsstaettenDetail with custom field names
proc to*(node: JsonNode, T: typedesc[BetriebsstaettenDetail]): BetriebsstaettenDetail =
  result = BetriebsstaettenDetail()
  if node.kind == JObject:
    if node.hasKey("beschaefigte"):
      result.beschaefigte = to(node["beschaefigte"], int64)
    if node.hasKey("monatlicher_beitrag"):
      result.monatlicherBeitrag = to(node["monatlicher_beitrag"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)

# Custom JSON serialization for BetriebsstaettenDetail with custom field names
proc `%`*(obj: BetriebsstaettenDetail): JsonNode =
  result = newJObject()
  result["beschaefigte"] = %obj.beschaefigte
  result["monatlicher_beitrag"] = %obj.monatlicherBeitrag
  result["name"] = %obj.name

