#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_supplier_invoice_status

type SupplierInvoiceUpdate* = object
  ## 
  currency*: Option[string]
  goodsReceiptId*: Option[string] ## References the goods receipt entity.
  invoiceDate*: Option[string]
  invoiceNumber*: Option[string]
  lineItems*: Option[JsonNode] ## JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`.
  notes*: Option[string]
  purchaseOrderId*: Option[string] ## References the purchase order entity.
  status*: Option[SupplierInvoiceStatus] ## One of: draft | matched | has_variances | posted | cancelled
  supplierContactId*: Option[string] ## References the supplier entity.
  supplierName*: Option[string]
  totalGrossAmount*: Option[string]
  totalNetAmount*: Option[string]

