#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type OAuthAuthorizeResponse* = object
  ## 
  authorizationUrl*: string
  state*: string


# Custom JSON deserialization for OAuthAuthorizeResponse with custom field names
proc to*(node: JsonNode, T: typedesc[OAuthAuthorizeResponse]): OAuthAuthorizeResponse =
  result = OAuthAuthorizeResponse()
  if node.kind == JObject:
    if node.hasKey("authorization_url"):
      result.authorizationUrl = to(node["authorization_url"], string)
    if node.hasKey("state"):
      result.state = to(node["state"], string)

# Custom JSON serialization for OAuthAuthorizeResponse with custom field names
proc `%`*(obj: OAuthAuthorizeResponse): JsonNode =
  result = newJObject()
  result["authorization_url"] = %obj.authorizationUrl
  result["state"] = %obj.state

