#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AiSuggestion* = object
  ## 
  confidence*: float64
  reasoning*: string
  suggestedPriority*: Option[string]
  suggestedReply*: string
  suggestedStatus*: Option[string]
  toolCalls*: seq[string]


# Custom JSON deserialization for AiSuggestion with custom field names
proc to*(node: JsonNode, T: typedesc[AiSuggestion]): AiSuggestion =
  result = AiSuggestion()
  if node.kind == JObject:
    if node.hasKey("confidence"):
      result.confidence = to(node["confidence"], float64)
    if node.hasKey("reasoning"):
      result.reasoning = to(node["reasoning"], string)
    if node.hasKey("suggested_priority") and node["suggested_priority"].kind != JNull:
      result.suggestedPriority = some(to(node["suggested_priority"], typeof(result.suggestedPriority.get())))
    if node.hasKey("suggested_reply"):
      result.suggestedReply = to(node["suggested_reply"], string)
    if node.hasKey("suggested_status") and node["suggested_status"].kind != JNull:
      result.suggestedStatus = some(to(node["suggested_status"], typeof(result.suggestedStatus.get())))
    if node.hasKey("tool_calls"):
      result.toolCalls = to(node["tool_calls"], seq[string])

# Custom JSON serialization for AiSuggestion with custom field names
proc `%`*(obj: AiSuggestion): JsonNode =
  result = newJObject()
  result["confidence"] = %obj.confidence
  result["reasoning"] = %obj.reasoning
  if obj.suggestedPriority.isSome():
    result["suggested_priority"] = %obj.suggestedPriority.get()
  result["suggested_reply"] = %obj.suggestedReply
  if obj.suggestedStatus.isSome():
    result["suggested_status"] = %obj.suggestedStatus.get()
  result["tool_calls"] = %obj.toolCalls

