#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_account_overview
import model_balance_sheet
import model_income_statement
import model_vat_summary

type EBilanzReport* = object
  ## 
  accountOverview*: seq[AccountOverview]
  balanceSheet*: BalanceSheet
  generatedAt*: string
  incomeStatement*: IncomeStatement
  period*: string
  vatSummary*: VatSummary


# Custom JSON deserialization for EBilanzReport with custom field names
proc to*(node: JsonNode, T: typedesc[EBilanzReport]): EBilanzReport =
  result = EBilanzReport()
  if node.kind == JObject:
    if node.hasKey("account_overview"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["account_overview"]
      if arrayNode.kind == JArray:
        result.accountOverview = @[]
        for item in arrayNode.items:
          result.accountOverview.add(to(item, AccountOverview))
    if node.hasKey("balance_sheet"):
      result.balanceSheet = to(node["balance_sheet"], BalanceSheet)
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("income_statement"):
      result.incomeStatement = to(node["income_statement"], IncomeStatement)
    if node.hasKey("period"):
      result.period = to(node["period"], string)
    if node.hasKey("vat_summary"):
      result.vatSummary = to(node["vat_summary"], VatSummary)

# Custom JSON serialization for EBilanzReport with custom field names
proc `%`*(obj: EBilanzReport): JsonNode =
  result = newJObject()
  result["account_overview"] = %obj.accountOverview
  result["balance_sheet"] = %obj.balanceSheet
  result["generated_at"] = %obj.generatedAt
  result["income_statement"] = %obj.incomeStatement
  result["period"] = %obj.period
  result["vat_summary"] = %obj.vatSummary

