#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CountryCode* {.pure.} = enum
  ABW
  AFG
  AGO
  AIA
  ALA
  ALB
  AND
  ARE
  ARG
  ARM
  ASM
  ATA
  ATF
  ATG
  AUS
  AUT
  AZE
  BDI
  BEL
  BEN
  BES
  BFA
  BGD
  BGR
  BHR
  BHS
  BIH
  BLM
  BLR
  BLZ
  BMU
  BOL
  BRA
  BRB
  BRN
  BTN
  BVT
  BWA
  CAF
  CAN
  CCK
  CHE
  CHL
  CHN
  CIV
  CMR
  COD
  COG
  COK
  COL
  COM
  CPV
  CRI
  CUB
  CUW
  CXR
  CYM
  CYP
  CZE
  DEU
  DJI
  DMA
  DNK
  DOM
  DZA
  ECU
  EGY
  ERI
  ESH
  ESP
  EST
  ETH
  FIN
  FJI
  FLK
  FRA
  FRO
  FSM
  GAB
  GBR
  GEO
  GGY
  GHA
  GIB
  GIN
  GLP
  GMB
  GNB
  GNQ
  GRC
  GRD
  GRL
  GTM
  GUF
  GUM
  GUY
  HKG
  HMD
  HND
  HRV
  HTI
  HUN
  IDN
  IMN
  IND
  IOT
  IRL
  IRN
  IRQ
  ISL
  ISR
  ITA
  JAM
  JEY
  JOR
  JPN
  KAZ
  KEN
  KGZ
  KHM
  KIR
  KNA
  KOR
  KWT
  LAO
  LBN
  LBR
  LBY
  LCA
  LIE
  LKA
  LSO
  LTU
  LUX
  LVA
  MAC
  MAF
  MAR
  MCO
  MDA
  MDG
  MDV
  MEX
  MHL
  MKD
  MLI
  MLT
  MMR
  MNE
  MNG
  MNP
  MOZ
  MRT
  MSR
  MTQ
  MUS
  MWI
  MYS
  MYT
  NAM
  NCL
  NER
  NFK
  NGA
  NIC
  NIU
  NLD
  NOR
  NPL
  NRU
  NZL
  OMN
  PAK
  PAN
  PCN
  PER
  PHL
  PLW
  PNG
  POL
  PRI
  PRK
  PRT
  PRY
  PSE
  PYF
  QAT
  REU
  ROU
  RUS
  RWA
  SAU
  SDN
  SEN
  SGP
  SGS
  SHN
  SJM
  SLB
  SLE
  SLV
  SMR
  SOM
  SPM
  SRB
  SSD
  STP
  SUR
  SVK
  SVN
  SWE
  SWZ
  SXM
  SYC
  SYR
  TCA
  TCD
  TGO
  THA
  TJK
  TKL
  TKM
  TLS
  TON
  TTO
  TUN
  TUR
  TUV
  TWN
  TZA
  UGA
  UKR
  UMI
  URY
  USA
  UZB
  VAT
  VCT
  VEN
  VGB
  VIR
  VNM
  VUT
  WLF
  WSM
  YEM
  ZAF
  ZMB
  ZWE

func `%`*(v: CountryCode): JsonNode =
  result = case v:
    of CountryCode.ABW: %"ABW"
    of CountryCode.AFG: %"AFG"
    of CountryCode.AGO: %"AGO"
    of CountryCode.AIA: %"AIA"
    of CountryCode.ALA: %"ALA"
    of CountryCode.ALB: %"ALB"
    of CountryCode.AND: %"AND"
    of CountryCode.ARE: %"ARE"
    of CountryCode.ARG: %"ARG"
    of CountryCode.ARM: %"ARM"
    of CountryCode.ASM: %"ASM"
    of CountryCode.ATA: %"ATA"
    of CountryCode.ATF: %"ATF"
    of CountryCode.ATG: %"ATG"
    of CountryCode.AUS: %"AUS"
    of CountryCode.AUT: %"AUT"
    of CountryCode.AZE: %"AZE"
    of CountryCode.BDI: %"BDI"
    of CountryCode.BEL: %"BEL"
    of CountryCode.BEN: %"BEN"
    of CountryCode.BES: %"BES"
    of CountryCode.BFA: %"BFA"
    of CountryCode.BGD: %"BGD"
    of CountryCode.BGR: %"BGR"
    of CountryCode.BHR: %"BHR"
    of CountryCode.BHS: %"BHS"
    of CountryCode.BIH: %"BIH"
    of CountryCode.BLM: %"BLM"
    of CountryCode.BLR: %"BLR"
    of CountryCode.BLZ: %"BLZ"
    of CountryCode.BMU: %"BMU"
    of CountryCode.BOL: %"BOL"
    of CountryCode.BRA: %"BRA"
    of CountryCode.BRB: %"BRB"
    of CountryCode.BRN: %"BRN"
    of CountryCode.BTN: %"BTN"
    of CountryCode.BVT: %"BVT"
    of CountryCode.BWA: %"BWA"
    of CountryCode.CAF: %"CAF"
    of CountryCode.CAN: %"CAN"
    of CountryCode.CCK: %"CCK"
    of CountryCode.CHE: %"CHE"
    of CountryCode.CHL: %"CHL"
    of CountryCode.CHN: %"CHN"
    of CountryCode.CIV: %"CIV"
    of CountryCode.CMR: %"CMR"
    of CountryCode.COD: %"COD"
    of CountryCode.COG: %"COG"
    of CountryCode.COK: %"COK"
    of CountryCode.COL: %"COL"
    of CountryCode.COM: %"COM"
    of CountryCode.CPV: %"CPV"
    of CountryCode.CRI: %"CRI"
    of CountryCode.CUB: %"CUB"
    of CountryCode.CUW: %"CUW"
    of CountryCode.CXR: %"CXR"
    of CountryCode.CYM: %"CYM"
    of CountryCode.CYP: %"CYP"
    of CountryCode.CZE: %"CZE"
    of CountryCode.DEU: %"DEU"
    of CountryCode.DJI: %"DJI"
    of CountryCode.DMA: %"DMA"
    of CountryCode.DNK: %"DNK"
    of CountryCode.DOM: %"DOM"
    of CountryCode.DZA: %"DZA"
    of CountryCode.ECU: %"ECU"
    of CountryCode.EGY: %"EGY"
    of CountryCode.ERI: %"ERI"
    of CountryCode.ESH: %"ESH"
    of CountryCode.ESP: %"ESP"
    of CountryCode.EST: %"EST"
    of CountryCode.ETH: %"ETH"
    of CountryCode.FIN: %"FIN"
    of CountryCode.FJI: %"FJI"
    of CountryCode.FLK: %"FLK"
    of CountryCode.FRA: %"FRA"
    of CountryCode.FRO: %"FRO"
    of CountryCode.FSM: %"FSM"
    of CountryCode.GAB: %"GAB"
    of CountryCode.GBR: %"GBR"
    of CountryCode.GEO: %"GEO"
    of CountryCode.GGY: %"GGY"
    of CountryCode.GHA: %"GHA"
    of CountryCode.GIB: %"GIB"
    of CountryCode.GIN: %"GIN"
    of CountryCode.GLP: %"GLP"
    of CountryCode.GMB: %"GMB"
    of CountryCode.GNB: %"GNB"
    of CountryCode.GNQ: %"GNQ"
    of CountryCode.GRC: %"GRC"
    of CountryCode.GRD: %"GRD"
    of CountryCode.GRL: %"GRL"
    of CountryCode.GTM: %"GTM"
    of CountryCode.GUF: %"GUF"
    of CountryCode.GUM: %"GUM"
    of CountryCode.GUY: %"GUY"
    of CountryCode.HKG: %"HKG"
    of CountryCode.HMD: %"HMD"
    of CountryCode.HND: %"HND"
    of CountryCode.HRV: %"HRV"
    of CountryCode.HTI: %"HTI"
    of CountryCode.HUN: %"HUN"
    of CountryCode.IDN: %"IDN"
    of CountryCode.IMN: %"IMN"
    of CountryCode.IND: %"IND"
    of CountryCode.IOT: %"IOT"
    of CountryCode.IRL: %"IRL"
    of CountryCode.IRN: %"IRN"
    of CountryCode.IRQ: %"IRQ"
    of CountryCode.ISL: %"ISL"
    of CountryCode.ISR: %"ISR"
    of CountryCode.ITA: %"ITA"
    of CountryCode.JAM: %"JAM"
    of CountryCode.JEY: %"JEY"
    of CountryCode.JOR: %"JOR"
    of CountryCode.JPN: %"JPN"
    of CountryCode.KAZ: %"KAZ"
    of CountryCode.KEN: %"KEN"
    of CountryCode.KGZ: %"KGZ"
    of CountryCode.KHM: %"KHM"
    of CountryCode.KIR: %"KIR"
    of CountryCode.KNA: %"KNA"
    of CountryCode.KOR: %"KOR"
    of CountryCode.KWT: %"KWT"
    of CountryCode.LAO: %"LAO"
    of CountryCode.LBN: %"LBN"
    of CountryCode.LBR: %"LBR"
    of CountryCode.LBY: %"LBY"
    of CountryCode.LCA: %"LCA"
    of CountryCode.LIE: %"LIE"
    of CountryCode.LKA: %"LKA"
    of CountryCode.LSO: %"LSO"
    of CountryCode.LTU: %"LTU"
    of CountryCode.LUX: %"LUX"
    of CountryCode.LVA: %"LVA"
    of CountryCode.MAC: %"MAC"
    of CountryCode.MAF: %"MAF"
    of CountryCode.MAR: %"MAR"
    of CountryCode.MCO: %"MCO"
    of CountryCode.MDA: %"MDA"
    of CountryCode.MDG: %"MDG"
    of CountryCode.MDV: %"MDV"
    of CountryCode.MEX: %"MEX"
    of CountryCode.MHL: %"MHL"
    of CountryCode.MKD: %"MKD"
    of CountryCode.MLI: %"MLI"
    of CountryCode.MLT: %"MLT"
    of CountryCode.MMR: %"MMR"
    of CountryCode.MNE: %"MNE"
    of CountryCode.MNG: %"MNG"
    of CountryCode.MNP: %"MNP"
    of CountryCode.MOZ: %"MOZ"
    of CountryCode.MRT: %"MRT"
    of CountryCode.MSR: %"MSR"
    of CountryCode.MTQ: %"MTQ"
    of CountryCode.MUS: %"MUS"
    of CountryCode.MWI: %"MWI"
    of CountryCode.MYS: %"MYS"
    of CountryCode.MYT: %"MYT"
    of CountryCode.NAM: %"NAM"
    of CountryCode.NCL: %"NCL"
    of CountryCode.NER: %"NER"
    of CountryCode.NFK: %"NFK"
    of CountryCode.NGA: %"NGA"
    of CountryCode.NIC: %"NIC"
    of CountryCode.NIU: %"NIU"
    of CountryCode.NLD: %"NLD"
    of CountryCode.NOR: %"NOR"
    of CountryCode.NPL: %"NPL"
    of CountryCode.NRU: %"NRU"
    of CountryCode.NZL: %"NZL"
    of CountryCode.OMN: %"OMN"
    of CountryCode.PAK: %"PAK"
    of CountryCode.PAN: %"PAN"
    of CountryCode.PCN: %"PCN"
    of CountryCode.PER: %"PER"
    of CountryCode.PHL: %"PHL"
    of CountryCode.PLW: %"PLW"
    of CountryCode.PNG: %"PNG"
    of CountryCode.POL: %"POL"
    of CountryCode.PRI: %"PRI"
    of CountryCode.PRK: %"PRK"
    of CountryCode.PRT: %"PRT"
    of CountryCode.PRY: %"PRY"
    of CountryCode.PSE: %"PSE"
    of CountryCode.PYF: %"PYF"
    of CountryCode.QAT: %"QAT"
    of CountryCode.REU: %"REU"
    of CountryCode.ROU: %"ROU"
    of CountryCode.RUS: %"RUS"
    of CountryCode.RWA: %"RWA"
    of CountryCode.SAU: %"SAU"
    of CountryCode.SDN: %"SDN"
    of CountryCode.SEN: %"SEN"
    of CountryCode.SGP: %"SGP"
    of CountryCode.SGS: %"SGS"
    of CountryCode.SHN: %"SHN"
    of CountryCode.SJM: %"SJM"
    of CountryCode.SLB: %"SLB"
    of CountryCode.SLE: %"SLE"
    of CountryCode.SLV: %"SLV"
    of CountryCode.SMR: %"SMR"
    of CountryCode.SOM: %"SOM"
    of CountryCode.SPM: %"SPM"
    of CountryCode.SRB: %"SRB"
    of CountryCode.SSD: %"SSD"
    of CountryCode.STP: %"STP"
    of CountryCode.SUR: %"SUR"
    of CountryCode.SVK: %"SVK"
    of CountryCode.SVN: %"SVN"
    of CountryCode.SWE: %"SWE"
    of CountryCode.SWZ: %"SWZ"
    of CountryCode.SXM: %"SXM"
    of CountryCode.SYC: %"SYC"
    of CountryCode.SYR: %"SYR"
    of CountryCode.TCA: %"TCA"
    of CountryCode.TCD: %"TCD"
    of CountryCode.TGO: %"TGO"
    of CountryCode.THA: %"THA"
    of CountryCode.TJK: %"TJK"
    of CountryCode.TKL: %"TKL"
    of CountryCode.TKM: %"TKM"
    of CountryCode.TLS: %"TLS"
    of CountryCode.TON: %"TON"
    of CountryCode.TTO: %"TTO"
    of CountryCode.TUN: %"TUN"
    of CountryCode.TUR: %"TUR"
    of CountryCode.TUV: %"TUV"
    of CountryCode.TWN: %"TWN"
    of CountryCode.TZA: %"TZA"
    of CountryCode.UGA: %"UGA"
    of CountryCode.UKR: %"UKR"
    of CountryCode.UMI: %"UMI"
    of CountryCode.URY: %"URY"
    of CountryCode.USA: %"USA"
    of CountryCode.UZB: %"UZB"
    of CountryCode.VAT: %"VAT"
    of CountryCode.VCT: %"VCT"
    of CountryCode.VEN: %"VEN"
    of CountryCode.VGB: %"VGB"
    of CountryCode.VIR: %"VIR"
    of CountryCode.VNM: %"VNM"
    of CountryCode.VUT: %"VUT"
    of CountryCode.WLF: %"WLF"
    of CountryCode.WSM: %"WSM"
    of CountryCode.YEM: %"YEM"
    of CountryCode.ZAF: %"ZAF"
    of CountryCode.ZMB: %"ZMB"
    of CountryCode.ZWE: %"ZWE"

func `$`*(v: CountryCode): string =
  result = case v:
    of CountryCode.ABW: $("ABW")
    of CountryCode.AFG: $("AFG")
    of CountryCode.AGO: $("AGO")
    of CountryCode.AIA: $("AIA")
    of CountryCode.ALA: $("ALA")
    of CountryCode.ALB: $("ALB")
    of CountryCode.AND: $("AND")
    of CountryCode.ARE: $("ARE")
    of CountryCode.ARG: $("ARG")
    of CountryCode.ARM: $("ARM")
    of CountryCode.ASM: $("ASM")
    of CountryCode.ATA: $("ATA")
    of CountryCode.ATF: $("ATF")
    of CountryCode.ATG: $("ATG")
    of CountryCode.AUS: $("AUS")
    of CountryCode.AUT: $("AUT")
    of CountryCode.AZE: $("AZE")
    of CountryCode.BDI: $("BDI")
    of CountryCode.BEL: $("BEL")
    of CountryCode.BEN: $("BEN")
    of CountryCode.BES: $("BES")
    of CountryCode.BFA: $("BFA")
    of CountryCode.BGD: $("BGD")
    of CountryCode.BGR: $("BGR")
    of CountryCode.BHR: $("BHR")
    of CountryCode.BHS: $("BHS")
    of CountryCode.BIH: $("BIH")
    of CountryCode.BLM: $("BLM")
    of CountryCode.BLR: $("BLR")
    of CountryCode.BLZ: $("BLZ")
    of CountryCode.BMU: $("BMU")
    of CountryCode.BOL: $("BOL")
    of CountryCode.BRA: $("BRA")
    of CountryCode.BRB: $("BRB")
    of CountryCode.BRN: $("BRN")
    of CountryCode.BTN: $("BTN")
    of CountryCode.BVT: $("BVT")
    of CountryCode.BWA: $("BWA")
    of CountryCode.CAF: $("CAF")
    of CountryCode.CAN: $("CAN")
    of CountryCode.CCK: $("CCK")
    of CountryCode.CHE: $("CHE")
    of CountryCode.CHL: $("CHL")
    of CountryCode.CHN: $("CHN")
    of CountryCode.CIV: $("CIV")
    of CountryCode.CMR: $("CMR")
    of CountryCode.COD: $("COD")
    of CountryCode.COG: $("COG")
    of CountryCode.COK: $("COK")
    of CountryCode.COL: $("COL")
    of CountryCode.COM: $("COM")
    of CountryCode.CPV: $("CPV")
    of CountryCode.CRI: $("CRI")
    of CountryCode.CUB: $("CUB")
    of CountryCode.CUW: $("CUW")
    of CountryCode.CXR: $("CXR")
    of CountryCode.CYM: $("CYM")
    of CountryCode.CYP: $("CYP")
    of CountryCode.CZE: $("CZE")
    of CountryCode.DEU: $("DEU")
    of CountryCode.DJI: $("DJI")
    of CountryCode.DMA: $("DMA")
    of CountryCode.DNK: $("DNK")
    of CountryCode.DOM: $("DOM")
    of CountryCode.DZA: $("DZA")
    of CountryCode.ECU: $("ECU")
    of CountryCode.EGY: $("EGY")
    of CountryCode.ERI: $("ERI")
    of CountryCode.ESH: $("ESH")
    of CountryCode.ESP: $("ESP")
    of CountryCode.EST: $("EST")
    of CountryCode.ETH: $("ETH")
    of CountryCode.FIN: $("FIN")
    of CountryCode.FJI: $("FJI")
    of CountryCode.FLK: $("FLK")
    of CountryCode.FRA: $("FRA")
    of CountryCode.FRO: $("FRO")
    of CountryCode.FSM: $("FSM")
    of CountryCode.GAB: $("GAB")
    of CountryCode.GBR: $("GBR")
    of CountryCode.GEO: $("GEO")
    of CountryCode.GGY: $("GGY")
    of CountryCode.GHA: $("GHA")
    of CountryCode.GIB: $("GIB")
    of CountryCode.GIN: $("GIN")
    of CountryCode.GLP: $("GLP")
    of CountryCode.GMB: $("GMB")
    of CountryCode.GNB: $("GNB")
    of CountryCode.GNQ: $("GNQ")
    of CountryCode.GRC: $("GRC")
    of CountryCode.GRD: $("GRD")
    of CountryCode.GRL: $("GRL")
    of CountryCode.GTM: $("GTM")
    of CountryCode.GUF: $("GUF")
    of CountryCode.GUM: $("GUM")
    of CountryCode.GUY: $("GUY")
    of CountryCode.HKG: $("HKG")
    of CountryCode.HMD: $("HMD")
    of CountryCode.HND: $("HND")
    of CountryCode.HRV: $("HRV")
    of CountryCode.HTI: $("HTI")
    of CountryCode.HUN: $("HUN")
    of CountryCode.IDN: $("IDN")
    of CountryCode.IMN: $("IMN")
    of CountryCode.IND: $("IND")
    of CountryCode.IOT: $("IOT")
    of CountryCode.IRL: $("IRL")
    of CountryCode.IRN: $("IRN")
    of CountryCode.IRQ: $("IRQ")
    of CountryCode.ISL: $("ISL")
    of CountryCode.ISR: $("ISR")
    of CountryCode.ITA: $("ITA")
    of CountryCode.JAM: $("JAM")
    of CountryCode.JEY: $("JEY")
    of CountryCode.JOR: $("JOR")
    of CountryCode.JPN: $("JPN")
    of CountryCode.KAZ: $("KAZ")
    of CountryCode.KEN: $("KEN")
    of CountryCode.KGZ: $("KGZ")
    of CountryCode.KHM: $("KHM")
    of CountryCode.KIR: $("KIR")
    of CountryCode.KNA: $("KNA")
    of CountryCode.KOR: $("KOR")
    of CountryCode.KWT: $("KWT")
    of CountryCode.LAO: $("LAO")
    of CountryCode.LBN: $("LBN")
    of CountryCode.LBR: $("LBR")
    of CountryCode.LBY: $("LBY")
    of CountryCode.LCA: $("LCA")
    of CountryCode.LIE: $("LIE")
    of CountryCode.LKA: $("LKA")
    of CountryCode.LSO: $("LSO")
    of CountryCode.LTU: $("LTU")
    of CountryCode.LUX: $("LUX")
    of CountryCode.LVA: $("LVA")
    of CountryCode.MAC: $("MAC")
    of CountryCode.MAF: $("MAF")
    of CountryCode.MAR: $("MAR")
    of CountryCode.MCO: $("MCO")
    of CountryCode.MDA: $("MDA")
    of CountryCode.MDG: $("MDG")
    of CountryCode.MDV: $("MDV")
    of CountryCode.MEX: $("MEX")
    of CountryCode.MHL: $("MHL")
    of CountryCode.MKD: $("MKD")
    of CountryCode.MLI: $("MLI")
    of CountryCode.MLT: $("MLT")
    of CountryCode.MMR: $("MMR")
    of CountryCode.MNE: $("MNE")
    of CountryCode.MNG: $("MNG")
    of CountryCode.MNP: $("MNP")
    of CountryCode.MOZ: $("MOZ")
    of CountryCode.MRT: $("MRT")
    of CountryCode.MSR: $("MSR")
    of CountryCode.MTQ: $("MTQ")
    of CountryCode.MUS: $("MUS")
    of CountryCode.MWI: $("MWI")
    of CountryCode.MYS: $("MYS")
    of CountryCode.MYT: $("MYT")
    of CountryCode.NAM: $("NAM")
    of CountryCode.NCL: $("NCL")
    of CountryCode.NER: $("NER")
    of CountryCode.NFK: $("NFK")
    of CountryCode.NGA: $("NGA")
    of CountryCode.NIC: $("NIC")
    of CountryCode.NIU: $("NIU")
    of CountryCode.NLD: $("NLD")
    of CountryCode.NOR: $("NOR")
    of CountryCode.NPL: $("NPL")
    of CountryCode.NRU: $("NRU")
    of CountryCode.NZL: $("NZL")
    of CountryCode.OMN: $("OMN")
    of CountryCode.PAK: $("PAK")
    of CountryCode.PAN: $("PAN")
    of CountryCode.PCN: $("PCN")
    of CountryCode.PER: $("PER")
    of CountryCode.PHL: $("PHL")
    of CountryCode.PLW: $("PLW")
    of CountryCode.PNG: $("PNG")
    of CountryCode.POL: $("POL")
    of CountryCode.PRI: $("PRI")
    of CountryCode.PRK: $("PRK")
    of CountryCode.PRT: $("PRT")
    of CountryCode.PRY: $("PRY")
    of CountryCode.PSE: $("PSE")
    of CountryCode.PYF: $("PYF")
    of CountryCode.QAT: $("QAT")
    of CountryCode.REU: $("REU")
    of CountryCode.ROU: $("ROU")
    of CountryCode.RUS: $("RUS")
    of CountryCode.RWA: $("RWA")
    of CountryCode.SAU: $("SAU")
    of CountryCode.SDN: $("SDN")
    of CountryCode.SEN: $("SEN")
    of CountryCode.SGP: $("SGP")
    of CountryCode.SGS: $("SGS")
    of CountryCode.SHN: $("SHN")
    of CountryCode.SJM: $("SJM")
    of CountryCode.SLB: $("SLB")
    of CountryCode.SLE: $("SLE")
    of CountryCode.SLV: $("SLV")
    of CountryCode.SMR: $("SMR")
    of CountryCode.SOM: $("SOM")
    of CountryCode.SPM: $("SPM")
    of CountryCode.SRB: $("SRB")
    of CountryCode.SSD: $("SSD")
    of CountryCode.STP: $("STP")
    of CountryCode.SUR: $("SUR")
    of CountryCode.SVK: $("SVK")
    of CountryCode.SVN: $("SVN")
    of CountryCode.SWE: $("SWE")
    of CountryCode.SWZ: $("SWZ")
    of CountryCode.SXM: $("SXM")
    of CountryCode.SYC: $("SYC")
    of CountryCode.SYR: $("SYR")
    of CountryCode.TCA: $("TCA")
    of CountryCode.TCD: $("TCD")
    of CountryCode.TGO: $("TGO")
    of CountryCode.THA: $("THA")
    of CountryCode.TJK: $("TJK")
    of CountryCode.TKL: $("TKL")
    of CountryCode.TKM: $("TKM")
    of CountryCode.TLS: $("TLS")
    of CountryCode.TON: $("TON")
    of CountryCode.TTO: $("TTO")
    of CountryCode.TUN: $("TUN")
    of CountryCode.TUR: $("TUR")
    of CountryCode.TUV: $("TUV")
    of CountryCode.TWN: $("TWN")
    of CountryCode.TZA: $("TZA")
    of CountryCode.UGA: $("UGA")
    of CountryCode.UKR: $("UKR")
    of CountryCode.UMI: $("UMI")
    of CountryCode.URY: $("URY")
    of CountryCode.USA: $("USA")
    of CountryCode.UZB: $("UZB")
    of CountryCode.VAT: $("VAT")
    of CountryCode.VCT: $("VCT")
    of CountryCode.VEN: $("VEN")
    of CountryCode.VGB: $("VGB")
    of CountryCode.VIR: $("VIR")
    of CountryCode.VNM: $("VNM")
    of CountryCode.VUT: $("VUT")
    of CountryCode.WLF: $("WLF")
    of CountryCode.WSM: $("WSM")
    of CountryCode.YEM: $("YEM")
    of CountryCode.ZAF: $("ZAF")
    of CountryCode.ZMB: $("ZMB")
    of CountryCode.ZWE: $("ZWE")

proc to*(node: JsonNode, T: typedesc[CountryCode]): CountryCode =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum CountryCode, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("ABW"):
    return CountryCode.ABW
  of $("AFG"):
    return CountryCode.AFG
  of $("AGO"):
    return CountryCode.AGO
  of $("AIA"):
    return CountryCode.AIA
  of $("ALA"):
    return CountryCode.ALA
  of $("ALB"):
    return CountryCode.ALB
  of $("AND"):
    return CountryCode.AND
  of $("ARE"):
    return CountryCode.ARE
  of $("ARG"):
    return CountryCode.ARG
  of $("ARM"):
    return CountryCode.ARM
  of $("ASM"):
    return CountryCode.ASM
  of $("ATA"):
    return CountryCode.ATA
  of $("ATF"):
    return CountryCode.ATF
  of $("ATG"):
    return CountryCode.ATG
  of $("AUS"):
    return CountryCode.AUS
  of $("AUT"):
    return CountryCode.AUT
  of $("AZE"):
    return CountryCode.AZE
  of $("BDI"):
    return CountryCode.BDI
  of $("BEL"):
    return CountryCode.BEL
  of $("BEN"):
    return CountryCode.BEN
  of $("BES"):
    return CountryCode.BES
  of $("BFA"):
    return CountryCode.BFA
  of $("BGD"):
    return CountryCode.BGD
  of $("BGR"):
    return CountryCode.BGR
  of $("BHR"):
    return CountryCode.BHR
  of $("BHS"):
    return CountryCode.BHS
  of $("BIH"):
    return CountryCode.BIH
  of $("BLM"):
    return CountryCode.BLM
  of $("BLR"):
    return CountryCode.BLR
  of $("BLZ"):
    return CountryCode.BLZ
  of $("BMU"):
    return CountryCode.BMU
  of $("BOL"):
    return CountryCode.BOL
  of $("BRA"):
    return CountryCode.BRA
  of $("BRB"):
    return CountryCode.BRB
  of $("BRN"):
    return CountryCode.BRN
  of $("BTN"):
    return CountryCode.BTN
  of $("BVT"):
    return CountryCode.BVT
  of $("BWA"):
    return CountryCode.BWA
  of $("CAF"):
    return CountryCode.CAF
  of $("CAN"):
    return CountryCode.CAN
  of $("CCK"):
    return CountryCode.CCK
  of $("CHE"):
    return CountryCode.CHE
  of $("CHL"):
    return CountryCode.CHL
  of $("CHN"):
    return CountryCode.CHN
  of $("CIV"):
    return CountryCode.CIV
  of $("CMR"):
    return CountryCode.CMR
  of $("COD"):
    return CountryCode.COD
  of $("COG"):
    return CountryCode.COG
  of $("COK"):
    return CountryCode.COK
  of $("COL"):
    return CountryCode.COL
  of $("COM"):
    return CountryCode.COM
  of $("CPV"):
    return CountryCode.CPV
  of $("CRI"):
    return CountryCode.CRI
  of $("CUB"):
    return CountryCode.CUB
  of $("CUW"):
    return CountryCode.CUW
  of $("CXR"):
    return CountryCode.CXR
  of $("CYM"):
    return CountryCode.CYM
  of $("CYP"):
    return CountryCode.CYP
  of $("CZE"):
    return CountryCode.CZE
  of $("DEU"):
    return CountryCode.DEU
  of $("DJI"):
    return CountryCode.DJI
  of $("DMA"):
    return CountryCode.DMA
  of $("DNK"):
    return CountryCode.DNK
  of $("DOM"):
    return CountryCode.DOM
  of $("DZA"):
    return CountryCode.DZA
  of $("ECU"):
    return CountryCode.ECU
  of $("EGY"):
    return CountryCode.EGY
  of $("ERI"):
    return CountryCode.ERI
  of $("ESH"):
    return CountryCode.ESH
  of $("ESP"):
    return CountryCode.ESP
  of $("EST"):
    return CountryCode.EST
  of $("ETH"):
    return CountryCode.ETH
  of $("FIN"):
    return CountryCode.FIN
  of $("FJI"):
    return CountryCode.FJI
  of $("FLK"):
    return CountryCode.FLK
  of $("FRA"):
    return CountryCode.FRA
  of $("FRO"):
    return CountryCode.FRO
  of $("FSM"):
    return CountryCode.FSM
  of $("GAB"):
    return CountryCode.GAB
  of $("GBR"):
    return CountryCode.GBR
  of $("GEO"):
    return CountryCode.GEO
  of $("GGY"):
    return CountryCode.GGY
  of $("GHA"):
    return CountryCode.GHA
  of $("GIB"):
    return CountryCode.GIB
  of $("GIN"):
    return CountryCode.GIN
  of $("GLP"):
    return CountryCode.GLP
  of $("GMB"):
    return CountryCode.GMB
  of $("GNB"):
    return CountryCode.GNB
  of $("GNQ"):
    return CountryCode.GNQ
  of $("GRC"):
    return CountryCode.GRC
  of $("GRD"):
    return CountryCode.GRD
  of $("GRL"):
    return CountryCode.GRL
  of $("GTM"):
    return CountryCode.GTM
  of $("GUF"):
    return CountryCode.GUF
  of $("GUM"):
    return CountryCode.GUM
  of $("GUY"):
    return CountryCode.GUY
  of $("HKG"):
    return CountryCode.HKG
  of $("HMD"):
    return CountryCode.HMD
  of $("HND"):
    return CountryCode.HND
  of $("HRV"):
    return CountryCode.HRV
  of $("HTI"):
    return CountryCode.HTI
  of $("HUN"):
    return CountryCode.HUN
  of $("IDN"):
    return CountryCode.IDN
  of $("IMN"):
    return CountryCode.IMN
  of $("IND"):
    return CountryCode.IND
  of $("IOT"):
    return CountryCode.IOT
  of $("IRL"):
    return CountryCode.IRL
  of $("IRN"):
    return CountryCode.IRN
  of $("IRQ"):
    return CountryCode.IRQ
  of $("ISL"):
    return CountryCode.ISL
  of $("ISR"):
    return CountryCode.ISR
  of $("ITA"):
    return CountryCode.ITA
  of $("JAM"):
    return CountryCode.JAM
  of $("JEY"):
    return CountryCode.JEY
  of $("JOR"):
    return CountryCode.JOR
  of $("JPN"):
    return CountryCode.JPN
  of $("KAZ"):
    return CountryCode.KAZ
  of $("KEN"):
    return CountryCode.KEN
  of $("KGZ"):
    return CountryCode.KGZ
  of $("KHM"):
    return CountryCode.KHM
  of $("KIR"):
    return CountryCode.KIR
  of $("KNA"):
    return CountryCode.KNA
  of $("KOR"):
    return CountryCode.KOR
  of $("KWT"):
    return CountryCode.KWT
  of $("LAO"):
    return CountryCode.LAO
  of $("LBN"):
    return CountryCode.LBN
  of $("LBR"):
    return CountryCode.LBR
  of $("LBY"):
    return CountryCode.LBY
  of $("LCA"):
    return CountryCode.LCA
  of $("LIE"):
    return CountryCode.LIE
  of $("LKA"):
    return CountryCode.LKA
  of $("LSO"):
    return CountryCode.LSO
  of $("LTU"):
    return CountryCode.LTU
  of $("LUX"):
    return CountryCode.LUX
  of $("LVA"):
    return CountryCode.LVA
  of $("MAC"):
    return CountryCode.MAC
  of $("MAF"):
    return CountryCode.MAF
  of $("MAR"):
    return CountryCode.MAR
  of $("MCO"):
    return CountryCode.MCO
  of $("MDA"):
    return CountryCode.MDA
  of $("MDG"):
    return CountryCode.MDG
  of $("MDV"):
    return CountryCode.MDV
  of $("MEX"):
    return CountryCode.MEX
  of $("MHL"):
    return CountryCode.MHL
  of $("MKD"):
    return CountryCode.MKD
  of $("MLI"):
    return CountryCode.MLI
  of $("MLT"):
    return CountryCode.MLT
  of $("MMR"):
    return CountryCode.MMR
  of $("MNE"):
    return CountryCode.MNE
  of $("MNG"):
    return CountryCode.MNG
  of $("MNP"):
    return CountryCode.MNP
  of $("MOZ"):
    return CountryCode.MOZ
  of $("MRT"):
    return CountryCode.MRT
  of $("MSR"):
    return CountryCode.MSR
  of $("MTQ"):
    return CountryCode.MTQ
  of $("MUS"):
    return CountryCode.MUS
  of $("MWI"):
    return CountryCode.MWI
  of $("MYS"):
    return CountryCode.MYS
  of $("MYT"):
    return CountryCode.MYT
  of $("NAM"):
    return CountryCode.NAM
  of $("NCL"):
    return CountryCode.NCL
  of $("NER"):
    return CountryCode.NER
  of $("NFK"):
    return CountryCode.NFK
  of $("NGA"):
    return CountryCode.NGA
  of $("NIC"):
    return CountryCode.NIC
  of $("NIU"):
    return CountryCode.NIU
  of $("NLD"):
    return CountryCode.NLD
  of $("NOR"):
    return CountryCode.NOR
  of $("NPL"):
    return CountryCode.NPL
  of $("NRU"):
    return CountryCode.NRU
  of $("NZL"):
    return CountryCode.NZL
  of $("OMN"):
    return CountryCode.OMN
  of $("PAK"):
    return CountryCode.PAK
  of $("PAN"):
    return CountryCode.PAN
  of $("PCN"):
    return CountryCode.PCN
  of $("PER"):
    return CountryCode.PER
  of $("PHL"):
    return CountryCode.PHL
  of $("PLW"):
    return CountryCode.PLW
  of $("PNG"):
    return CountryCode.PNG
  of $("POL"):
    return CountryCode.POL
  of $("PRI"):
    return CountryCode.PRI
  of $("PRK"):
    return CountryCode.PRK
  of $("PRT"):
    return CountryCode.PRT
  of $("PRY"):
    return CountryCode.PRY
  of $("PSE"):
    return CountryCode.PSE
  of $("PYF"):
    return CountryCode.PYF
  of $("QAT"):
    return CountryCode.QAT
  of $("REU"):
    return CountryCode.REU
  of $("ROU"):
    return CountryCode.ROU
  of $("RUS"):
    return CountryCode.RUS
  of $("RWA"):
    return CountryCode.RWA
  of $("SAU"):
    return CountryCode.SAU
  of $("SDN"):
    return CountryCode.SDN
  of $("SEN"):
    return CountryCode.SEN
  of $("SGP"):
    return CountryCode.SGP
  of $("SGS"):
    return CountryCode.SGS
  of $("SHN"):
    return CountryCode.SHN
  of $("SJM"):
    return CountryCode.SJM
  of $("SLB"):
    return CountryCode.SLB
  of $("SLE"):
    return CountryCode.SLE
  of $("SLV"):
    return CountryCode.SLV
  of $("SMR"):
    return CountryCode.SMR
  of $("SOM"):
    return CountryCode.SOM
  of $("SPM"):
    return CountryCode.SPM
  of $("SRB"):
    return CountryCode.SRB
  of $("SSD"):
    return CountryCode.SSD
  of $("STP"):
    return CountryCode.STP
  of $("SUR"):
    return CountryCode.SUR
  of $("SVK"):
    return CountryCode.SVK
  of $("SVN"):
    return CountryCode.SVN
  of $("SWE"):
    return CountryCode.SWE
  of $("SWZ"):
    return CountryCode.SWZ
  of $("SXM"):
    return CountryCode.SXM
  of $("SYC"):
    return CountryCode.SYC
  of $("SYR"):
    return CountryCode.SYR
  of $("TCA"):
    return CountryCode.TCA
  of $("TCD"):
    return CountryCode.TCD
  of $("TGO"):
    return CountryCode.TGO
  of $("THA"):
    return CountryCode.THA
  of $("TJK"):
    return CountryCode.TJK
  of $("TKL"):
    return CountryCode.TKL
  of $("TKM"):
    return CountryCode.TKM
  of $("TLS"):
    return CountryCode.TLS
  of $("TON"):
    return CountryCode.TON
  of $("TTO"):
    return CountryCode.TTO
  of $("TUN"):
    return CountryCode.TUN
  of $("TUR"):
    return CountryCode.TUR
  of $("TUV"):
    return CountryCode.TUV
  of $("TWN"):
    return CountryCode.TWN
  of $("TZA"):
    return CountryCode.TZA
  of $("UGA"):
    return CountryCode.UGA
  of $("UKR"):
    return CountryCode.UKR
  of $("UMI"):
    return CountryCode.UMI
  of $("URY"):
    return CountryCode.URY
  of $("USA"):
    return CountryCode.USA
  of $("UZB"):
    return CountryCode.UZB
  of $("VAT"):
    return CountryCode.VAT
  of $("VCT"):
    return CountryCode.VCT
  of $("VEN"):
    return CountryCode.VEN
  of $("VGB"):
    return CountryCode.VGB
  of $("VIR"):
    return CountryCode.VIR
  of $("VNM"):
    return CountryCode.VNM
  of $("VUT"):
    return CountryCode.VUT
  of $("WLF"):
    return CountryCode.WLF
  of $("WSM"):
    return CountryCode.WSM
  of $("YEM"):
    return CountryCode.YEM
  of $("ZAF"):
    return CountryCode.ZAF
  of $("ZMB"):
    return CountryCode.ZMB
  of $("ZWE"):
    return CountryCode.ZWE
  else:
    raise newException(ValueError, "Invalid enum value for CountryCode: " & strVal)

