#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CreateSubscriptionRequest* = object
  ## 
  eventType*: string
  isActive*: Option[bool]
  name*: string
  secret*: Option[string]
  url*: string


# Custom JSON deserialization for CreateSubscriptionRequest with custom field names
proc to*(node: JsonNode, T: typedesc[CreateSubscriptionRequest]): CreateSubscriptionRequest =
  result = CreateSubscriptionRequest()
  if node.kind == JObject:
    if node.hasKey("event_type"):
      result.eventType = to(node["event_type"], string)
    if node.hasKey("is_active") and node["is_active"].kind != JNull:
      result.isActive = some(to(node["is_active"], typeof(result.isActive.get())))
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("secret") and node["secret"].kind != JNull:
      result.secret = some(to(node["secret"], typeof(result.secret.get())))
    if node.hasKey("url"):
      result.url = to(node["url"], string)

# Custom JSON serialization for CreateSubscriptionRequest with custom field names
proc `%`*(obj: CreateSubscriptionRequest): JsonNode =
  result = newJObject()
  result["event_type"] = %obj.eventType
  if obj.isActive.isSome():
    result["is_active"] = %obj.isActive.get()
  result["name"] = %obj.name
  if obj.secret.isSome():
    result["secret"] = %obj.secret.get()
  result["url"] = %obj.url

