#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type TimeEntryClockOut* = object
  ## 
  clockOut*: string
  hours*: Option[string] ## Optional manual hours; when absent, derived from clock_in..clock_out.


# Custom JSON deserialization for TimeEntryClockOut with custom field names
proc to*(node: JsonNode, T: typedesc[TimeEntryClockOut]): TimeEntryClockOut =
  result = TimeEntryClockOut()
  if node.kind == JObject:
    if node.hasKey("clock_out"):
      result.clockOut = to(node["clock_out"], string)
    if node.hasKey("hours") and node["hours"].kind != JNull:
      result.hours = some(to(node["hours"], typeof(result.hours.get())))

# Custom JSON serialization for TimeEntryClockOut with custom field names
proc `%`*(obj: TimeEntryClockOut): JsonNode =
  result = newJObject()
  result["clock_out"] = %obj.clockOut
  if obj.hours.isSome():
    result["hours"] = %obj.hours.get()

