#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type VatItem* = object
  ## 
  netAmount*: string
  taxAmount*: string
  taxRate*: string


# Custom JSON deserialization for VatItem with custom field names
proc to*(node: JsonNode, T: typedesc[VatItem]): VatItem =
  result = VatItem()
  if node.kind == JObject:
    if node.hasKey("net_amount"):
      result.netAmount = to(node["net_amount"], string)
    if node.hasKey("tax_amount"):
      result.taxAmount = to(node["tax_amount"], string)
    if node.hasKey("tax_rate"):
      result.taxRate = to(node["tax_rate"], string)

# Custom JSON serialization for VatItem with custom field names
proc `%`*(obj: VatItem): JsonNode =
  result = newJObject()
  result["net_amount"] = %obj.netAmount
  result["tax_amount"] = %obj.taxAmount
  result["tax_rate"] = %obj.taxRate

