#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type VoucherStatus* {.pure.} = enum
  Open
  Paid
  Invoiced

func `%`*(v: VoucherStatus): JsonNode =
  result = case v:
    of VoucherStatus.Open: %"open"
    of VoucherStatus.Paid: %"paid"
    of VoucherStatus.Invoiced: %"invoiced"

func `$`*(v: VoucherStatus): string =
  result = case v:
    of VoucherStatus.Open: $("open")
    of VoucherStatus.Paid: $("paid")
    of VoucherStatus.Invoiced: $("invoiced")

proc to*(node: JsonNode, T: typedesc[VoucherStatus]): VoucherStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum VoucherStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("open"):
    return VoucherStatus.Open
  of $("paid"):
    return VoucherStatus.Paid
  of $("invoiced"):
    return VoucherStatus.Invoiced
  else:
    raise newException(ValueError, "Invalid enum value for VoucherStatus: " & strVal)

