#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_payroll_summary_item

type YearlyPayrollSummary* = object
  ## 
  avgEmployeeCount*: int
  months*: seq[PayrollSummaryItem]
  year*: int
  yearlyEmployerCost*: string
  yearlyGross*: string
  yearlyNet*: string


# Custom JSON deserialization for YearlyPayrollSummary with custom field names
proc to*(node: JsonNode, T: typedesc[YearlyPayrollSummary]): YearlyPayrollSummary =
  result = YearlyPayrollSummary()
  if node.kind == JObject:
    if node.hasKey("avg_employee_count"):
      result.avgEmployeeCount = to(node["avg_employee_count"], int)
    if node.hasKey("months"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["months"]
      if arrayNode.kind == JArray:
        result.months = @[]
        for item in arrayNode.items:
          result.months.add(to(item, PayrollSummaryItem))
    if node.hasKey("year"):
      result.year = to(node["year"], int)
    if node.hasKey("yearly_employer_cost"):
      result.yearlyEmployerCost = to(node["yearly_employer_cost"], string)
    if node.hasKey("yearly_gross"):
      result.yearlyGross = to(node["yearly_gross"], string)
    if node.hasKey("yearly_net"):
      result.yearlyNet = to(node["yearly_net"], string)

# Custom JSON serialization for YearlyPayrollSummary with custom field names
proc `%`*(obj: YearlyPayrollSummary): JsonNode =
  result = newJObject()
  result["avg_employee_count"] = %obj.avgEmployeeCount
  result["months"] = %obj.months
  result["year"] = %obj.year
  result["yearly_employer_cost"] = %obj.yearlyEmployerCost
  result["yearly_gross"] = %obj.yearlyGross
  result["yearly_net"] = %obj.yearlyNet

