#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type TrackOrderRequest* = object
  ## Refresh tracking for a shipment from the live carrier API and store the latest status + events on the shipment row.
  email*: string
  orderNumber*: string


# Custom JSON deserialization for TrackOrderRequest with custom field names
proc to*(node: JsonNode, T: typedesc[TrackOrderRequest]): TrackOrderRequest =
  result = TrackOrderRequest()
  if node.kind == JObject:
    if node.hasKey("email"):
      result.email = to(node["email"], string)
    if node.hasKey("order_number"):
      result.orderNumber = to(node["order_number"], string)

# Custom JSON serialization for TrackOrderRequest with custom field names
proc `%`*(obj: TrackOrderRequest): JsonNode =
  result = newJObject()
  result["email"] = %obj.email
  result["order_number"] = %obj.orderNumber

