#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type WorkflowAction* = object
  ## One action inside a workflow. Only `email` is supported for now.
  actionType*: string
  body*: Option[string]
  subject*: Option[string]


# Custom JSON deserialization for WorkflowAction with custom field names
proc to*(node: JsonNode, T: typedesc[WorkflowAction]): WorkflowAction =
  result = WorkflowAction()
  if node.kind == JObject:
    if node.hasKey("action_type"):
      result.actionType = to(node["action_type"], string)
    if node.hasKey("body") and node["body"].kind != JNull:
      result.body = some(to(node["body"], typeof(result.body.get())))
    if node.hasKey("subject") and node["subject"].kind != JNull:
      result.subject = some(to(node["subject"], typeof(result.subject.get())))

# Custom JSON serialization for WorkflowAction with custom field names
proc `%`*(obj: WorkflowAction): JsonNode =
  result = newJObject()
  result["action_type"] = %obj.actionType
  if obj.body.isSome():
    result["body"] = %obj.body.get()
  if obj.subject.isSome():
    result["subject"] = %obj.subject.get()

