#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type UpdateChannelDto* = object
  ## 
  config*: Option[JsonNode]
  isActive*: Option[bool]
  name*: Option[string]


# Custom JSON deserialization for UpdateChannelDto with custom field names
proc to*(node: JsonNode, T: typedesc[UpdateChannelDto]): UpdateChannelDto =
  result = UpdateChannelDto()
  if node.kind == JObject:
    if node.hasKey("config") and node["config"].kind != JNull:
      result.config = some(to(node["config"], typeof(result.config.get())))
    if node.hasKey("is_active") and node["is_active"].kind != JNull:
      result.isActive = some(to(node["is_active"], typeof(result.isActive.get())))
    if node.hasKey("name") and node["name"].kind != JNull:
      result.name = some(to(node["name"], typeof(result.name.get())))

# Custom JSON serialization for UpdateChannelDto with custom field names
proc `%`*(obj: UpdateChannelDto): JsonNode =
  result = newJObject()
  if obj.config.isSome():
    result["config"] = %obj.config.get()
  if obj.isActive.isSome():
    result["is_active"] = %obj.isActive.get()
  if obj.name.isSome():
    result["name"] = %obj.name.get()

