#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type MirrorTriggerResponse* = object
  ## 
  jobId*: string


# Custom JSON deserialization for MirrorTriggerResponse with custom field names
proc to*(node: JsonNode, T: typedesc[MirrorTriggerResponse]): MirrorTriggerResponse =
  result = MirrorTriggerResponse()
  if node.kind == JObject:
    if node.hasKey("job_id"):
      result.jobId = to(node["job_id"], string)

# Custom JSON serialization for MirrorTriggerResponse with custom field names
proc `%`*(obj: MirrorTriggerResponse): JsonNode =
  result = newJObject()
  result["job_id"] = %obj.jobId

