#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ElsterStatus* = object
  ## 
  certConfigured*: bool
  ericAvailable*: bool
  ericVersion*: Option[string]
  featureEnabled*: bool
  hint*: string
  mode*: string
  vendorIdConfigured*: bool


# Custom JSON deserialization for ElsterStatus with custom field names
proc to*(node: JsonNode, T: typedesc[ElsterStatus]): ElsterStatus =
  result = ElsterStatus()
  if node.kind == JObject:
    if node.hasKey("cert_configured"):
      result.certConfigured = to(node["cert_configured"], bool)
    if node.hasKey("eric_available"):
      result.ericAvailable = to(node["eric_available"], bool)
    if node.hasKey("eric_version") and node["eric_version"].kind != JNull:
      result.ericVersion = some(to(node["eric_version"], typeof(result.ericVersion.get())))
    if node.hasKey("feature_enabled"):
      result.featureEnabled = to(node["feature_enabled"], bool)
    if node.hasKey("hint"):
      result.hint = to(node["hint"], string)
    if node.hasKey("mode"):
      result.mode = to(node["mode"], string)
    if node.hasKey("vendor_id_configured"):
      result.vendorIdConfigured = to(node["vendor_id_configured"], bool)

# Custom JSON serialization for ElsterStatus with custom field names
proc `%`*(obj: ElsterStatus): JsonNode =
  result = newJObject()
  result["cert_configured"] = %obj.certConfigured
  result["eric_available"] = %obj.ericAvailable
  if obj.ericVersion.isSome():
    result["eric_version"] = %obj.ericVersion.get()
  result["feature_enabled"] = %obj.featureEnabled
  result["hint"] = %obj.hint
  result["mode"] = %obj.mode
  result["vendor_id_configured"] = %obj.vendorIdConfigured

