#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type GatewayType* {.pure.} = enum
  Stripe
  Paypal
  Klarna
  Sofort
  Bancontact
  Ideal
  BankTransfer
  Mollie
  Bitpay
  Braintree
  Adyen
  Paddle
  VivaWallet
  Reepay
  Sumup
  Test

func `%`*(v: GatewayType): JsonNode =
  result = case v:
    of GatewayType.Stripe: %"stripe"
    of GatewayType.Paypal: %"paypal"
    of GatewayType.Klarna: %"klarna"
    of GatewayType.Sofort: %"sofort"
    of GatewayType.Bancontact: %"bancontact"
    of GatewayType.Ideal: %"ideal"
    of GatewayType.BankTransfer: %"bank_transfer"
    of GatewayType.Mollie: %"mollie"
    of GatewayType.Bitpay: %"bitpay"
    of GatewayType.Braintree: %"braintree"
    of GatewayType.Adyen: %"adyen"
    of GatewayType.Paddle: %"paddle"
    of GatewayType.VivaWallet: %"viva_wallet"
    of GatewayType.Reepay: %"reepay"
    of GatewayType.Sumup: %"sumup"
    of GatewayType.Test: %"test"

func `$`*(v: GatewayType): string =
  result = case v:
    of GatewayType.Stripe: $("stripe")
    of GatewayType.Paypal: $("paypal")
    of GatewayType.Klarna: $("klarna")
    of GatewayType.Sofort: $("sofort")
    of GatewayType.Bancontact: $("bancontact")
    of GatewayType.Ideal: $("ideal")
    of GatewayType.BankTransfer: $("bank_transfer")
    of GatewayType.Mollie: $("mollie")
    of GatewayType.Bitpay: $("bitpay")
    of GatewayType.Braintree: $("braintree")
    of GatewayType.Adyen: $("adyen")
    of GatewayType.Paddle: $("paddle")
    of GatewayType.VivaWallet: $("viva_wallet")
    of GatewayType.Reepay: $("reepay")
    of GatewayType.Sumup: $("sumup")
    of GatewayType.Test: $("test")

proc to*(node: JsonNode, T: typedesc[GatewayType]): GatewayType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum GatewayType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("stripe"):
    return GatewayType.Stripe
  of $("paypal"):
    return GatewayType.Paypal
  of $("klarna"):
    return GatewayType.Klarna
  of $("sofort"):
    return GatewayType.Sofort
  of $("bancontact"):
    return GatewayType.Bancontact
  of $("ideal"):
    return GatewayType.Ideal
  of $("bank_transfer"):
    return GatewayType.BankTransfer
  of $("mollie"):
    return GatewayType.Mollie
  of $("bitpay"):
    return GatewayType.Bitpay
  of $("braintree"):
    return GatewayType.Braintree
  of $("adyen"):
    return GatewayType.Adyen
  of $("paddle"):
    return GatewayType.Paddle
  of $("viva_wallet"):
    return GatewayType.VivaWallet
  of $("reepay"):
    return GatewayType.Reepay
  of $("sumup"):
    return GatewayType.Sumup
  of $("test"):
    return GatewayType.Test
  else:
    raise newException(ValueError, "Invalid enum value for GatewayType: " & strVal)

