#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_emission_method
import model_ghg_scope

type EmissionEntry* = object
  ## 
  activityValue*: string ## Activity amount in `unit` (kWh, l, km, t, tkm, EUR).
  categoryId*: string ## GHG-Protocol category key, e.g. \"purchased_goods\", \"business_travel\".
  description*: string
  efSource*: string ## Emission-factor source, e.g. \"UBA-2024\", \"DEFRA-2024\".
  efVersion*: string
  `method`*: EmissionMethod ## \"activity\" | \"spend\" | \"supplier\".
  scope*: GhgScope ## GHG scope: \"1\" | \"2\" | \"3\".
  tco2e*: string ## Computed server-side: activity * factor / 1000, rounded to 4 dp.
  unit*: string ## Unit of the activity value.
  updatedAt*: Option[string]
  year*: int ## Reporting year.

