#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type MessageType* {.pure.} = enum
  Text
  Html

func `%`*(v: MessageType): JsonNode =
  result = case v:
    of MessageType.Text: %"text"
    of MessageType.Html: %"html"

func `$`*(v: MessageType): string =
  result = case v:
    of MessageType.Text: $("text")
    of MessageType.Html: $("html")

proc to*(node: JsonNode, T: typedesc[MessageType]): MessageType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum MessageType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("text"):
    return MessageType.Text
  of $("html"):
    return MessageType.Html
  else:
    raise newException(ValueError, "Invalid enum value for MessageType: " & strVal)

