#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_vat_item

type VatSummary* = object
  ## 
  inputTaxItems*: seq[VatItem]
  outputTaxItems*: seq[VatItem]
  totalInputTax*: string
  totalOutputTax*: string
  vatDue*: string


# Custom JSON deserialization for VatSummary with custom field names
proc to*(node: JsonNode, T: typedesc[VatSummary]): VatSummary =
  result = VatSummary()
  if node.kind == JObject:
    if node.hasKey("input_tax_items"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["input_tax_items"]
      if arrayNode.kind == JArray:
        result.inputTaxItems = @[]
        for item in arrayNode.items:
          result.inputTaxItems.add(to(item, VatItem))
    if node.hasKey("output_tax_items"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["output_tax_items"]
      if arrayNode.kind == JArray:
        result.outputTaxItems = @[]
        for item in arrayNode.items:
          result.outputTaxItems.add(to(item, VatItem))
    if node.hasKey("total_input_tax"):
      result.totalInputTax = to(node["total_input_tax"], string)
    if node.hasKey("total_output_tax"):
      result.totalOutputTax = to(node["total_output_tax"], string)
    if node.hasKey("vat_due"):
      result.vatDue = to(node["vat_due"], string)

# Custom JSON serialization for VatSummary with custom field names
proc `%`*(obj: VatSummary): JsonNode =
  result = newJObject()
  result["input_tax_items"] = %obj.inputTaxItems
  result["output_tax_items"] = %obj.outputTaxItems
  result["total_input_tax"] = %obj.totalInputTax
  result["total_output_tax"] = %obj.totalOutputTax
  result["vat_due"] = %obj.vatDue

