#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_gdpr_activity
import model_gdpr_api_key
import model_gdpr_billing_info
import model_gdpr_notification
import model_gdpr_refresh_token
import model_gdpr_tenant
import model_gdpr_usage_event
import model_gdpr_user

type GdprExport* = object
  ## 
  activityLog*: seq[GdprActivity]
  apiKeys*: seq[GdprApiKey] ## Key identifiers and names only — never a usable credential.
  billing*: seq[GdprBillingInfo]
  exportedAt*: string
  generatedByAi*: bool ## Honesty field: this document is a plain data dump, never AI-generated.
  notifications*: seq[GdprNotification]
  refreshTokens*: seq[GdprRefreshToken] ## Session records: metadata only, never the token hash.
  tenants*: seq[GdprTenant]
  usageEvents*: seq[GdprUsageEvent]
  user*: GdprUser

