#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_plugin_pricing_one_of
import model_plugin_pricing_one_of1
import model_plugin_pricing_one_of2

# OneOf type
type PluginPricingKind* {.pure.} = enum
  PluginPricingOneOfVariant
  PluginPricingOneOf1Variant
  PluginPricingOneOf2Variant

type PluginPricing* = object
  ## How a plugin is priced in the marketplace. Tagged on `type` so the same enum deserializes both the API DTO and the `plugin_marketplace.json` manifest (`{\"type\":\"free\"}` / `{\"type\":\"one_time\",\"price\":99.0}` / `{\"type\":\"recurring\",\"price_per_month\":19.9}`).
  case kind*: PluginPricingKind
  of PluginPricingKind.PluginPricingOneOfVariant:
    PluginPricing_oneOfValue*: PluginPricingOneOf
  of PluginPricingKind.PluginPricingOneOf1Variant:
    PluginPricing_oneOf_1Value*: PluginPricingOneOf1
  of PluginPricingKind.PluginPricingOneOf2Variant:
    PluginPricing_oneOf_2Value*: PluginPricingOneOf2

proc to*(node: JsonNode, T: typedesc[PluginPricing]): PluginPricing =
  ## Custom deserializer for oneOf type - tries each variant
  try:
    return PluginPricing(kind: PluginPricingKind.PluginPricingOneOfVariant, PluginPricing_oneOfValue: to(node, PluginPricingOneOf))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginPricingOneOf: ", e.msg
  try:
    return PluginPricing(kind: PluginPricingKind.PluginPricingOneOf1Variant, PluginPricing_oneOf_1Value: to(node, PluginPricingOneOf1))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginPricingOneOf1: ", e.msg
  try:
    return PluginPricing(kind: PluginPricingKind.PluginPricingOneOf2Variant, PluginPricing_oneOf_2Value: to(node, PluginPricingOneOf2))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PluginPricingOneOf2: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PluginPricing. JSON: " & $node)

