#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CouponValidation* = object
  ## 
  code*: string
  discountType*: string
  discountValue*: string
  discountedAmount*: string
  maxDiscountAmount*: Option[string]
  reason*: Option[string]
  valid*: bool


# Custom JSON deserialization for CouponValidation with custom field names
proc to*(node: JsonNode, T: typedesc[CouponValidation]): CouponValidation =
  result = CouponValidation()
  if node.kind == JObject:
    if node.hasKey("code"):
      result.code = to(node["code"], string)
    if node.hasKey("discount_type"):
      result.discountType = to(node["discount_type"], string)
    if node.hasKey("discount_value"):
      result.discountValue = to(node["discount_value"], string)
    if node.hasKey("discounted_amount"):
      result.discountedAmount = to(node["discounted_amount"], string)
    if node.hasKey("max_discount_amount") and node["max_discount_amount"].kind != JNull:
      result.maxDiscountAmount = some(to(node["max_discount_amount"], typeof(result.maxDiscountAmount.get())))
    if node.hasKey("reason") and node["reason"].kind != JNull:
      result.reason = some(to(node["reason"], typeof(result.reason.get())))
    if node.hasKey("valid"):
      result.valid = to(node["valid"], bool)

# Custom JSON serialization for CouponValidation with custom field names
proc `%`*(obj: CouponValidation): JsonNode =
  result = newJObject()
  result["code"] = %obj.code
  result["discount_type"] = %obj.discountType
  result["discount_value"] = %obj.discountValue
  result["discounted_amount"] = %obj.discountedAmount
  if obj.maxDiscountAmount.isSome():
    result["max_discount_amount"] = %obj.maxDiscountAmount.get()
  if obj.reason.isSome():
    result["reason"] = %obj.reason.get()
  result["valid"] = %obj.valid

