#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_tracking_event

type TrackingInfo* = object
  ## 
  carrier*: string
  estimatedDelivery*: Option[string]
  events*: seq[TrackingEvent]
  rawResponse*: Option[JsonNode]
  status*: string
  trackingNumber*: string


# Custom JSON deserialization for TrackingInfo with custom field names
proc to*(node: JsonNode, T: typedesc[TrackingInfo]): TrackingInfo =
  result = TrackingInfo()
  if node.kind == JObject:
    if node.hasKey("carrier"):
      result.carrier = to(node["carrier"], string)
    if node.hasKey("estimated_delivery") and node["estimated_delivery"].kind != JNull:
      result.estimatedDelivery = some(to(node["estimated_delivery"], typeof(result.estimatedDelivery.get())))
    if node.hasKey("events"):
      result.events = to(node["events"], seq[TrackingEvent])
    if node.hasKey("raw_response") and node["raw_response"].kind != JNull:
      result.rawResponse = some(to(node["raw_response"], typeof(result.rawResponse.get())))
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("tracking_number"):
      result.trackingNumber = to(node["tracking_number"], string)

# Custom JSON serialization for TrackingInfo with custom field names
proc `%`*(obj: TrackingInfo): JsonNode =
  result = newJObject()
  result["carrier"] = %obj.carrier
  if obj.estimatedDelivery.isSome():
    result["estimated_delivery"] = %obj.estimatedDelivery.get()
  result["events"] = %obj.events
  if obj.rawResponse.isSome():
    result["raw_response"] = %obj.rawResponse.get()
  result["status"] = %obj.status
  result["tracking_number"] = %obj.trackingNumber

