#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PackingCompleteRequest* = object
  ## 
  notes*: Option[string]
  orderNumber*: string
  shipmentId*: Option[string]
  videoUrl*: Option[string]


# Custom JSON deserialization for PackingCompleteRequest with custom field names
proc to*(node: JsonNode, T: typedesc[PackingCompleteRequest]): PackingCompleteRequest =
  result = PackingCompleteRequest()
  if node.kind == JObject:
    if node.hasKey("notes") and node["notes"].kind != JNull:
      result.notes = some(to(node["notes"], typeof(result.notes.get())))
    if node.hasKey("order_number"):
      result.orderNumber = to(node["order_number"], string)
    if node.hasKey("shipment_id") and node["shipment_id"].kind != JNull:
      result.shipmentId = some(to(node["shipment_id"], typeof(result.shipmentId.get())))
    if node.hasKey("video_url") and node["video_url"].kind != JNull:
      result.videoUrl = some(to(node["video_url"], typeof(result.videoUrl.get())))

# Custom JSON serialization for PackingCompleteRequest with custom field names
proc `%`*(obj: PackingCompleteRequest): JsonNode =
  result = newJObject()
  if obj.notes.isSome():
    result["notes"] = %obj.notes.get()
  result["order_number"] = %obj.orderNumber
  if obj.shipmentId.isSome():
    result["shipment_id"] = %obj.shipmentId.get()
  if obj.videoUrl.isSome():
    result["video_url"] = %obj.videoUrl.get()

