#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SendMessageDto* = object
  ## 
  body*: string
  isInternal*: Option[bool]


# Custom JSON deserialization for SendMessageDto with custom field names
proc to*(node: JsonNode, T: typedesc[SendMessageDto]): SendMessageDto =
  result = SendMessageDto()
  if node.kind == JObject:
    if node.hasKey("body"):
      result.body = to(node["body"], string)
    if node.hasKey("is_internal") and node["is_internal"].kind != JNull:
      result.isInternal = some(to(node["is_internal"], typeof(result.isInternal.get())))

# Custom JSON serialization for SendMessageDto with custom field names
proc `%`*(obj: SendMessageDto): JsonNode =
  result = newJObject()
  result["body"] = %obj.body
  if obj.isInternal.isSome():
    result["is_internal"] = %obj.isInternal.get()

