#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_vat_detail

type UmsatzsteuerReport* = object
  ## 
  generatedAt*: string
  inputTax*: seq[VatDetail]
  outputTax*: seq[VatDetail]
  period*: string
  totalInputTax*: string
  totalOutputTax*: string
  vatPayable*: string
  vatRefund*: string


# Custom JSON deserialization for UmsatzsteuerReport with custom field names
proc to*(node: JsonNode, T: typedesc[UmsatzsteuerReport]): UmsatzsteuerReport =
  result = UmsatzsteuerReport()
  if node.kind == JObject:
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("input_tax"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["input_tax"]
      if arrayNode.kind == JArray:
        result.inputTax = @[]
        for item in arrayNode.items:
          result.inputTax.add(to(item, VatDetail))
    if node.hasKey("output_tax"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["output_tax"]
      if arrayNode.kind == JArray:
        result.outputTax = @[]
        for item in arrayNode.items:
          result.outputTax.add(to(item, VatDetail))
    if node.hasKey("period"):
      result.period = to(node["period"], string)
    if node.hasKey("total_input_tax"):
      result.totalInputTax = to(node["total_input_tax"], string)
    if node.hasKey("total_output_tax"):
      result.totalOutputTax = to(node["total_output_tax"], string)
    if node.hasKey("vat_payable"):
      result.vatPayable = to(node["vat_payable"], string)
    if node.hasKey("vat_refund"):
      result.vatRefund = to(node["vat_refund"], string)

# Custom JSON serialization for UmsatzsteuerReport with custom field names
proc `%`*(obj: UmsatzsteuerReport): JsonNode =
  result = newJObject()
  result["generated_at"] = %obj.generatedAt
  result["input_tax"] = %obj.inputTax
  result["output_tax"] = %obj.outputTax
  result["period"] = %obj.period
  result["total_input_tax"] = %obj.totalInputTax
  result["total_output_tax"] = %obj.totalOutputTax
  result["vat_payable"] = %obj.vatPayable
  result["vat_refund"] = %obj.vatRefund

