#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type InvoiceType* {.pure.} = enum
  Invoice
  CreditNote
  AdvancePayment
  FinalSettlement
  SpecialBilling
  DownPaymentInvoice
  Proforma
  Recurring
  CancellationInvoice

func `%`*(v: InvoiceType): JsonNode =
  result = case v:
    of InvoiceType.Invoice: %"Invoice"
    of InvoiceType.CreditNote: %"CreditNote"
    of InvoiceType.AdvancePayment: %"AdvancePayment"
    of InvoiceType.FinalSettlement: %"FinalSettlement"
    of InvoiceType.SpecialBilling: %"SpecialBilling"
    of InvoiceType.DownPaymentInvoice: %"DownPaymentInvoice"
    of InvoiceType.Proforma: %"Proforma"
    of InvoiceType.Recurring: %"Recurring"
    of InvoiceType.CancellationInvoice: %"CancellationInvoice"

func `$`*(v: InvoiceType): string =
  result = case v:
    of InvoiceType.Invoice: $("Invoice")
    of InvoiceType.CreditNote: $("CreditNote")
    of InvoiceType.AdvancePayment: $("AdvancePayment")
    of InvoiceType.FinalSettlement: $("FinalSettlement")
    of InvoiceType.SpecialBilling: $("SpecialBilling")
    of InvoiceType.DownPaymentInvoice: $("DownPaymentInvoice")
    of InvoiceType.Proforma: $("Proforma")
    of InvoiceType.Recurring: $("Recurring")
    of InvoiceType.CancellationInvoice: $("CancellationInvoice")

proc to*(node: JsonNode, T: typedesc[InvoiceType]): InvoiceType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum InvoiceType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("Invoice"):
    return InvoiceType.Invoice
  of $("CreditNote"):
    return InvoiceType.CreditNote
  of $("AdvancePayment"):
    return InvoiceType.AdvancePayment
  of $("FinalSettlement"):
    return InvoiceType.FinalSettlement
  of $("SpecialBilling"):
    return InvoiceType.SpecialBilling
  of $("DownPaymentInvoice"):
    return InvoiceType.DownPaymentInvoice
  of $("Proforma"):
    return InvoiceType.Proforma
  of $("Recurring"):
    return InvoiceType.Recurring
  of $("CancellationInvoice"):
    return InvoiceType.CancellationInvoice
  else:
    raise newException(ValueError, "Invalid enum value for InvoiceType: " & strVal)

