#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type BankLookup* = object
  ## 
  bankName*: Option[string]
  bic*: Option[string]
  iban*: string
  nextgenpsd2Url*: Option[string]
  psd2Supported*: bool


# Custom JSON deserialization for BankLookup with custom field names
proc to*(node: JsonNode, T: typedesc[BankLookup]): BankLookup =
  result = BankLookup()
  if node.kind == JObject:
    if node.hasKey("bank_name") and node["bank_name"].kind != JNull:
      result.bankName = some(to(node["bank_name"], typeof(result.bankName.get())))
    if node.hasKey("bic") and node["bic"].kind != JNull:
      result.bic = some(to(node["bic"], typeof(result.bic.get())))
    if node.hasKey("iban"):
      result.iban = to(node["iban"], string)
    if node.hasKey("nextgenpsd2_url") and node["nextgenpsd2_url"].kind != JNull:
      result.nextgenpsd2Url = some(to(node["nextgenpsd2_url"], typeof(result.nextgenpsd2Url.get())))
    if node.hasKey("psd2_supported"):
      result.psd2Supported = to(node["psd2_supported"], bool)

# Custom JSON serialization for BankLookup with custom field names
proc `%`*(obj: BankLookup): JsonNode =
  result = newJObject()
  if obj.bankName.isSome():
    result["bank_name"] = %obj.bankName.get()
  if obj.bic.isSome():
    result["bic"] = %obj.bic.get()
  result["iban"] = %obj.iban
  if obj.nextgenpsd2Url.isSome():
    result["nextgenpsd2_url"] = %obj.nextgenpsd2Url.get()
  result["psd2_supported"] = %obj.psd2Supported

