#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ProformaInvoiceStatus* {.pure.} = enum
  Draft
  Sent
  Converted

func `%`*(v: ProformaInvoiceStatus): JsonNode =
  result = case v:
    of ProformaInvoiceStatus.Draft: %"draft"
    of ProformaInvoiceStatus.Sent: %"sent"
    of ProformaInvoiceStatus.Converted: %"converted"

func `$`*(v: ProformaInvoiceStatus): string =
  result = case v:
    of ProformaInvoiceStatus.Draft: $("draft")
    of ProformaInvoiceStatus.Sent: $("sent")
    of ProformaInvoiceStatus.Converted: $("converted")

proc to*(node: JsonNode, T: typedesc[ProformaInvoiceStatus]): ProformaInvoiceStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ProformaInvoiceStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("draft"):
    return ProformaInvoiceStatus.Draft
  of $("sent"):
    return ProformaInvoiceStatus.Sent
  of $("converted"):
    return ProformaInvoiceStatus.Converted
  else:
    raise newException(ValueError, "Invalid enum value for ProformaInvoiceStatus: " & strVal)

