#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AnlageGKfzHinweis* = object
  ## 
  bezeichnung*: string
  kennzeichen*: string
  privatAnteilProzent*: string


# Custom JSON deserialization for AnlageGKfzHinweis with custom field names
proc to*(node: JsonNode, T: typedesc[AnlageGKfzHinweis]): AnlageGKfzHinweis =
  result = AnlageGKfzHinweis()
  if node.kind == JObject:
    if node.hasKey("bezeichnung"):
      result.bezeichnung = to(node["bezeichnung"], string)
    if node.hasKey("kennzeichen"):
      result.kennzeichen = to(node["kennzeichen"], string)
    if node.hasKey("privat_anteil_prozent"):
      result.privatAnteilProzent = to(node["privat_anteil_prozent"], string)

# Custom JSON serialization for AnlageGKfzHinweis with custom field names
proc `%`*(obj: AnlageGKfzHinweis): JsonNode =
  result = newJObject()
  result["bezeichnung"] = %obj.bezeichnung
  result["kennzeichen"] = %obj.kennzeichen
  result["privat_anteil_prozent"] = %obj.privatAnteilProzent

