#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type DhlCredentials* = object
  ## 
  apiKey*: string ## DHL-API-Key from developer.dhl.com (required for tracking).
  clientId*: Option[string] ## Client credentials from the DHL developer app; required for label creation.
  clientSecret*: Option[string]


# Custom JSON deserialization for DhlCredentials with custom field names
proc to*(node: JsonNode, T: typedesc[DhlCredentials]): DhlCredentials =
  result = DhlCredentials()
  if node.kind == JObject:
    if node.hasKey("api_key"):
      result.apiKey = to(node["api_key"], string)
    if node.hasKey("client_id") and node["client_id"].kind != JNull:
      result.clientId = some(to(node["client_id"], typeof(result.clientId.get())))
    if node.hasKey("client_secret") and node["client_secret"].kind != JNull:
      result.clientSecret = some(to(node["client_secret"], typeof(result.clientSecret.get())))

# Custom JSON serialization for DhlCredentials with custom field names
proc `%`*(obj: DhlCredentials): JsonNode =
  result = newJObject()
  result["api_key"] = %obj.apiKey
  if obj.clientId.isSome():
    result["client_id"] = %obj.clientId.get()
  if obj.clientSecret.isSome():
    result["client_secret"] = %obj.clientSecret.get()

