#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PrintDeliveryNoteResponse* = object
  ## 
  message*: string
  pdfUrl*: Option[string]
  success*: bool


# Custom JSON deserialization for PrintDeliveryNoteResponse with custom field names
proc to*(node: JsonNode, T: typedesc[PrintDeliveryNoteResponse]): PrintDeliveryNoteResponse =
  result = PrintDeliveryNoteResponse()
  if node.kind == JObject:
    if node.hasKey("message"):
      result.message = to(node["message"], string)
    if node.hasKey("pdf_url") and node["pdf_url"].kind != JNull:
      result.pdfUrl = some(to(node["pdf_url"], typeof(result.pdfUrl.get())))
    if node.hasKey("success"):
      result.success = to(node["success"], bool)

# Custom JSON serialization for PrintDeliveryNoteResponse with custom field names
proc `%`*(obj: PrintDeliveryNoteResponse): JsonNode =
  result = newJObject()
  result["message"] = %obj.message
  if obj.pdfUrl.isSome():
    result["pdf_url"] = %obj.pdfUrl.get()
  result["success"] = %obj.success

