#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SyncLog* = object
  ## 
  completedAt*: Option[string]
  connectionId*: string
  errorMessage*: Option[string]
  itemsFailed*: int
  itemsSynced*: int
  logId*: string
  platform*: string
  startedAt*: string
  status*: string
  syncType*: string


# Custom JSON deserialization for SyncLog with custom field names
proc to*(node: JsonNode, T: typedesc[SyncLog]): SyncLog =
  result = SyncLog()
  if node.kind == JObject:
    if node.hasKey("completed_at") and node["completed_at"].kind != JNull:
      result.completedAt = some(to(node["completed_at"], typeof(result.completedAt.get())))
    if node.hasKey("connection_id"):
      result.connectionId = to(node["connection_id"], string)
    if node.hasKey("error_message") and node["error_message"].kind != JNull:
      result.errorMessage = some(to(node["error_message"], typeof(result.errorMessage.get())))
    if node.hasKey("items_failed"):
      result.itemsFailed = to(node["items_failed"], int)
    if node.hasKey("items_synced"):
      result.itemsSynced = to(node["items_synced"], int)
    if node.hasKey("log_id"):
      result.logId = to(node["log_id"], string)
    if node.hasKey("platform"):
      result.platform = to(node["platform"], string)
    if node.hasKey("started_at"):
      result.startedAt = to(node["started_at"], string)
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("sync_type"):
      result.syncType = to(node["sync_type"], string)

# Custom JSON serialization for SyncLog with custom field names
proc `%`*(obj: SyncLog): JsonNode =
  result = newJObject()
  if obj.completedAt.isSome():
    result["completed_at"] = %obj.completedAt.get()
  result["connection_id"] = %obj.connectionId
  if obj.errorMessage.isSome():
    result["error_message"] = %obj.errorMessage.get()
  result["items_failed"] = %obj.itemsFailed
  result["items_synced"] = %obj.itemsSynced
  result["log_id"] = %obj.logId
  result["platform"] = %obj.platform
  result["started_at"] = %obj.startedAt
  result["status"] = %obj.status
  result["sync_type"] = %obj.syncType

