#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SepaSequenceType* {.pure.} = enum
  FRST
  RCUR
  FNAL
  OOFF

func `%`*(v: SepaSequenceType): JsonNode =
  result = case v:
    of SepaSequenceType.FRST: %"FRST"
    of SepaSequenceType.RCUR: %"RCUR"
    of SepaSequenceType.FNAL: %"FNAL"
    of SepaSequenceType.OOFF: %"OOFF"

func `$`*(v: SepaSequenceType): string =
  result = case v:
    of SepaSequenceType.FRST: $("FRST")
    of SepaSequenceType.RCUR: $("RCUR")
    of SepaSequenceType.FNAL: $("FNAL")
    of SepaSequenceType.OOFF: $("OOFF")

proc to*(node: JsonNode, T: typedesc[SepaSequenceType]): SepaSequenceType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SepaSequenceType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("FRST"):
    return SepaSequenceType.FRST
  of $("RCUR"):
    return SepaSequenceType.RCUR
  of $("FNAL"):
    return SepaSequenceType.FNAL
  of $("OOFF"):
    return SepaSequenceType.OOFF
  else:
    raise newException(ValueError, "Invalid enum value for SepaSequenceType: " & strVal)

