#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ActivityStatus* {.pure.} = enum
  Open
  Done
  Cancelled

func `%`*(v: ActivityStatus): JsonNode =
  result = case v:
    of ActivityStatus.Open: %"open"
    of ActivityStatus.Done: %"done"
    of ActivityStatus.Cancelled: %"cancelled"

func `$`*(v: ActivityStatus): string =
  result = case v:
    of ActivityStatus.Open: $("open")
    of ActivityStatus.Done: $("done")
    of ActivityStatus.Cancelled: $("cancelled")

proc to*(node: JsonNode, T: typedesc[ActivityStatus]): ActivityStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum ActivityStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("open"):
    return ActivityStatus.Open
  of $("done"):
    return ActivityStatus.Done
  of $("cancelled"):
    return ActivityStatus.Cancelled
  else:
    raise newException(ValueError, "Invalid enum value for ActivityStatus: " & strVal)

