#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_gu_v_item

type GuVReport* = object
  ## 
  expenses*: seq[GuVItem]
  generatedAt*: string
  netIncome*: string
  period*: string
  revenue*: seq[GuVItem]
  totalExpenses*: string
  totalRevenue*: string


# Custom JSON deserialization for GuVReport with custom field names
proc to*(node: JsonNode, T: typedesc[GuVReport]): GuVReport =
  result = GuVReport()
  if node.kind == JObject:
    if node.hasKey("expenses"):
      result.expenses = to(node["expenses"], seq[GuVItem])
    if node.hasKey("generated_at"):
      result.generatedAt = to(node["generated_at"], string)
    if node.hasKey("net_income"):
      result.netIncome = to(node["net_income"], string)
    if node.hasKey("period"):
      result.period = to(node["period"], string)
    if node.hasKey("revenue"):
      result.revenue = to(node["revenue"], seq[GuVItem])
    if node.hasKey("total_expenses"):
      result.totalExpenses = to(node["total_expenses"], string)
    if node.hasKey("total_revenue"):
      result.totalRevenue = to(node["total_revenue"], string)

# Custom JSON serialization for GuVReport with custom field names
proc `%`*(obj: GuVReport): JsonNode =
  result = newJObject()
  result["expenses"] = %obj.expenses
  result["generated_at"] = %obj.generatedAt
  result["net_income"] = %obj.netIncome
  result["period"] = %obj.period
  result["revenue"] = %obj.revenue
  result["total_expenses"] = %obj.totalExpenses
  result["total_revenue"] = %obj.totalRevenue

