#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CustomerInfo* = object
  ## Additional information about the customer placing the shipment.
  annualVolume*: int
  isRegistered*: bool


# Custom JSON deserialization for CustomerInfo with custom field names
proc to*(node: JsonNode, T: typedesc[CustomerInfo]): CustomerInfo =
  result = CustomerInfo()
  if node.kind == JObject:
    if node.hasKey("annual_volume"):
      result.annualVolume = to(node["annual_volume"], int)
    if node.hasKey("is_registered"):
      result.isRegistered = to(node["is_registered"], bool)

# Custom JSON serialization for CustomerInfo with custom field names
proc `%`*(obj: CustomerInfo): JsonNode =
  result = newJObject()
  result["annual_volume"] = %obj.annualVolume
  result["is_registered"] = %obj.isRegistered

