#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type AiWorkerConfig* = object
  ## 
  autoReply*: bool
  createdAt*: string
  id*: string
  isActive*: bool
  maxToolCalls*: int
  model*: string
  name*: string
  provider*: string
  systemPrompt*: string
  tenantId*: string
  triggerOn*: seq[string]
  updatedAt*: Option[string]


# Custom JSON deserialization for AiWorkerConfig with custom field names
proc to*(node: JsonNode, T: typedesc[AiWorkerConfig]): AiWorkerConfig =
  result = AiWorkerConfig()
  if node.kind == JObject:
    if node.hasKey("auto_reply"):
      result.autoReply = to(node["auto_reply"], bool)
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("id"):
      result.id = to(node["id"], string)
    if node.hasKey("is_active"):
      result.isActive = to(node["is_active"], bool)
    if node.hasKey("max_tool_calls"):
      result.maxToolCalls = to(node["max_tool_calls"], int)
    if node.hasKey("model"):
      result.model = to(node["model"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("provider"):
      result.provider = to(node["provider"], string)
    if node.hasKey("system_prompt"):
      result.systemPrompt = to(node["system_prompt"], string)
    if node.hasKey("tenant_id"):
      result.tenantId = to(node["tenant_id"], string)
    if node.hasKey("trigger_on"):
      result.triggerOn = to(node["trigger_on"], seq[string])
    if node.hasKey("updated_at") and node["updated_at"].kind != JNull:
      result.updatedAt = some(to(node["updated_at"], typeof(result.updatedAt.get())))

# Custom JSON serialization for AiWorkerConfig with custom field names
proc `%`*(obj: AiWorkerConfig): JsonNode =
  result = newJObject()
  result["auto_reply"] = %obj.autoReply
  result["created_at"] = %obj.createdAt
  result["id"] = %obj.id
  result["is_active"] = %obj.isActive
  result["max_tool_calls"] = %obj.maxToolCalls
  result["model"] = %obj.model
  result["name"] = %obj.name
  result["provider"] = %obj.provider
  result["system_prompt"] = %obj.systemPrompt
  result["tenant_id"] = %obj.tenantId
  result["trigger_on"] = %obj.triggerOn
  if obj.updatedAt.isSome():
    result["updated_at"] = %obj.updatedAt.get()

