#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type OrderStateUpdate* = object
  ## 
  sendStateToShop*: Option[bool]
  state*: string


# Custom JSON deserialization for OrderStateUpdate with custom field names
proc to*(node: JsonNode, T: typedesc[OrderStateUpdate]): OrderStateUpdate =
  result = OrderStateUpdate()
  if node.kind == JObject:
    if node.hasKey("send_state_to_shop") and node["send_state_to_shop"].kind != JNull:
      result.sendStateToShop = some(to(node["send_state_to_shop"], typeof(result.sendStateToShop.get())))
    if node.hasKey("state"):
      result.state = to(node["state"], string)

# Custom JSON serialization for OrderStateUpdate with custom field names
proc `%`*(obj: OrderStateUpdate): JsonNode =
  result = newJObject()
  if obj.sendStateToShop.isSome():
    result["send_state_to_shop"] = %obj.sendStateToShop.get()
  result["state"] = %obj.state

