#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type DatevBookingPreview* = object
  ## 
  accountNumber*: string
  debitCredit*: string
  documentDate*: string
  documentText*: string
  netAmount*: string
  oppositeAccount*: string
  taxAmount*: Option[string]
  taxRate*: Option[string]


# Custom JSON deserialization for DatevBookingPreview with custom field names
proc to*(node: JsonNode, T: typedesc[DatevBookingPreview]): DatevBookingPreview =
  result = DatevBookingPreview()
  if node.kind == JObject:
    if node.hasKey("account_number"):
      result.accountNumber = to(node["account_number"], string)
    if node.hasKey("debit_credit"):
      result.debitCredit = to(node["debit_credit"], string)
    if node.hasKey("document_date"):
      result.documentDate = to(node["document_date"], string)
    if node.hasKey("document_text"):
      result.documentText = to(node["document_text"], string)
    if node.hasKey("net_amount"):
      result.netAmount = to(node["net_amount"], string)
    if node.hasKey("opposite_account"):
      result.oppositeAccount = to(node["opposite_account"], string)
    if node.hasKey("tax_amount") and node["tax_amount"].kind != JNull:
      result.taxAmount = some(to(node["tax_amount"], typeof(result.taxAmount.get())))
    if node.hasKey("tax_rate") and node["tax_rate"].kind != JNull:
      result.taxRate = some(to(node["tax_rate"], typeof(result.taxRate.get())))

# Custom JSON serialization for DatevBookingPreview with custom field names
proc `%`*(obj: DatevBookingPreview): JsonNode =
  result = newJObject()
  result["account_number"] = %obj.accountNumber
  result["debit_credit"] = %obj.debitCredit
  result["document_date"] = %obj.documentDate
  result["document_text"] = %obj.documentText
  result["net_amount"] = %obj.netAmount
  result["opposite_account"] = %obj.oppositeAccount
  if obj.taxAmount.isSome():
    result["tax_amount"] = %obj.taxAmount.get()
  if obj.taxRate.isSome():
    result["tax_rate"] = %obj.taxRate.get()

