#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type RfqStatus* {.pure.} = enum
  Draft
  Sent
  OfferReceived
  Rejected
  Converted

func `%`*(v: RfqStatus): JsonNode =
  result = case v:
    of RfqStatus.Draft: %"draft"
    of RfqStatus.Sent: %"sent"
    of RfqStatus.OfferReceived: %"offer_received"
    of RfqStatus.Rejected: %"rejected"
    of RfqStatus.Converted: %"converted"

func `$`*(v: RfqStatus): string =
  result = case v:
    of RfqStatus.Draft: $("draft")
    of RfqStatus.Sent: $("sent")
    of RfqStatus.OfferReceived: $("offer_received")
    of RfqStatus.Rejected: $("rejected")
    of RfqStatus.Converted: $("converted")

proc to*(node: JsonNode, T: typedesc[RfqStatus]): RfqStatus =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum RfqStatus, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("draft"):
    return RfqStatus.Draft
  of $("sent"):
    return RfqStatus.Sent
  of $("offer_received"):
    return RfqStatus.OfferReceived
  of $("rejected"):
    return RfqStatus.Rejected
  of $("converted"):
    return RfqStatus.Converted
  else:
    raise newException(ValueError, "Invalid enum value for RfqStatus: " & strVal)

