#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type Shareholder* = object
  ## 
  address*: Option[string] ## Anschrift des Aktionärs (§ 67 Abs. 1 AktG).
  birthDate*: Option[string] ## Geburtsdatum des Aktionärs (§ 67 Abs. 1 AktG).
  email*: Option[string] ## Elektronische Adresse (E-Mail) für die Kommunikation der Gesellschaft.
  firstName*: Option[string] ## Vorname des Aktionärs (§ 67 Abs. 1 AktG).
  lastName*: Option[string] ## Nachname des Aktionärs (§ 67 Abs. 1 AktG).
  shareNumber*: Option[string] ## Aktiennummer bzw. Sammelurkunde (bei Nennbetragsaktien).
  shares*: Option[string] ## Stückzahl der gehaltenen Stückaktien (§ 67 Abs. 1 AktG).

