#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_bom_status

type Bom* = object
  ## 
  components*: Option[JsonNode] ## JSON array of `{product_id, name, quantity, unit, scrap_rate}`.
  description*: Option[string]
  name*: string
  outputQuantity*: Option[int64] ## Output quantity per production run (defaults to 1).
  productId*: string ## The finished product this BOM produces. References the product entity.
  status*: Option[BomStatus] ## One of: draft | active | archived

