#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_posting_category_type

type PostingCategoryCreate* = object
  ## 
  accountNumber*: Option[string]
  accountNumberSkr03*: Option[string]
  accountNumberSkr04*: Option[string]
  accountNumberSkr49*: Option[string]
  categoryType*: PostingCategoryType
  createdAt*: string
  defaultVatRate*: int
  description*: Option[string]
  eksCategory*: Option[string]
  euVatLine*: Option[int]
  inputVatPercentage*: string
  isActive*: bool
  isSystem*: bool
  name*: string
  skrVersion*: string
  updatedAt*: Option[string]
  userModifiedSkr03*: bool
  userModifiedSkr04*: bool

