#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_object

type PluginErrorOneOf* = object
  ## 
  badRequest*: seq[JsonNode]


# Custom JSON deserialization for PluginErrorOneOf with custom field names
proc to*(node: JsonNode, T: typedesc[PluginErrorOneOf]): PluginErrorOneOf =
  result = PluginErrorOneOf()
  if node.kind == JObject:
    if node.hasKey("BadRequest"):
      result.badRequest = to(node["BadRequest"], seq[JsonNode])

# Custom JSON serialization for PluginErrorOneOf with custom field names
proc `%`*(obj: PluginErrorOneOf): JsonNode =
  result = newJObject()
  result["BadRequest"] = %obj.badRequest

