#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type TimeEntryDto* = object
  ## API shape returned to the frontend (matches `frontend/src/types/time-entry.ts`).
  clockIn*: Option[string]
  clockOut*: Option[string]
  createdAt*: string
  date*: string
  employeeId*: string
  hours*: Option[string]
  notes*: Option[string]
  timeEntryId*: string


# Custom JSON deserialization for TimeEntryDto with custom field names
proc to*(node: JsonNode, T: typedesc[TimeEntryDto]): TimeEntryDto =
  result = TimeEntryDto()
  if node.kind == JObject:
    if node.hasKey("clock_in") and node["clock_in"].kind != JNull:
      result.clockIn = some(to(node["clock_in"], typeof(result.clockIn.get())))
    if node.hasKey("clock_out") and node["clock_out"].kind != JNull:
      result.clockOut = some(to(node["clock_out"], typeof(result.clockOut.get())))
    if node.hasKey("created_at"):
      result.createdAt = to(node["created_at"], string)
    if node.hasKey("date"):
      result.date = to(node["date"], string)
    if node.hasKey("employee_id"):
      result.employeeId = to(node["employee_id"], string)
    if node.hasKey("hours") and node["hours"].kind != JNull:
      result.hours = some(to(node["hours"], typeof(result.hours.get())))
    if node.hasKey("notes") and node["notes"].kind != JNull:
      result.notes = some(to(node["notes"], typeof(result.notes.get())))
    if node.hasKey("time_entry_id"):
      result.timeEntryId = to(node["time_entry_id"], string)

# Custom JSON serialization for TimeEntryDto with custom field names
proc `%`*(obj: TimeEntryDto): JsonNode =
  result = newJObject()
  if obj.clockIn.isSome():
    result["clock_in"] = %obj.clockIn.get()
  if obj.clockOut.isSome():
    result["clock_out"] = %obj.clockOut.get()
  result["created_at"] = %obj.createdAt
  result["date"] = %obj.date
  result["employee_id"] = %obj.employeeId
  if obj.hours.isSome():
    result["hours"] = %obj.hours.get()
  if obj.notes.isSome():
    result["notes"] = %obj.notes.get()
  result["time_entry_id"] = %obj.timeEntryId

