#
# SimpleBilly API
# 
# Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
# The version of the OpenAPI document: 0.1.0
# Contact: support@simplebilly.com
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_service_assignment_status

type ServiceAssignmentUpdate* = object
  ## 
  employeeId*: Option[string] ## References the employees entity.
  jobId*: Option[string] ## References the service_jobs entity.
  notes*: Option[string]
  scheduledDate*: Option[string] ## Work day the assignment is scheduled for.
  scheduledEnd*: Option[string] ## Planned end time of the assignment.
  scheduledStart*: Option[string] ## Planned start time of the assignment.
  status*: Option[ServiceAssignmentStatus] ## Assignment lifecycle status: \"planned\", \"confirmed\", \"en_route\", \"in_progress\", \"completed\" or \"cancelled\".

